"""
lut_export.py — Serialize sovereign LUT to hardware-ready formats.

Outputs:
  binary  : packed Frac as (numerator, denominator) int16 pairs — 4 bytes each
  c_header: C array of structs for use in GhostOS / embedded firmware
  verilog : Verilog parameter/localparam block for BRAM ROM initialisation

All values are passed through exactly as stored — no float conversion.

CC0 1.0 Universal.
"""
from __future__ import annotations
import struct
from fractions import Fraction
from pathlib import Path
from typing import Iterable


# ── binary serialisation ─────────────────────────────────────────────────────

def frac_to_bytes(f: Fraction, *, bits: int = 16) -> bytes:
    """
    Pack a Fraction as signed (numerator, denominator) pair.
    Both fit in `bits`-wide signed integers.
    Raises ValueError if either part overflows the bit width.
    """
    limit = (1 << (bits - 1)) - 1
    n, d = int(f.numerator), int(f.denominator)
    if abs(n) > limit or abs(d) > limit:
        raise ValueError(f"Fraction {f} overflows {bits}-bit representation")
    fmt = '>hh' if bits == 16 else '>ii'
    return struct.pack(fmt, n, d)


def spread_lut_to_bytes(spreads: list[Fraction], *, bits: int = 16) -> bytes:
    """Pack a list of spread Fractions into a flat byte blob."""
    return b''.join(frac_to_bytes(s, bits=bits) for s in spreads)


def write_spread_lut_bin(path: str | Path, spreads: list[Fraction]) -> int:
    """Write binary blob. Returns number of bytes written."""
    data = spread_lut_to_bytes(spreads)
    Path(path).write_bytes(data)
    return len(data)


# ── C header ─────────────────────────────────────────────────────────────────

def write_c_header(path: str | Path,
                   spreads: list[Fraction],
                   guard: str = "SOVEREIGN_LUT_H") -> None:
    """
    Emit a C header with the spread table as a static const struct array.
    Each entry: { int16_t num; int16_t den; }
    """
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "/* Sovereign Geometry LUT — generated by lut_export.py */",
        "/* Values are exact rational fractions: value = num/den */",
        "/* CC0 1.0 Universal */",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct { int16_t num; int16_t den; } spu_frac_t;",
        "",
        f"#define SPU_IVM_SPREAD_LUT_LEN {len(spreads)}",
        "",
        "static const spu_frac_t spu_ivm_spread_lut[] = {",
    ]
    for i, s in enumerate(spreads):
        angle = i * 30
        lines.append(
            f"    {{ {int(s.numerator):3d}, {int(s.denominator):3d} }},"
            f"  /* s({angle}°) = {s} */"
        )
    lines += ["};", "", f"#endif /* {guard} */", ""]
    Path(path).write_text('\n'.join(lines))


# ── Verilog parameter block ───────────────────────────────────────────────────

def write_verilog_params(path: str | Path,
                         spreads: list[Fraction],
                         module_name: str = "spu_sovereign_lut") -> None:
    """
    Emit a Verilog localparams block for BRAM initialisation.
    Each spread is packed as {numerator[15:0], denominator[15:0]} = 32 bits.
    Compatible with $readmemh and Gowin/iCE40 BSRAM init.
    """
    lines = [
        f"// {module_name}.vh — Sovereign Geometry LUT (Verilog parameters)",
        "// Generated by lut_export.py — CC0 1.0 Universal",
        "// Format: [31:16] = numerator (signed), [15:0] = denominator (signed)",
        "",
        f"localparam integer SPU_IVM_SPREAD_LUT_LEN = {len(spreads)};",
        "",
    ]
    for i, s in enumerate(spreads):
        n = int(s.numerator) & 0xFFFF
        d = int(s.denominator) & 0xFFFF
        packed = (n << 16) | d
        angle = i * 30
        lines.append(
            f"localparam [31:0] SPU_SPREAD_{i:02d} = 32'h{packed:08X};"
            f" // s({angle}°) = {s}"
        )
    lines += [""]

    # Also emit as a packed array init for $readmemh
    lines += [
        "",
        "// $readmemh initialisation string (12 entries × 4 bytes = 12 lines):",
    ]
    for i, s in enumerate(spreads):
        n = int(s.numerator) & 0xFFFF
        d = int(s.denominator) & 0xFFFF
        packed = (n << 16) | d
        lines.append(f"// {packed:08X}  // [{i:2d}] s({i*30}°) = {s}")

    Path(path).write_text('\n'.join(lines))


# ── human-readable manifest ───────────────────────────────────────────────────

def write_manifest(path: str | Path,
                   spreads: list[Fraction],
                   jitterbug: dict,
                   tensegrity_prism: dict,
                   tensegrity_icosa: dict,
                   synergetics: dict) -> None:
    """Write a human-readable text manifest of all LUT contents."""
    lines = [
        "═══════════════════════════════════════════════════════",
        "  Sovereign Geometry LUT — identity manifest",
        "  Generated by lut_export.py — CC0 1.0 Universal",
        "═══════════════════════════════════════════════════════",
        "",
        "IVM SPREAD TABLE (30° steps, rational)",
        "─" * 40,
    ]
    for i, s in enumerate(spreads):
        approx = float(s)
        lines.append(f"  s({i*30:3d}°) = {str(s):8s}  ≈ {approx:.4f}")

    lines += ["", "SYNERGETICS VOLUMES (tetrahedron = 1)", "─" * 40]
    for name, vol in synergetics.items():
        v = float(vol) if hasattr(vol, 'numerator') else vol.approx()
        lines.append(f"  {name:30s} = {str(vol):10s}  ≈ {v:.4f}")

    lines += ["", "JITTERBUG PHASES", "─" * 40]
    for phase, data in jitterbug.items():
        if isinstance(data, dict) and "name" in data:
            vol = data["volume_ratio"]
            v = float(vol) if hasattr(vol, 'numerator') else vol.approx()
            lines.append(f"  {data['name']:40s}  vol ≈ {v:.4f}")

    lines += ["", "TENSEGRITY PRISM (3-strut, rational)", "─" * 40]
    for k, v in tensegrity_prism.items():
        if k != "note":
            lines.append(f"  {k:30s} = {v}")
    lines.append(f"  note: {tensegrity_prism['note']}")

    lines += ["", "TENSEGRITY ICOSAHEDRON (6-strut, Q(√5))", "─" * 40]
    for k, v in tensegrity_icosa.items():
        if k not in ("note", "vertices", "strut_pairs", "check_fn"):
            approx = v.approx() if hasattr(v, 'approx') else float(v)
            lines.append(f"  {k:30s} = {v!r:30s}  ≈ {approx:.6f}")
    lines.append(f"  note: {tensegrity_icosa['note']}")

    lines += [""]
    Path(path).write_text('\n'.join(lines))


# ── main export entry point ───────────────────────────────────────────────────

def export_all(out_dir: str | Path = "software/flash") -> None:
    """Run all exports into out_dir."""
    from .sovereign_lut import (
        SPREAD_LUT, JITTERBUG, TENSEGRITY_PRISM,
        TENSEGRITY_ICOSA, SYNERGETICS_VOLUMES,
    )

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    n = write_spread_lut_bin(out / "sovereign_spread_lut.bin", SPREAD_LUT)
    print(f"  sovereign_spread_lut.bin    {n} bytes")

    write_c_header(out / "sovereign_lut.h", SPREAD_LUT)
    print(f"  sovereign_lut.h             C header")

    write_verilog_params(out / "sovereign_lut.vh", SPREAD_LUT)
    print(f"  sovereign_lut.vh            Verilog params")

    write_manifest(
        out / "sovereign_lut_manifest.txt",
        SPREAD_LUT, JITTERBUG, TENSEGRITY_PRISM,
        TENSEGRITY_ICOSA, SYNERGETICS_VOLUMES,
    )
    print(f"  sovereign_lut_manifest.txt  human-readable manifest")


if __name__ == "__main__":
    import sys
    out = sys.argv[1] if len(sys.argv) > 1 else "software/flash"
    print(f"Exporting sovereign LUT to {out}/")
    export_all(out)
    print("Done.")
