#!/usr/bin/env python3
"""
generate_gowin_constraints.py - Sierpinski -> Gowin .cst INS_LOC scaffold

Generates a simple Sierpinski carpet at a given recursion depth, maps the 2D
coordinates onto a Gowin grid (rows x cols) and emits INS_LOC lines suitable
for manual placement (.cst) plus a CSV mapping for verification.

Usage:
  python generate_gowin_constraints.py --depth 3 --rows 200 --cols 100 \
    --prefix u_spu26/node --output-cst gowin_sierpinski.cst \
    --output-csv gowin_sierpinski_map.csv

This is a lightweight POC. The mapping function is intentionally simple; tune
scaling/offsets and collision handling for your Tang-25k floorplan.
"""

import argparse
import csv

def sierpinski_carpet(depth):
    # Returns center points (x,y) in [0,1) for the Sierpinski carpet at `depth`
    coords = [(0.0, 0.0, 1.0)]
    for _ in range(depth):
        new = []
        for x, y, s in coords:
            s3 = s / 3.0
            for dx in range(3):
                for dy in range(3):
                    if dx == 1 and dy == 1:
                        # remove center
                        continue
                    new.append((x + dx * s3, y + dy * s3, s3))
        coords = new
    # return centre points
    return [(x + s / 2.0, y + s / 2.0) for x, y, s in coords]


def map_ivm_to_gowin(x, y, rows, cols, offset_row=0, offset_col=0):
    # Map normalized [0,1) x,y to integer row/col on device grid
    row = int(offset_row + round(y * (rows - 1)))
    col = int(offset_col + round(x * (cols - 1)))
    # clamp
    row = max(0, min(rows - 1, row))
    col = max(0, min(cols - 1, col))
    return row, col


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--depth', type=int, default=3)
    p.add_argument('--rows', type=int, default=200)
    p.add_argument('--cols', type=int, default=100)
    p.add_argument('--offset-row', type=int, default=0)
    p.add_argument('--offset-col', type=int, default=0)
    p.add_argument('--prefix', type=str, default='u_spu26/node')
    p.add_argument('--output-cst', type=str, default='gowin_sierpinski.cst')
    p.add_argument('--output-csv', type=str, default='gowin_sierpinski_map.csv')
    args = p.parse_args()

    points = sierpinski_carpet(args.depth)
    seen = set()
    lines = []
    rows_list = []
    for i, (x, y) in enumerate(points):
        row, col = map_ivm_to_gowin(x, y, args.rows, args.cols, args.offset_row, args.offset_col)
        key = (row, col)
        if key in seen:
            # skip duplicates in this simple POC
            continue
        seen.add(key)
        inst = f'{args.prefix}_{i}'
        lines.append(f'INS_LOC "{inst}" R{row}C{col};')
        rows_list.append((inst, row, col, x, y))

    with open(args.output_cst, 'w') as f:
        f.write('// Generated by generate_gowin_constraints.py\n')
        for l in lines:
            f.write(l + '\n')

    with open(args.output_csv, 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['instance', 'row', 'col', 'x', 'y'])
        for r in rows_list:
            w.writerow(r)

    print(f'Wrote {len(rows_list)} mappings to {args.output_cst} and {args.output_csv}.')


if __name__ == '__main__':
    main()
