    ; ;; Generated by spu_compiler.py from /home/john/Projects/hardware/SPU/software/programs/call_demo.lith
    ; ;; Lithic-L → SPU-13 .sas assembly

;; call_demo.lith — CALL/RET Subroutine Test
;; Proves subroutine call and return with nested calls.
;;
;; Subroutine at label .quad_vec: loads a Quadray via QLDI, returns.
;; Main: calls .quad_vec with different values, verifies results.

;; ── Main (entry point) ────────────────────────────────────────────
    JMP .main
    
;; ── Subroutine: load QR0 with identity vector ──────────────────────
.quad_identity:
    IDNT QR0
    RET

;; ── Subroutine: load QR1 with rotated copy ─────────────────────────
.quad_rot60:
    ROTC QR1, QR0, 1
    RET

;; ── Main ───────────────────────────────────────────────────────────
.main:
    CALL .quad_identity   ;; QR0 = identity
    hex R0, QR0           ;; should show (1, 0)

    CALL .quad_rot60      ;; QR1 = ROTC(QR0, 60°)
    hex R1, QR1           ;; should show distinct from identity

    ;; Nested call: identity → rot60 → rot120
    CALL .quad_identity
    CALL .quad_rot60      ;; QR1 from identity
    ROTC QR2, QR1, 2      ;; QR2 from QR1 at 120°
    hex R2, QR2

