    ; ;; Generated by spu_compiler.py from /home/john/Projects/hardware/SPU/software/programs/delta_demo.lith
    ; ;; Lithic-L → SPU-13 .sas assembly

;; delta_demo.lith — Triple Quadrance Formula Demo
;; Exercise the DELTA opcode on Pythagorean triples.
;;
;; The Triple Quadrance Formula:
;;   (Q₃ − Q₁ − Q₂)² = 4·Q₁·Q₂·(1−s)
;; where s = k/steps is the spread of angle ABC.
;;
;; For a right triangle (k=steps, s=1): rhs² = 0, Q₃ = Q₁ + Q₂.
;; No sin/cos. No sqrt. Exact rational arithmetic.

;; ── Demo 1: 3-4-5 right triangle ──
;; Q1=3, Q2=4 → q_sum=7, at k=4 (s=1): rhs²=0 → 3-4-5 triangle
    ; ── delta_curve: Q1=3, Q2=4, 4 steps ──
    DELTA QR0, 3, 4, 4
    ; Q₃ = 7 ± √(4·3·4·(steps−k)/4)

QLOG QR0

;; ── Demo 2: Isosceles legs ──
;; Q1=Q2=3, 6 steps
    ; ── delta_curve: Q1=3, Q2=3, 6 steps ──
    DELTA QR1, 3, 3, 6
    ; Q₃ = 6 ± √(4·3·3·(steps−k)/6)

QLOG QR1

;; ── Demo 3: Large quadrances ──
;; Q1=25, Q2=144 → q_sum=169 (13²)
    ; ── delta_curve: Q1=25, Q2=144, 8 steps ──
    DELTA QR2, 25, 144, 8
    ; Q₃ = 169 ± √(4·25·144·(steps−k)/8)

QLOG QR2

;; ── Demo 4: Collapsed triangle (single step) ──
    ; ── delta_curve: Q1=5, Q2=5, 1 steps ──
    DELTA QR3, 5, 5, 1
    ; Q₃ = 10 ± √(4·5·5·(steps−k)/1)

QLOG QR3

;; ── Hex output for visualization ──
hex R0, QR0
hex R1, QR1
hex R2, QR2
hex R3, QR3

