    ; ;; Generated by spu_compiler.py from /home/john/Projects/hardware/SPU/software/programs/isa_test.lith
    ; ;; Lithic-L → SPU-13 .sas assembly

;; isa_test.lith — Comprehensive ISA Test Suite
;; Exercises every new opcode: ROTC, QLDI, DELTA, QSUB
;; plus polyhedron expansion and hex output.
;; Run with: python3 software/spu_forge.py simulate programs/isa_test.lith

;; ── Test 1: QLDI — Quadray Load Immediate ──
;; Load 4 integer components into QR0
QLDI QR0, -1, 0, 0, 1
hex R0, QR0

;; ── Test 2: ROTC 0° — Identity rotation ──
;; Apply identity rotation, result should equal source
ROTC QR1, QR0, 0
hex R1, QR1

;; ── Test 3: ROTC 60° — D-axis rotation ──
ROTC QR2, QR0, 1
hex R2, QR2

;; ── Test 4: ROTC 120° — D-axis rotation ──
ROTC QR3, QR0, 2
hex R3, QR3

;; ── Test 5: ROTC 240° — D-axis rotation ──
ROTC QR4, QR0, 4
hex R4, QR4

;; ── Test 6: QSUB — Quadray subtraction ──
;; QR5 = QR3 - QR2 (120° result minus 60° result)
QSUB QR5, QR3, QR2
QLOG QR5

;; ── Test 7: QLDI — Negative vertex ──
QLDI QR6, 1, 0, 0, -1
hex R6, QR6

;; ── Test 8: ROTC 180° — Half-turn ──
ROTC QR7, QR0, 3
hex R7, QR7

;; ── Test 9: ROTC 300° — 5/6 turn ──
ROTC QR8, QR0, 5
hex R8, QR8

;; ── Test 10: DELTA — Triple quadrance ──
;; Pythagorean triple: Q1=3, Q2=4 → q_sum=7, rhs²=0
    ; ── delta_curve: Q1=3, Q2=4, 4 steps ──
    DELTA QR0, 3, 4, 4
    ; Q₃ = 7 ± √(4·3·4·(steps−k)/4)

QLOG QR9

;; ── Test 11: Polyhedron — VE ──
;; Expands to 12 QLDI instructions
    ; ── VE: 12 vertices ──
    QLDI QR1, -1, 0, 0, 1
    ; vertex 0: (-1,0,0,1)
    QLDI QR2, -1, 0, 1, 0
    ; vertex 1: (-1,0,1,0)
    QLDI QR3, -1, 1, 0, 0
    ; vertex 2: (-1,1,0,0)
    QLDI QR4, 0, -1, 0, 1
    ; vertex 3: (0,-1,0,1)
    QLDI QR5, 0, -1, 1, 0
    ; vertex 4: (0,-1,1,0)
    QLDI QR6, 0, 0, -1, 1
    ; vertex 5: (0,0,-1,1)
    QLDI QR7, 0, 0, 1, -1
    ; vertex 6: (0,0,1,-1)
    QLDI QR8, 0, 1, -1, 0
    ; vertex 7: (0,1,-1,0)
    QLDI QR9, 0, 1, 0, -1
    ; vertex 8: (0,1,0,-1)
    QLDI QR10, 1, -1, 0, 0
    ; vertex 9: (1,-1,0,0)
    QLDI QR11, 1, 0, -1, 0
    ; vertex 10: (1,0,-1,0)
    QLDI QR12, 1, 0, 0, -1
    ; vertex 11: (1,0,0,-1)

    ; ;; 12 vertices loaded in QR1–QR12

;; Log first and last VE vertex
hex R10, QR1
hex R11, QR12

