    ; ;; Generated by spu_compiler.py from /home/john/Projects/hardware/SPU/software/programs/robot_arm_demo.lith
    ; ;; Lithic-L → SPU-13 .sas assembly

;; robot_arm_demo.lith — 2-joint arm with circular trajectory
;; Demonstrates: arc, chain, nlrep, snap, delta

;; Initialize Quadray basis vectors
IDNT QR[0]              ; QR[0] = (1,0,0,0) — nucleus
IDNT QR[1]              ; QR[1] = B-axis start

;; ── Forward Kinematics Chain ──
;; 2-joint arm: D-axis at 60°, then B-axis at 240°
    ; ── fk_chain: 2 joints from QR0 ──
    ; joint 0: axis=3, F=2/3, G=2/3, H=-1/3
    ROTC QR0, QR0, 1
    ; 60° circulant rotation
    ; joint 1: axis=1, F=2/3, G=-1/3, H=2/3
    ROTC QR0, QR0, 4
    ; 240° circulant rotation


;; ── Circular Arc Trajectory ──
;; 12-step Pell orbit around the elbow (QR[0]) from wrist (QR[1])
    ; ── circular_arc: 12 Pell steps around QR0, axis 3 ──
    LD R8, 2, 1
    ; R8 = Pell rotor (2+√3)
    QSUB QR5, QR1, QR0
    ; QR5 = offset = QR1 - QR0
    QLOG QR1
    ; step 0: start point
    ; step 1
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 2
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 3
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 4
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 5
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 6
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 7
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 8
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 9
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 10
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 11
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6
    ; step 12
    QROT QR5, R8
    QADD QR6, QR5, QR0
    QLOG QR6


;; ── Cayley NLERP ──
;; Interpolate between Pell step 2 and step 6 at t=1/2
    ; ── cayley_nlrep: step 2→6 at t=1/2 → step 4 ──
    LD R[0], 97, 56
    ; Pell rotor r^4 = (97+56√3), polarity=−


;; ── Delta Curve ──
;; Parameterize Q₃ for Q₁=3, Q₂=4 as spread varies
    ; ── delta_curve: Q1=3, Q2=4, 4 steps ──
    DELTA QR0, 3, 4, 4
    ; Q₃ = 7 ± √(4·3·4·(steps−k)/4)


;; ── Davis Gate Snap ──
    ; ── davis_snap: laminar check ──
    SNAP 
    EQUIL 


HALT

