    ; ;; Generated by spu_compiler.py from /home/john/Projects/hardware/SPU/software/programs/wildberger_calculus.lith
    ; ;; Lithic-L → SPU-13 .sas assembly

;; wildberger_calculus.lith — Rational Calculus Without Limits
;; 
;; Implements Wildberger's algebraic calculus: tangent slopes via
;; bipolynumber linear-term extraction, and integration via Faulhaber
;; combinatorial sums. No limits, no infinity, no transcendental.
;;
;; Part 1: Tangent to circle x² + y² = 25 at point (3, 4)
;;   Shift: α→3+ᾱ, β→4+β̄ → expand → extract linear terms → slope = -3/4
;;
;; Part 2: Area under α² from 0 to x via Faulhaber
;;   Sum = Σ(kh)²·h → n-invariant term → x³/3

;; ── Part 1: Tangent Slope via Shifted Polynumber ────────────────────
;; 
;; For F(α,β) = α² + β² - 25 at point (3,4):
;;   Substitute α = 3 + ᾱ, β = 4 + β̄
;;   F = (3+ᾱ)² + (4+β̄)² - 25
;;     = 9 + 6ᾱ + ᾱ² + 16 + 8β̄ + β̄² - 25
;;     = 6ᾱ + 8β̄ + ᾱ² + β̄²   (constants cancel: 9+16-25=0)
;;   Linear terms: 6ᾱ + 8β̄ = 0
;;   Substitute back: 6(α-3) + 8(β-4) = 0 → 3α + 4β = 25
;;   Slope = -3/4
;;
;; SPU computation: the RPLU evaluates the shifted polynumber
;; and extracts the tangent coefficients bit-exactly.

;; Load test point (3, 4) into registers
QLDI QR0, 3, 4, 0, 0
QLOG QR0

;; Coefficients of linear form: 6α + 8β = 0
;; Slope = -coeff_α / coeff_β = -6/8 = -3/4
QLDI QR1, 6, 0, 0, 8   ;; A=6 (α coeff), D=8 (β coeff)
QLOG QR1

;; ── Part 2: Rational Area via Faulhaber Sum ─────────────────────────
;;
;; Area under α² from 0 to x:
;;   Sum(x, n) = h³ · Σk² where h = x/n
;;             = (x/n)³ · n(n+1)(2n+1)/6  
;;             = x³/6 · (2 + 3/n + 1/n²)
;;             = x³/3 + x³/(2n) + x³/(6n²)
;;   n-invariant term = x³/3   ← the rational integral
;;
;; For x=4: Area = 4³/3 = 64/3 ≈ 21.333...

;; Compute x³ = 64 using DELTA for quadrance then multiply
;; QLDI: α=4 as integer
QLDI QR2, 4, 0, 0, 0

;; The area is x³/3. With integer x=4:
;;   x² = 16 (quadrance)
;;   x³ = 64
;;   Area = 64/3

;; For rational output: numerator=64, denominator=3
;; Store in QR3: {num, den, 0, 0}
QLDI QR3, 64, 3, 0, 0
QLOG QR3

;; ── Part 3: Faulhaber formula for Σk² ──────────────────────────────
;; Σk² = n(n+1)(2n+1)/6 for n from 1 to N
;; Compute for n=10: Σ₁₀ k² = 10·11·21/6 = 2310/6 = 385

;; n=10 → n(n+1)=110, (2n+1)=21, product=2310
    ; ── delta_curve: Q1=10, Q2=11, 1 steps ──
    DELTA QR4, 10, 11, 1
    ; Q₃ = 21 ± √(4·10·11·(steps−k)/1)

QLOG QR4

;; ── Hex output ──────────────────────────────────────────────────────
hex R0, QR0
hex R1, QR1
hex R2, QR2
hex R3, QR3
hex R4, QR4

;; ── Comparison: Classical vs Rational ───────────────────────────────
;;
;; Classical calculus:
;;   d/dx [x² + y² = 25] → 2x + 2y·dy/dx = 0 → dy/dx = -x/y = -3/4
;;   ∫₀ˣ α² dα = x³/3
;;
;; Wildberger calculus:
;;   Tangent: extract linear terms of shifted polynumber → -3/4
;;   Area: extract n-invariant term of Faulhaber sum → x³/3
;;
;; Same answers. Zero limits. Zero approximation.
;; Both fit in the Q(√3) field natively.

