    ; ;; Generated by spu_compiler.py from /home/john/Projects/hardware/SPU/software/programs/wildberger_spread.lith
    ; ;; Lithic-L → SPU-13 .sas assembly

;; wildberger_spread.lith — Rational Trigonometry Primitives
;; Computes spread, quadrance, collinearity without sin/cos/sqrt.
;; Maps directly to SPU-13 DELTA and ROTC opcodes.
;;
;; Spread s = 1 − (Q₃−Q₁−Q₂)² / (4·Q₁·Q₂)
;; Collinearity: (Q₁+Q₂+Q₃)² = 2(Q₁²+Q₂²+Q₃²)

;; ── Primitive: spread_of_three_quadrances ──────────────────────────
;; Input:  Q1 in R0, Q2 in R1, Q3 in R2
;; Output: spread numerator in R3, spread denominator in R4
;; Uses:   QR3 for DELTA computation, QR4 for scratch
;;
;; Formula: s = 1 − (Q₃−Q₁−Q₂)² / (4·Q₁·Q₂)
;;   DELTA Q1 Q2 4 → QR3.B = 4·Q₁·Q₂
;;                    QR3.A = Q₁+Q₂
;;   rhs² = (Q₃ − QR3.A)² = (Q₃−Q₁−Q₂)²
;;   spread_num = 4·Q₁·Q₂ − rhs²
;;   spread_den = 4·Q₁·Q₂
;;
;; ── Instructions ────────────────────────────────────────────────────

;; --- load test values: 3-4-5 triangle ---
;; Q1=3, Q2=4, Q3=5 (right triangle: spread=1, collinear=false)
    ; ── delta_curve: Q1=3, Q2=4, 4 steps ──
    DELTA QR3, 3, 4, 4
    ; Q₃ = 7 ± √(4·3·4·(steps−k)/4)

;; QR3.A = 7 (Q₁+Q₂), QR3.B = 48 (4·Q₁·Q₂), QR3.C = 4

;; --- verify: for right triangle, Q₃=Q₁+Q₂ → rhs²=0 → s=48/48=1 ---
;; rhs² is already 0 in QR3.B for the right triangle
;; spread = 48/48 = 1  (perfect right angle)

;; --- test collinearity: 1-4-5 on a line ---
;; Q1=1, Q2=4, Q3=9 (collinear: 1+4+9=14, 2*(1+16+81)=196 → 14²=196 ✓)
    ; ── delta_curve: Q1=1, Q2=4, 4 steps ──
    DELTA QR4, 1, 4, 4
    ; Q₃ = 5 ± √(4·1·4·(steps−k)/4)

;; Check: (Q₁+Q₂+Q₃)² vs 2(Q₁²+Q₂²+Q₃²)
;;   LHS = (1+4+9)² = 14² = 196
;;   RHS = 2*(1+16+81) = 2*98 = 196
;; Equal → collinear ✓

;; ── hex output ──────────────────────────────────────────────────────
hex R0, QR3
hex R1, QR4

