#!/usr/bin/env python3
"""
software/tools/golden_primes.py — SPU-13 Golden Prime Generator
Finds the 13 most "Laminar" primes: maximally distant from all powers of 2.

Theory:
  A "Cubic" prime sits close to 2^k — it resonates with binary addressing.
  A "Golden" prime sits exactly between two consecutive powers of 2 — it
  cannot alias any binary frame boundary, giving maximum Quadray stride entropy.

  Dissonance score (pure integers, no float):
    k = bit_length(p) - 1          (floor of log2)
    lower = 1 << k                 (2^k)
    upper = 1 << (k+1)             (2^(k+1))
    midpoint = lower + (upper - lower) // 2
    dist_from_mid = abs(p - midpoint)   (0 = perfectly golden)
    score = upper - lower - 2*dist_from_mid   (higher = more laminar)

CC0 1.0 Universal — Public Domain
"""

import sys
import struct
import os

# ---------------------------------------------------------------------------
# Integer-only primality test
# ---------------------------------------------------------------------------

def is_prime(n: int) -> bool:
    if n < 2:
        return False
    if n in (2, 3):
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


# ---------------------------------------------------------------------------
# Integer-only laminar dissonance score
# ---------------------------------------------------------------------------

def laminar_score(p: int) -> int:
    """
    Higher score = more laminar (further from any power of 2).
    Purely integer arithmetic — no float.
    """
    k = p.bit_length() - 1          # floor(log2(p))
    lower = 1 << k
    upper = 1 << (k + 1)
    midpoint = lower + ((upper - lower) >> 1)
    dist = abs(p - midpoint)
    return (upper - lower) - 2 * dist   # max when p == midpoint


def generate_golden_primes(search_top: int = 65535, count: int = 13) -> list[int]:
    """
    Return the `count` primes in [2, search_top] with highest laminar score.
    """
    candidates = [(p, laminar_score(p)) for p in range(search_top, search_top // 2, -1)
                  if is_prime(p)]
    candidates.sort(key=lambda x: -x[1])
    return [p for p, _ in candidates[:count]]


# ---------------------------------------------------------------------------
# Flash binary output (matches flash_map.vh offset 0x100100)
# ---------------------------------------------------------------------------

def to_bin(primes: list[int]) -> bytes:
    """Pack 13 primes as 32-bit big-endian integers."""
    return b''.join(struct.pack('>I', p) for p in primes)


def to_verilog(primes: list[int], path: str):
    with open(path, 'w') as f:
        f.write("// AUTO-GENERATED by golden_primes.py — CC0 1.0\n")
        f.write("// SPU-13 Sovereign Golden Prime Set (integer laminar scoring)\n\n")
        for i, p in enumerate(primes):
            k = p.bit_length() - 1
            lower, upper = 1 << k, 1 << (k + 1)
            score = laminar_score(p)
            f.write(f"`define GOLDEN_PRIME_{i:02d} 16'd{p}"
                    f"  // 2^{k}={lower}..2^{k+1}={upper}  score={score}\n")
        f.write(f"\n`define GOLDEN_PRIME_DEFAULT `GOLDEN_PRIME_00\n")
    print(f"  Verilog header written: {path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="SPU-13 Golden Prime Generator")
    parser.add_argument('--top',   type=int, default=65535, help='Upper search bound')
    parser.add_argument('--count', type=int, default=13,    help='Number of primes')
    parser.add_argument('--bin',   metavar='FILE', help='Write binary output')
    parser.add_argument('--vh',    metavar='FILE', help='Write Verilog header')
    args = parser.parse_args()

    print(f"  Searching [{args.top//2}..{args.top}] for {args.count} golden primes…")
    primes = generate_golden_primes(args.top, args.count)

    print(f"\n  Golden Prime Set ({args.count} primes, highest laminar score first):")
    for i, p in enumerate(primes):
        k = p.bit_length() - 1
        lower, upper = 1 << k, 1 << (k + 1)
        score = laminar_score(p)
        mid = lower + ((upper - lower) >> 1)
        print(f"    [{i:02d}] {p:6d}  2^{k}={lower}..{mid}..{upper}  score={score}")

    if args.bin:
        data = to_bin(primes)
        with open(args.bin, 'wb') as f:
            f.write(data)
        print(f"\n  Binary written: {args.bin}  ({len(data)} bytes)")

    if args.vh:
        to_verilog(primes, args.vh)
