// SU(3) Padé(6,6) matrix exponential accelerator (prototype)
// Fixed-point Q16 implementation with scaling-and-squaring, Horner evaluation for matrix polynomials,
// and adjugate-based inverse for 3x3 matrix (determinant division).

module su3_pade66_accel (
    input  wire clk,
    input  wire rst_n,
    input  wire start,

    input  wire signed [31:0] g00, g01, g02,
    input  wire signed [31:0] g10, g11, g12,
    input  wire signed [31:0] g20, g21, g22,

    output reg  signed [31:0] e00, e01, e02,
    output reg  signed [31:0] e10, e11, e12,
    output reg  signed [31:0] e20, e21, e22,

    output reg done,
    output reg busy
);

// Load Padé(6,6) coefficients from mem (Q16 signed)
reg signed [31:0] num_coef [0:6];
reg signed [31:0] den_coef [0:6];
initial begin
    // files generated by tools/generate_pade_66_q16.py
    $readmemh("hardware/common/rtl/accel/pade6_num_q16.mem", num_coef);
    $readmemh("hardware/common/rtl/accel/pade6_den_q16.mem", den_coef);
end

// FSM states
localparam IDLE = 4'd0,
           LATCH = 4'd1,
           SCALE = 4'd2,
           HORNER_NUM_INIT = 4'd3,
           HORNER_NUM_STEP = 4'd4,
           HORNER_DEN_INIT = 4'd5,
           HORNER_DEN_STEP = 4'd6,
           INV = 4'd7,
           MUL = 4'd8,
           SQR = 4'd9,
           DONE = 4'd10;
reg [3:0] state;

// Latched A
reg signed [31:0] A00, A01, A02, A10, A11, A12, A20, A21, A22;
// Scaled S = A / 2^s_count
reg signed [31:0] S00, S01, S02, S10, S11, S12, S20, S21, S22;
// Horner accumulators P (used for numerator/denominator)
reg signed [31:0] P00, P01, P02, P10, P11, P12, P20, P21, P22;
// temporary for multiplication results
reg signed [31:0] T00, T01, T02, T10, T11, T12, T20, T21, T22;
// Numerator N and Denominator D matrices
reg signed [31:0] N00, N01, N02, N10, N11, N12, N20, N21, N22;
reg signed [31:0] D00, D01, D02, D10, D11, D12, D20, D21, D22;

// intermediate powers if needed
reg signed [31:0] A2_00, A2_01, A2_02, A2_10, A2_11, A2_12, A2_20, A2_21, A2_22;

// temporary 64/128-bit variables
reg signed [63:0] p0, p1, p2;
reg signed [127:0] big0, big1;

// inverse adjugate and determinant temporaries
reg signed [63:0] adj00, adj01, adj02, adj10, adj11, adj12, adj20, adj21, adj22;
reg signed [127:0] det_int; // det in scaled integer (S^3)

// extra temporaries used in always blocks
reg [31:0] m00, m01, m02, m10, m11, m12, m20, m21, m22;
reg [31:0] mx;
reg [63:0] tmp_shift;
reg signed [127:0] num0;
reg signed [31:0] inv00, inv01, inv02, inv10, inv11, inv12, inv20, inv21, inv22;

// counters
reg [3:0] horner_k;
reg [4:0] s_count;
reg [4:0] s_remaining;

// helper abs32
function [31:0] abs32;
    input signed [31:0] v;
    begin
        abs32 = v[31] ? -v : v;
    end
endfunction

integer i;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        state <= IDLE;
        busy <= 1'b0;
        done <= 1'b0;
        // clear regs
        A00 <= 32'sd0; A01 <= 32'sd0; A02 <= 32'sd0;
        A10 <= 32'sd0; A11 <= 32'sd0; A12 <= 32'sd0;
        A20 <= 32'sd0; A21 <= 32'sd0; A22 <= 32'sd0;
        S00 <= 32'sd0; S01 <= 32'sd0; S02 <= 32'sd0;
        S10 <= 32'sd0; S11 <= 32'sd0; S12 <= 32'sd0;
        S20 <= 32'sd0; S21 <= 32'sd0; S22 <= 32'sd0;
        P00 <= 32'sd0; P01 <= 32'sd0; P02 <= 32'sd0;
        P10 <= 32'sd0; P11 <= 32'sd0; P12 <= 32'sd0;
        P20 <= 32'sd0; P21 <= 32'sd0; P22 <= 32'sd0;
        N00 <= 32'sd0; N01 <= 32'sd0; N02 <= 32'sd0;
        N10 <= 32'sd0; N11 <= 32'sd0; N12 <= 32'sd0;
        N20 <= 32'sd0; N21 <= 32'sd0; N22 <= 32'sd0;
        D00 <= 32'sd0; D01 <= 32'sd0; D02 <= 32'sd0;
        D10 <= 32'sd0; D11 <= 32'sd0; D12 <= 32'sd0;
        D20 <= 32'sd0; D21 <= 32'sd0; D22 <= 32'sd0;
        e00 <= 32'sd0; e01 <= 32'sd0; e02 <= 32'sd0;
        e10 <= 32'sd0; e11 <= 32'sd0; e12 <= 32'sd0;
        e20 <= 32'sd0; e21 <= 32'sd0; e22 <= 32'sd0;
    end else begin
        case (state)
            IDLE: begin
                done <= 1'b0;
                busy <= 1'b0;
                if (start) begin
                    // latch inputs
                    A00 <= g00; A01 <= g01; A02 <= g02;
                    A10 <= g10; A11 <= g11; A12 <= g12;
                    A20 <= g20; A21 <= g21; A22 <= g22;
                    state <= LATCH;
                    busy <= 1'b1;
                end
            end
            LATCH: begin
                // compute max absolute element
                m00 = abs32(A00); m01 = abs32(A01); m02 = abs32(A02);
                m10 = abs32(A10); m11 = abs32(A11); m12 = abs32(A12);
                m20 = abs32(A20); m21 = abs32(A21); m22 = abs32(A22);
                mx = m00;
                if (m01 > mx) mx = m01; if (m02 > mx) mx = m02;
                if (m10 > mx) mx = m10; if (m11 > mx) mx = m11; if (m12 > mx) mx = m12;
                if (m20 > mx) mx = m20; if (m21 > mx) mx = m21; if (m22 > mx) mx = m22;
                // compute s_count = max(0, ceil(log2(mx / 65536)))
                s_count <= 0;
                if (mx <= 32'sd65536) begin
                    s_count <= 0;
                end else begin
                    // tmp shifting
                    tmp_shift = mx;
                    s_count <= 0;
                    while (tmp_shift > 32'sd65536 && s_count < 20) begin
                        tmp_shift = tmp_shift >> 1;
                        s_count <= s_count + 1;
                    end
                end
                s_remaining <= s_count;
                state <= SCALE;
            end
            SCALE: begin
                if (s_count == 0) begin
                    S00 <= A00; S01 <= A01; S02 <= A02;
                    S10 <= A10; S11 <= A11; S12 <= A12;
                    S20 <= A20; S21 <= A21; S22 <= A22;
                end else begin
                    S00 <= A00 >>> s_count; S01 <= A01 >>> s_count; S02 <= A02 >>> s_count;
                    S10 <= A10 >>> s_count; S11 <= A11 >>> s_count; S12 <= A12 >>> s_count;
                    S20 <= A20 >>> s_count; S21 <= A21 >>> s_count; S22 <= A22 >>> s_count;
                end
                state <= HORNER_NUM_INIT;
            end
            HORNER_NUM_INIT: begin
                // P = num_coef[6]*I
                P00 <= num_coef[6]; P01 <= 32'sd0; P02 <= 32'sd0;
                P10 <= 32'sd0; P11 <= num_coef[6]; P12 <= 32'sd0;
                P20 <= 32'sd0; P21 <= 32'sd0; P22 <= num_coef[6];
                horner_k <= 5; // next degree to process
                state <= HORNER_NUM_STEP;
            end
            HORNER_NUM_STEP: begin
                // TMP = S * P
                // compute each element with 64-bit products then >>16
                p0 = $signed(S00) * $signed(P00);
                p1 = $signed(S01) * $signed(P10);
                p2 = $signed(S02) * $signed(P20);
                T00 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S00) * $signed(P01);
                p1 = $signed(S01) * $signed(P11);
                p2 = $signed(S02) * $signed(P21);
                T01 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S00) * $signed(P02);
                p1 = $signed(S01) * $signed(P12);
                p2 = $signed(S02) * $signed(P22);
                T02 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S10) * $signed(P00);
                p1 = $signed(S11) * $signed(P10);
                p2 = $signed(S12) * $signed(P20);
                T10 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S10) * $signed(P01);
                p1 = $signed(S11) * $signed(P11);
                p2 = $signed(S12) * $signed(P21);
                T11 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S10) * $signed(P02);
                p1 = $signed(S11) * $signed(P12);
                p2 = $signed(S12) * $signed(P22);
                T12 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S20) * $signed(P00);
                p1 = $signed(S21) * $signed(P10);
                p2 = $signed(S22) * $signed(P20);
                T20 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S20) * $signed(P01);
                p1 = $signed(S21) * $signed(P11);
                p2 = $signed(S22) * $signed(P21);
                T21 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S20) * $signed(P02);
                p1 = $signed(S21) * $signed(P12);
                p2 = $signed(S22) * $signed(P22);
                T22 <= $signed((p0 + p1 + p2) >>> 16);

                // update P = TMP + num_coef[horner_k]*I
                P00 <= $signed(T00) + num_coef[horner_k];
                P01 <= T01; P02 <= T02;
                P10 <= T10; P11 <= $signed(T11) + num_coef[horner_k]; P12 <= T12;
                P20 <= T20; P21 <= T21; P22 <= $signed(T22) + num_coef[horner_k];

                if (horner_k == 0) begin
                    // finished numerator
                    N00 <= P00; N01 <= P01; N02 <= P02;
                    N10 <= P10; N11 <= P11; N12 <= P12;
                    N20 <= P20; N21 <= P21; N22 <= P22;
                    state <= HORNER_DEN_INIT;
                end else begin
                    horner_k <= horner_k - 1;
                    state <= HORNER_NUM_STEP; // next iteration
                end
            end
            HORNER_DEN_INIT: begin
                // D = den_coef[6]*I
                P00 <= den_coef[6]; P01 <= 32'sd0; P02 <= 32'sd0;
                P10 <= 32'sd0; P11 <= den_coef[6]; P12 <= 32'sd0;
                P20 <= 32'sd0; P21 <= 32'sd0; P22 <= den_coef[6];
                horner_k <= 5;
                state <= HORNER_DEN_STEP;
            end
            HORNER_DEN_STEP: begin
                // TMP = S * P
                p0 = $signed(S00) * $signed(P00);
                p1 = $signed(S01) * $signed(P10);
                p2 = $signed(S02) * $signed(P20);
                T00 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S00) * $signed(P01);
                p1 = $signed(S01) * $signed(P11);
                p2 = $signed(S02) * $signed(P21);
                T01 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S00) * $signed(P02);
                p1 = $signed(S01) * $signed(P12);
                p2 = $signed(S02) * $signed(P22);
                T02 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S10) * $signed(P00);
                p1 = $signed(S11) * $signed(P10);
                p2 = $signed(S12) * $signed(P20);
                T10 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S10) * $signed(P01);
                p1 = $signed(S11) * $signed(P11);
                p2 = $signed(S12) * $signed(P21);
                T11 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S10) * $signed(P02);
                p1 = $signed(S11) * $signed(P12);
                p2 = $signed(S12) * $signed(P22);
                T12 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S20) * $signed(P00);
                p1 = $signed(S21) * $signed(P10);
                p2 = $signed(S22) * $signed(P20);
                T20 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S20) * $signed(P01);
                p1 = $signed(S21) * $signed(P11);
                p2 = $signed(S22) * $signed(P21);
                T21 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(S20) * $signed(P02);
                p1 = $signed(S21) * $signed(P12);
                p2 = $signed(S22) * $signed(P22);
                T22 <= $signed((p0 + p1 + p2) >>> 16);

                // update P = TMP + den_coef[horner_k]*I
                P00 <= $signed(T00) + den_coef[horner_k];
                P01 <= T01; P02 <= T02;
                P10 <= T10; P11 <= $signed(T11) + den_coef[horner_k]; P12 <= T12;
                P20 <= T20; P21 <= T21; P22 <= $signed(T22) + den_coef[horner_k];

                if (horner_k == 0) begin
                    // finished denominator
                    D00 <= P00; D01 <= P01; D02 <= P02;
                    D10 <= P10; D11 <= P11; D12 <= P12;
                    D20 <= P20; D21 <= P21; D22 <= P22;
                    state <= INV;
                end else begin
                    horner_k <= horner_k - 1;
                    state <= HORNER_DEN_STEP; // next iteration
                end
            end
            INV: begin
                // compute adjugate (cofactor matrix) and determinant (integer math)
                // cofactors (2x2 minors): C00 = D11*D22 - D12*D21 etc.
                adj00 <= $signed(D11) * $signed(D22) - $signed(D12) * $signed(D21);
                adj01 <= -($signed(D10) * $signed(D22) - $signed(D12) * $signed(D20));
                adj02 <= $signed(D10) * $signed(D21) - $signed(D11) * $signed(D20);
                adj10 <= -($signed(D01) * $signed(D22) - $signed(D02) * $signed(D21));
                adj11 <= $signed(D00) * $signed(D22) - $signed(D02) * $signed(D20);
                adj12 <= -($signed(D00) * $signed(D21) - $signed(D01) * $signed(D20));
                adj20 <= $signed(D01) * $signed(D12) - $signed(D02) * $signed(D11);
                adj21 <= -($signed(D00) * $signed(D12) - $signed(D02) * $signed(D10));
                adj22 <= $signed(D00) * $signed(D11) - $signed(D01) * $signed(D10);

                // determinant det = D00*C00 + D01*C10 + D02*C20
                // Note: D elements are Q16, adj entries are Q32 (product of two Q16). So det_int will be Q48 scaling.
                big0 = $signed(D00);
                big1 = $signed(adj00);
                det_int <= big0 * big1 + $signed(D01) * $signed(adj10) + $signed(D02) * $signed(adj20);

                // if det == 0, just set identity (fallback)
                if (det_int == 0) begin
                    // set inv to identity
                    N00 <= N00; // keep numerator
                    // set X = N (i.e., assume D = I)
                    // compute X = N
                    N00 <= N00; // no-op to avoid lvalue warnings
                    // assign outputs directly
                    e00 <= N00; e01 <= N01; e02 <= N02;
                    e10 <= N10; e11 <= N11; e12 <= N12;
                    e20 <= N20; e21 <= N21; e22 <= N22;
                    state <= SQR;
                end else begin
                    state <= MUL; // compute invD * N
                end
            end
            MUL: begin
                // compute invD_Q16 = (adj * S) / det_int where S = 2^16
                // compute numerator adj * S (adj is Q32 -> adj*S is Q48)
                // then divide by det_int (Q48) -> yields dimensionless scaled by Q16
                // temporaries num0 and invXX are declared at module scope
                // S = 1<<16
                // S = 1<<16
                num0 = $signed(adj00) * 64'sd65536;
                inv00 = $signed(num0 / det_int);
                num0 = $signed(adj01) * 64'sd65536;
                inv01 = $signed(num0 / det_int);
                num0 = $signed(adj02) * 64'sd65536;
                inv02 = $signed(num0 / det_int);
                num0 = $signed(adj10) * 64'sd65536;
                inv10 = $signed(num0 / det_int);
                num0 = $signed(adj11) * 64'sd65536;
                inv11 = $signed(num0 / det_int);
                num0 = $signed(adj12) * 64'sd65536;
                inv12 = $signed(num0 / det_int);
                num0 = $signed(adj20) * 64'sd65536;
                inv20 = $signed(num0 / det_int);
                num0 = $signed(adj21) * 64'sd65536;
                inv21 = $signed(num0 / det_int);
                num0 = $signed(adj22) * 64'sd65536;
                inv22 = $signed(num0 / det_int);

                // Now compute X = invD * N  (matrix multiply Q16*Q16 -> Q32 >>16 -> Q16)
                // X00 = inv00*N00 + inv01*N10 + inv02*N20 >>16
                p0 = $signed(inv00) * $signed(N00);
                p1 = $signed(inv01) * $signed(N10);
                p2 = $signed(inv02) * $signed(N20);
                T00 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(inv00) * $signed(N01);
                p1 = $signed(inv01) * $signed(N11);
                p2 = $signed(inv02) * $signed(N21);
                T01 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(inv00) * $signed(N02);
                p1 = $signed(inv01) * $signed(N12);
                p2 = $signed(inv02) * $signed(N22);
                T02 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(inv10) * $signed(N00);
                p1 = $signed(inv11) * $signed(N10);
                p2 = $signed(inv12) * $signed(N20);
                T10 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(inv10) * $signed(N01);
                p1 = $signed(inv11) * $signed(N11);
                p2 = $signed(inv12) * $signed(N21);
                T11 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(inv10) * $signed(N02);
                p1 = $signed(inv11) * $signed(N12);
                p2 = $signed(inv12) * $signed(N22);
                T12 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(inv20) * $signed(N00);
                p1 = $signed(inv21) * $signed(N10);
                p2 = $signed(inv22) * $signed(N20);
                T20 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(inv20) * $signed(N01);
                p1 = $signed(inv21) * $signed(N11);
                p2 = $signed(inv22) * $signed(N21);
                T21 <= $signed((p0 + p1 + p2) >>> 16);

                p0 = $signed(inv20) * $signed(N02);
                p1 = $signed(inv21) * $signed(N12);
                p2 = $signed(inv22) * $signed(N22);
                T22 <= $signed((p0 + p1 + p2) >>> 16);

                // write to R (use R regs as e.g., R00..R22 = T00..T22)
                e00 <= T00; e01 <= T01; e02 <= T02;
                e10 <= T10; e11 <= T11; e12 <= T12;
                e20 <= T20; e21 <= T21; e22 <= T22;

                // set remaining squaring count
                state <= SQR;
            end
            SQR: begin
                if (s_remaining == 0) begin
                    // output R already in e00..e22
                    done <= 1'b1;
                    busy <= 1'b0;
                    state <= DONE;
                end else begin
                    // square R: R = R * R
                    p0 = $signed(e00) * $signed(e00);
                    p1 = $signed(e01) * $signed(e10);
                    p2 = $signed(e02) * $signed(e20);
                    T00 <= $signed((p0 + p1 + p2) >>> 16);

                    p0 = $signed(e00) * $signed(e01);
                    p1 = $signed(e01) * $signed(e11);
                    p2 = $signed(e02) * $signed(e21);
                    T01 <= $signed((p0 + p1 + p2) >>> 16);

                    p0 = $signed(e00) * $signed(e02);
                    p1 = $signed(e01) * $signed(e12);
                    p2 = $signed(e02) * $signed(e22);
                    T02 <= $signed((p0 + p1 + p2) >>> 16);

                    p0 = $signed(e10) * $signed(e00);
                    p1 = $signed(e11) * $signed(e10);
                    p2 = $signed(e12) * $signed(e20);
                    T10 <= $signed((p0 + p1 + p2) >>> 16);

                    p0 = $signed(e10) * $signed(e01);
                    p1 = $signed(e11) * $signed(e11);
                    p2 = $signed(e12) * $signed(e21);
                    T11 <= $signed((p0 + p1 + p2) >>> 16);

                    p0 = $signed(e10) * $signed(e02);
                    p1 = $signed(e11) * $signed(e12);
                    p2 = $signed(e12) * $signed(e22);
                    T12 <= $signed((p0 + p1 + p2) >>> 16);

                    p0 = $signed(e20) * $signed(e00);
                    p1 = $signed(e21) * $signed(e10);
                    p2 = $signed(e22) * $signed(e20);
                    T20 <= $signed((p0 + p1 + p2) >>> 16);

                    p0 = $signed(e20) * $signed(e01);
                    p1 = $signed(e21) * $signed(e11);
                    p2 = $signed(e22) * $signed(e21);
                    T21 <= $signed((p0 + p1 + p2) >>> 16);

                    p0 = $signed(e20) * $signed(e02);
                    p1 = $signed(e21) * $signed(e12);
                    p2 = $signed(e22) * $signed(e22);
                    T22 <= $signed((p0 + p1 + p2) >>> 16);

                    // write back
                    e00 <= T00; e01 <= T01; e02 <= T02;
                    e10 <= T10; e11 <= T11; e12 <= T12;
                    e20 <= T20; e21 <= T21; e22 <= T22;

                    s_remaining <= s_remaining - 1'b1;
                end
            end
            DONE: begin
                // clear done after one cycle
                done <= 1'b0;
                state <= IDLE;
            end
            default: state <= IDLE;
        endcase
    end
end

endmodule
