#ifndef SOVEREIGN_LUT_H
#define SOVEREIGN_LUT_H

/* Sovereign Geometry LUT — generated by lut_export.py */
/* Values are exact rational fractions: value = num/den */
/* CC0 1.0 Universal */

#include <stdint.h>

typedef struct { int16_t num; int16_t den; } spu_frac_t;

#define SPU_IVM_SPREAD_LUT_LEN 12

static const spu_frac_t spu_ivm_spread_lut[] = {
    {   0,   1 },  /* s(0°) = 0 */
    {   1,   4 },  /* s(30°) = 1/4 */
    {   3,   4 },  /* s(60°) = 3/4 */
    {   1,   1 },  /* s(90°) = 1 */
    {   3,   4 },  /* s(120°) = 3/4 */
    {   1,   4 },  /* s(150°) = 1/4 */
    {   0,   1 },  /* s(180°) = 0 */
    {   1,   4 },  /* s(210°) = 1/4 */
    {   3,   4 },  /* s(240°) = 3/4 */
    {   1,   1 },  /* s(270°) = 1 */
    {   3,   4 },  /* s(300°) = 3/4 */
    {   1,   4 },  /* s(330°) = 1/4 */
};

#endif /* SOVEREIGN_LUT_H */
