#!/usr/bin/env python3
"""
Coordinate Transformer (Master Script)
Maps tiling coordinates (Sierpinski carpet) to Gowin Tang-25k grid and emits .cst INS_LOC lines
and a CSV mapping for verification. This is the canonical, tunable transformer for floorplanning.

Usage:
  python3 coordinate_transformer.py --depth 3 --config gowin_tang25k_grid.json \
    --prefix u_spu26/node --output-cst example_master.cst --output-csv example_master_map.csv

Tune the device grid in the JSON config and adjust spacing/collision options as needed.
"""

import argparse
import json
import csv
import math
import os


def sierpinski_carpet(depth):
    coords = [(0.0, 0.0, 1.0)]
    for _ in range(depth):
        new = []
        for x, y, s in coords:
            s3 = s / 3.0
            for dx in range(3):
                for dy in range(3):
                    if dx == 1 and dy == 1:
                        continue
                    new.append((x + dx * s3, y + dy * s3, s3))
        coords = new
    return [(x + s / 2.0, y + s / 2.0) for x, y, s in coords]


def map_ivm_to_gowin(x, y, rows, cols, offset_row=0, offset_col=0):
    # Map normalized [0,1) x,y to integer row/col on device grid (simple linear mapping)
    row = int(offset_row + round(y * (rows - 1)))
    col = int(offset_col + round(x * (cols - 1)))
    row = max(0, min(rows - 1, row))
    col = max(0, min(cols - 1, col))
    return row, col


def find_nearest_free(row, col, occupied, rows, cols, max_radius=8):
    if (row, col) not in occupied:
        return row, col
    for r in range(1, max_radius + 1):
        # spiral search perimeter
        for dr in range(-r, r + 1):
            for dc in (-r, r):
                rr, cc = row + dr, col + dc
                if 0 <= rr < rows and 0 <= cc < cols and (rr, cc) not in occupied:
                    return rr, cc
        for dc in range(-r + 1, r):
            for dr in (-r, r):
                rr, cc = row + dr, col + dc
                if 0 <= rr < rows and 0 <= cc < cols and (rr, cc) not in occupied:
                    return rr, cc
    # fallback: return original (collision unresolved)
    return row, col


def load_config(path):
    if not path:
        return None
    with open(path, 'r') as f:
        return json.load(f)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--depth', type=int, default=3, help='Sierpinski recursion depth')
    p.add_argument('--config', type=str, default='gowin_tang25k_grid.json', help='Device grid JSON')
    p.add_argument('--rows', type=int, help='Override device rows')
    p.add_argument('--cols', type=int, help='Override device cols')
    p.add_argument('--offset-row', type=int, help='Override offset row')
    p.add_argument('--offset-col', type=int, help='Override offset col')
    p.add_argument('--prefix', type=str, default='u_spu26/node', help='Instance prefix')
    p.add_argument('--output-cst', type=str, default='example_master.cst', help='Output .cst path')
    p.add_argument('--output-csv', type=str, default='example_master_map.csv', help='Output CSV path')
    p.add_argument('--max-radius', type=int, default=8, help='Collision search radius')
    args = p.parse_args()

    cfg = load_config(args.config) or {}
    rows = args.rows or cfg.get('rows', 64)
    cols = args.cols or cfg.get('cols', 128)
    offset_row = args.offset_row if args.offset_row is not None else cfg.get('offset_row', 0)
    offset_col = args.offset_col if args.offset_col is not None else cfg.get('offset_col', 0)

    points = sierpinski_carpet(args.depth)
    occupied = set()
    mappings = []

    for i, (x, y) in enumerate(points):
        row, col = map_ivm_to_gowin(x, y, rows, cols, offset_row, offset_col)
        r2, c2 = find_nearest_free(row, col, occupied, rows, cols, args.max_radius)
        occupied.add((r2, c2))
        inst = f'{args.prefix}_{i}'
        mappings.append((inst, r2, c2, x, y))

    # Write .cst
    with open(args.output_cst, 'w') as f:
        f.write('// Generated by coordinate_transformer.py\n')
        for inst, r, c, x, y in mappings:
            f.write(f'INS_LOC "{inst}" R{r}C{c};\n')

    # Write CSV
    with open(args.output_csv, 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['instance', 'row', 'col', 'x', 'y'])
        for row in mappings:
            w.writerow(row)

    print(f'Wrote {len(mappings)} mappings to {args.output_cst} and {args.output_csv}.')


if __name__ == '__main__':
    main()
