#!/usr/bin/env python3
"""
generate_spu4_floorplan.py

Place a central SPU-4 Janus seed plus 12 neighbor seeds in a Vector-Equilibrium
ring and emit Gowin .cst INS_LOC lines and a CSV mapping for verification.

This script reuses coordinate_transformer.py mapping helpers (map_ivm_to_gowin,
find_nearest_free) located in the same directory.

Usage example:
  python3 generate_spu4_floorplan.py --config gowin_tang25k_grid.json \
      --radius 0.12 --prefix u_spu13/seed --output-cst spu13_spu4_ins.cst \
      --output-csv spu13_spu4_map.csv

"""

import argparse
import csv
import math
import os
import sys

# allow importing the sibling module coordinate_transformer.py
SCRIPT_DIR = os.path.dirname(__file__)
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

import coordinate_transformer as ct


def generate_vector_equilibrium_coords(cx=0.5, cy=0.5, radius=0.12, ring=12):
    """Return list of (x,y) coordinates: center followed by 'ring' points around."""
    pts = [(cx, cy)]
    for i in range(ring):
        theta = 2.0 * math.pi * i / float(ring)
        x = cx + radius * math.cos(theta)
        y = cy + radius * math.sin(theta)
        pts.append((x, y))
    return pts


def main():
    p = argparse.ArgumentParser(description='Generate SPU-4 Vector-Equilibrium floorplan .cst + CSV')
    p.add_argument('--config', type=str, default='gowin_tang25k_grid.json', help='Device grid JSON (sibling to this script)')
    p.add_argument('--rows', type=int, help='Override device rows')
    p.add_argument('--cols', type=int, help='Override device cols')
    p.add_argument('--offset-row', type=int, help='Offset row (device)')
    p.add_argument('--offset-col', type=int, help='Offset col (device)')
    p.add_argument('--cx', type=float, default=0.5, help='Normalized center x (0..1)')
    p.add_argument('--cy', type=float, default=0.5, help='Normalized center y (0..1)')
    p.add_argument('--radius', type=float, default=0.12, help='Normalized ring radius')
    p.add_argument('--ring', type=int, default=12, help='Number of neighbors around center (default 12 => SPU-13)')
    p.add_argument('--prefix', type=str, default='u_cortex_0.u_spu13.node', help='Instance name prefix')
    p.add_argument('--output-cst', type=str, default='spu13_spu4_ins.cst', help='Output .cst path')
    p.add_argument('--output-csv', type=str, default='spu13_spu4_map.csv', help='Output CSV path')
    p.add_argument('--max-radius', type=int, default=8, help='Collision search radius (cells)')
    args = p.parse_args()

    cfg = ct.load_config(args.config) or {}
    rows = args.rows or cfg.get('rows', 64)
    cols = args.cols or cfg.get('cols', 128)
    offset_row = args.offset_row if args.offset_row is not None else cfg.get('offset_row', 0)
    offset_col = args.offset_col if args.offset_col is not None else cfg.get('offset_col', 0)

    points = generate_vector_equilibrium_coords(cx=args.cx, cy=args.cy, radius=args.radius, ring=args.ring)

    occupied = set()
    mappings = []  # tuples of (inst, row, col, x, y)

    for i, (x, y) in enumerate(points):
        row, col = ct.map_ivm_to_gowin(x, y, rows, cols, offset_row, offset_col)
        r2, c2 = ct.find_nearest_free(row, col, occupied, rows, cols, args.max_radius)
        occupied.add((r2, c2))
        inst = f'{args.prefix}_{i}'
        mappings.append((inst, r2, c2, x, y))

    # write .cst
    with open(args.output_cst, 'w') as f:
        f.write('// Generated by generate_spu4_floorplan.py\n')
        for inst, r, c, x, y in mappings:
            f.write(f'INS_LOC "{inst}" R{r}C{c};\n')
        # Reserve BRAM for trimmed RPLU wrapper instance (use center mapping by default)
        try:
            bram_inst = f'{args.prefix}_rplu_bram'
        except Exception:
            bram_inst = args.prefix + '_rplu_bram'
        if mappings:
            r0, c0 = mappings[0][1], mappings[0][2]
            f.write(f'INS_LOC "{bram_inst}" R{r0}C{c0};\n')

    # write csv
    with open(args.output_csv, 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['instance', 'row', 'col', 'x', 'y'])
        for row in mappings:
            w.writerow(row)

    print(f'Wrote {len(mappings)} mappings to {args.output_cst} and {args.output_csv}.')


if __name__ == '__main__':
    main()
