// spu13_irotc_engine.v — Icosahedral A5 rotation engine (IROTC opcode)
//
// Copyright 2026 John Curley
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Term-serial coefficient-select datapath (docs/IROTC_SPEC.md §6, design
// decision 2026-07-10): the doubled numerator alphabet is only
// {0, ±1, ±2, ±phi, ±phi^-1, ±sqrt5}, each a single-cycle signed map on a
// Z[phi] pair, so one shared term unit + 9 accumulate cycles executes any
// of the 60 rotations — either catalog — in a FIXED 13-cycle slot:
//
//   cycle  0    : start accepted, guards, operand/index latch
//   cycles 1-9  : acc[row] += code(idx,row,col) * w[col]   (x0 burns the
//                 cycle — latency is uniform across all indices)
//   cycle 10    : acc >>>= 1 (unguarded — licensed by the DOUBLED
//                 typestate at dispatch; doubling theorem)
//   cycle 11    : A = -(B+C+D) zero-sum recompute
//   cycle 12    : done pulse, outputs + out_tag valid
//
// This is signed exact Z[phi] integer arithmetic — NOT the mod-L_p plane
// of spu13_lucas_mac.v. No multipliers, no DSPs: adders and muxes only.
//
// The conjugate catalog (sel[6], Galois phi -> 1-phi) is the code remap
// 5<->8, 6<->7, 9<->10 — no second ROM. Code ROM is GENERATED:
//   python3 software/tests/test_icosahedral_catalog.py --emit-rtl
// (catalog sha aabef37c9c8b0317; never hand-edit the .mem).
//
// Dispatch faults (all leave outputs bit-identically untouched):
//   FAULT_BADIDX   sel[5:0] > 59
//   FAULT_UNTAGGED src_tag == TAG_UNTAGGED
//   FAULT_CATMIX   src_tag locked to the other catalog (typestate v0.2)
module spu13_irotc_engine #(
    parameter W = 32
) (
    input  wire                 clk,
    input  wire                 rst_n,
    input  wire                 start,
    input  wire [6:0]           sel,        // [5:0] index, [6] conjugate
    input  wire [1:0]           src_tag,    // source register typestate
    input  wire signed [W-1:0]  in_b_a, in_b_b,
    input  wire signed [W-1:0]  in_c_a, in_c_b,
    input  wire signed [W-1:0]  in_d_a, in_d_b,
    output reg                  busy,
    output reg                  done,
    output reg                  fault,
    output reg  [1:0]           fault_code,
    output reg  [1:0]           out_tag,    // TAG_MAIN or TAG_CONJ on done
    output reg  signed [W-1:0]  out_a_a, out_a_b,
    output reg  signed [W-1:0]  out_b_a, out_b_b,
    output reg  signed [W-1:0]  out_c_a, out_c_b,
    output reg  signed [W-1:0]  out_d_a, out_d_b
);
    // φ-plane typestate encodings (IROTC_SPEC.md §3)
    localparam [1:0] TAG_UNTAGGED = 2'd0;
    localparam [1:0] TAG_FRESH    = 2'd1;
    localparam [1:0] TAG_MAIN     = 2'd2;
    localparam [1:0] TAG_CONJ     = 2'd3;

    localparam [1:0] FAULT_BADIDX   = 2'd1;
    localparam [1:0] FAULT_UNTAGGED = 2'd2;
    localparam [1:0] FAULT_CATMIX   = 2'd3;

    localparam [1:0] S_IDLE = 2'd0, S_ACC = 2'd1, S_SHIFT = 2'd2,
                     S_ZSUM = 2'd3;

    // ── code ROM (60x9 alphabet codes, catalog sha aabef37c9c8b0317) ─
    // Generated by test_icosahedral_catalog.py --emit-rtl; values are
    // bit-identical to the verified case-function table (oracle check 23
    // pins every entry against the derivation each suite run). Stored as
    // an initialized memory with a REGISTERED read so synthesis infers a
    // BSRAM instead of a wide-mux LUT forest — the mux packing of the
    // combinational form was the routing-congestion source on GW5A.
    // The registered read is hidden by address prefetch (see rom_addr):
    // the 13-cycle slot is unchanged and testbench-pinned.
    (* ram_style = "block", syn_ramstyle = "block_ram" *)
    reg [3:0] code_mem [0:539];
    initial begin
        code_mem[0] = 4'd3;
        code_mem[1] = 4'd0;
        code_mem[2] = 4'd0;
        code_mem[3] = 4'd0;
        code_mem[4] = 4'd3;
        code_mem[5] = 4'd0;
        code_mem[6] = 4'd0;
        code_mem[7] = 4'd0;
        code_mem[8] = 4'd3;
        code_mem[9] = 4'd4;
        code_mem[10] = 4'd4;
        code_mem[11] = 4'd4;
        code_mem[12] = 4'd0;
        code_mem[13] = 4'd0;
        code_mem[14] = 4'd3;
        code_mem[15] = 4'd0;
        code_mem[16] = 4'd3;
        code_mem[17] = 4'd0;
        code_mem[18] = 4'd4;
        code_mem[19] = 4'd0;
        code_mem[20] = 4'd0;
        code_mem[21] = 4'd5;
        code_mem[22] = 4'd9;
        code_mem[23] = 4'd7;
        code_mem[24] = 4'd8;
        code_mem[25] = 4'd6;
        code_mem[26] = 4'd10;
        code_mem[27] = 4'd4;
        code_mem[28] = 4'd0;
        code_mem[29] = 4'd0;
        code_mem[30] = 4'd8;
        code_mem[31] = 4'd6;
        code_mem[32] = 4'd10;
        code_mem[33] = 4'd1;
        code_mem[34] = 4'd8;
        code_mem[35] = 4'd5;
        code_mem[36] = 4'd4;
        code_mem[37] = 4'd0;
        code_mem[38] = 4'd0;
        code_mem[39] = 4'd1;
        code_mem[40] = 4'd8;
        code_mem[41] = 4'd5;
        code_mem[42] = 4'd5;
        code_mem[43] = 4'd9;
        code_mem[44] = 4'd7;
        code_mem[45] = 4'd2;
        code_mem[46] = 4'd7;
        code_mem[47] = 4'd6;
        code_mem[48] = 4'd7;
        code_mem[49] = 4'd6;
        code_mem[50] = 4'd2;
        code_mem[51] = 4'd6;
        code_mem[52] = 4'd2;
        code_mem[53] = 4'd7;
        code_mem[54] = 4'd7;
        code_mem[55] = 4'd6;
        code_mem[56] = 4'd2;
        code_mem[57] = 4'd6;
        code_mem[58] = 4'd2;
        code_mem[59] = 4'd7;
        code_mem[60] = 4'd2;
        code_mem[61] = 4'd7;
        code_mem[62] = 4'd6;
        code_mem[63] = 4'd7;
        code_mem[64] = 4'd5;
        code_mem[65] = 4'd9;
        code_mem[66] = 4'd0;
        code_mem[67] = 4'd4;
        code_mem[68] = 4'd0;
        code_mem[69] = 4'd5;
        code_mem[70] = 4'd1;
        code_mem[71] = 4'd8;
        code_mem[72] = 4'd9;
        code_mem[73] = 4'd7;
        code_mem[74] = 4'd5;
        code_mem[75] = 4'd6;
        code_mem[76] = 4'd10;
        code_mem[77] = 4'd8;
        code_mem[78] = 4'd0;
        code_mem[79] = 4'd0;
        code_mem[80] = 4'd4;
        code_mem[81] = 4'd6;
        code_mem[82] = 4'd2;
        code_mem[83] = 4'd7;
        code_mem[84] = 4'd2;
        code_mem[85] = 4'd7;
        code_mem[86] = 4'd6;
        code_mem[87] = 4'd7;
        code_mem[88] = 4'd6;
        code_mem[89] = 4'd2;
        code_mem[90] = 4'd6;
        code_mem[91] = 4'd10;
        code_mem[92] = 4'd8;
        code_mem[93] = 4'd8;
        code_mem[94] = 4'd5;
        code_mem[95] = 4'd1;
        code_mem[96] = 4'd0;
        code_mem[97] = 4'd0;
        code_mem[98] = 4'd4;
        code_mem[99] = 4'd0;
        code_mem[100] = 4'd0;
        code_mem[101] = 4'd3;
        code_mem[102] = 4'd4;
        code_mem[103] = 4'd4;
        code_mem[104] = 4'd4;
        code_mem[105] = 4'd3;
        code_mem[106] = 4'd0;
        code_mem[107] = 4'd0;
        code_mem[108] = 4'd0;
        code_mem[109] = 4'd3;
        code_mem[110] = 4'd0;
        code_mem[111] = 4'd3;
        code_mem[112] = 4'd0;
        code_mem[113] = 4'd0;
        code_mem[114] = 4'd4;
        code_mem[115] = 4'd4;
        code_mem[116] = 4'd4;
        code_mem[117] = 4'd5;
        code_mem[118] = 4'd1;
        code_mem[119] = 4'd8;
        code_mem[120] = 4'd0;
        code_mem[121] = 4'd4;
        code_mem[122] = 4'd0;
        code_mem[123] = 4'd10;
        code_mem[124] = 4'd8;
        code_mem[125] = 4'd6;
        code_mem[126] = 4'd10;
        code_mem[127] = 4'd8;
        code_mem[128] = 4'd6;
        code_mem[129] = 4'd0;
        code_mem[130] = 4'd4;
        code_mem[131] = 4'd0;
        code_mem[132] = 4'd7;
        code_mem[133] = 4'd5;
        code_mem[134] = 4'd9;
        code_mem[135] = 4'd8;
        code_mem[136] = 4'd5;
        code_mem[137] = 4'd1;
        code_mem[138] = 4'd9;
        code_mem[139] = 4'd7;
        code_mem[140] = 4'd5;
        code_mem[141] = 4'd0;
        code_mem[142] = 4'd0;
        code_mem[143] = 4'd4;
        code_mem[144] = 4'd4;
        code_mem[145] = 4'd4;
        code_mem[146] = 4'd4;
        code_mem[147] = 4'd0;
        code_mem[148] = 4'd3;
        code_mem[149] = 4'd0;
        code_mem[150] = 4'd3;
        code_mem[151] = 4'd0;
        code_mem[152] = 4'd0;
        code_mem[153] = 4'd4;
        code_mem[154] = 4'd4;
        code_mem[155] = 4'd4;
        code_mem[156] = 4'd3;
        code_mem[157] = 4'd0;
        code_mem[158] = 4'd0;
        code_mem[159] = 4'd0;
        code_mem[160] = 4'd0;
        code_mem[161] = 4'd3;
        code_mem[162] = 4'd2;
        code_mem[163] = 4'd7;
        code_mem[164] = 4'd6;
        code_mem[165] = 4'd6;
        code_mem[166] = 4'd2;
        code_mem[167] = 4'd7;
        code_mem[168] = 4'd3;
        code_mem[169] = 4'd3;
        code_mem[170] = 4'd3;
        code_mem[171] = 4'd2;
        code_mem[172] = 4'd7;
        code_mem[173] = 4'd6;
        code_mem[174] = 4'd3;
        code_mem[175] = 4'd3;
        code_mem[176] = 4'd3;
        code_mem[177] = 4'd7;
        code_mem[178] = 4'd6;
        code_mem[179] = 4'd2;
        code_mem[180] = 4'd7;
        code_mem[181] = 4'd5;
        code_mem[182] = 4'd9;
        code_mem[183] = 4'd5;
        code_mem[184] = 4'd1;
        code_mem[185] = 4'd8;
        code_mem[186] = 4'd10;
        code_mem[187] = 4'd8;
        code_mem[188] = 4'd6;
        code_mem[189] = 4'd7;
        code_mem[190] = 4'd5;
        code_mem[191] = 4'd9;
        code_mem[192] = 4'd10;
        code_mem[193] = 4'd8;
        code_mem[194] = 4'd6;
        code_mem[195] = 4'd0;
        code_mem[196] = 4'd4;
        code_mem[197] = 4'd0;
        code_mem[198] = 4'd6;
        code_mem[199] = 4'd10;
        code_mem[200] = 4'd8;
        code_mem[201] = 4'd9;
        code_mem[202] = 4'd7;
        code_mem[203] = 4'd5;
        code_mem[204] = 4'd8;
        code_mem[205] = 4'd5;
        code_mem[206] = 4'd1;
        code_mem[207] = 4'd6;
        code_mem[208] = 4'd10;
        code_mem[209] = 4'd8;
        code_mem[210] = 4'd0;
        code_mem[211] = 4'd0;
        code_mem[212] = 4'd4;
        code_mem[213] = 4'd9;
        code_mem[214] = 4'd7;
        code_mem[215] = 4'd5;
        code_mem[216] = 4'd0;
        code_mem[217] = 4'd4;
        code_mem[218] = 4'd0;
        code_mem[219] = 4'd7;
        code_mem[220] = 4'd5;
        code_mem[221] = 4'd9;
        code_mem[222] = 4'd10;
        code_mem[223] = 4'd8;
        code_mem[224] = 4'd6;
        code_mem[225] = 4'd0;
        code_mem[226] = 4'd0;
        code_mem[227] = 4'd4;
        code_mem[228] = 4'd9;
        code_mem[229] = 4'd7;
        code_mem[230] = 4'd5;
        code_mem[231] = 4'd6;
        code_mem[232] = 4'd10;
        code_mem[233] = 4'd8;
        code_mem[234] = 4'd0;
        code_mem[235] = 4'd0;
        code_mem[236] = 4'd3;
        code_mem[237] = 4'd0;
        code_mem[238] = 4'd3;
        code_mem[239] = 4'd0;
        code_mem[240] = 4'd4;
        code_mem[241] = 4'd4;
        code_mem[242] = 4'd4;
        code_mem[243] = 4'd0;
        code_mem[244] = 4'd0;
        code_mem[245] = 4'd3;
        code_mem[246] = 4'd3;
        code_mem[247] = 4'd0;
        code_mem[248] = 4'd0;
        code_mem[249] = 4'd0;
        code_mem[250] = 4'd3;
        code_mem[251] = 4'd0;
        code_mem[252] = 4'd0;
        code_mem[253] = 4'd3;
        code_mem[254] = 4'd0;
        code_mem[255] = 4'd4;
        code_mem[256] = 4'd4;
        code_mem[257] = 4'd4;
        code_mem[258] = 4'd0;
        code_mem[259] = 4'd0;
        code_mem[260] = 4'd3;
        code_mem[261] = 4'd0;
        code_mem[262] = 4'd3;
        code_mem[263] = 4'd0;
        code_mem[264] = 4'd0;
        code_mem[265] = 4'd0;
        code_mem[266] = 4'd3;
        code_mem[267] = 4'd3;
        code_mem[268] = 4'd0;
        code_mem[269] = 4'd0;
        code_mem[270] = 4'd5;
        code_mem[271] = 4'd9;
        code_mem[272] = 4'd7;
        code_mem[273] = 4'd8;
        code_mem[274] = 4'd6;
        code_mem[275] = 4'd10;
        code_mem[276] = 4'd4;
        code_mem[277] = 4'd0;
        code_mem[278] = 4'd0;
        code_mem[279] = 4'd8;
        code_mem[280] = 4'd6;
        code_mem[281] = 4'd10;
        code_mem[282] = 4'd4;
        code_mem[283] = 4'd0;
        code_mem[284] = 4'd0;
        code_mem[285] = 4'd5;
        code_mem[286] = 4'd9;
        code_mem[287] = 4'd7;
        code_mem[288] = 4'd1;
        code_mem[289] = 4'd8;
        code_mem[290] = 4'd5;
        code_mem[291] = 4'd8;
        code_mem[292] = 4'd6;
        code_mem[293] = 4'd10;
        code_mem[294] = 4'd5;
        code_mem[295] = 4'd9;
        code_mem[296] = 4'd7;
        code_mem[297] = 4'd3;
        code_mem[298] = 4'd0;
        code_mem[299] = 4'd0;
        code_mem[300] = 4'd4;
        code_mem[301] = 4'd4;
        code_mem[302] = 4'd4;
        code_mem[303] = 4'd0;
        code_mem[304] = 4'd3;
        code_mem[305] = 4'd0;
        code_mem[306] = 4'd3;
        code_mem[307] = 4'd0;
        code_mem[308] = 4'd0;
        code_mem[309] = 4'd0;
        code_mem[310] = 4'd0;
        code_mem[311] = 4'd3;
        code_mem[312] = 4'd4;
        code_mem[313] = 4'd4;
        code_mem[314] = 4'd4;
        code_mem[315] = 4'd3;
        code_mem[316] = 4'd3;
        code_mem[317] = 4'd3;
        code_mem[318] = 4'd6;
        code_mem[319] = 4'd2;
        code_mem[320] = 4'd7;
        code_mem[321] = 4'd7;
        code_mem[322] = 4'd6;
        code_mem[323] = 4'd2;
        code_mem[324] = 4'd7;
        code_mem[325] = 4'd6;
        code_mem[326] = 4'd2;
        code_mem[327] = 4'd2;
        code_mem[328] = 4'd7;
        code_mem[329] = 4'd6;
        code_mem[330] = 4'd3;
        code_mem[331] = 4'd3;
        code_mem[332] = 4'd3;
        code_mem[333] = 4'd7;
        code_mem[334] = 4'd6;
        code_mem[335] = 4'd2;
        code_mem[336] = 4'd3;
        code_mem[337] = 4'd3;
        code_mem[338] = 4'd3;
        code_mem[339] = 4'd6;
        code_mem[340] = 4'd2;
        code_mem[341] = 4'd7;
        code_mem[342] = 4'd9;
        code_mem[343] = 4'd7;
        code_mem[344] = 4'd5;
        code_mem[345] = 4'd0;
        code_mem[346] = 4'd0;
        code_mem[347] = 4'd4;
        code_mem[348] = 4'd8;
        code_mem[349] = 4'd5;
        code_mem[350] = 4'd1;
        code_mem[351] = 4'd9;
        code_mem[352] = 4'd7;
        code_mem[353] = 4'd5;
        code_mem[354] = 4'd8;
        code_mem[355] = 4'd5;
        code_mem[356] = 4'd1;
        code_mem[357] = 4'd6;
        code_mem[358] = 4'd10;
        code_mem[359] = 4'd8;
        code_mem[360] = 4'd6;
        code_mem[361] = 4'd2;
        code_mem[362] = 4'd7;
        code_mem[363] = 4'd7;
        code_mem[364] = 4'd6;
        code_mem[365] = 4'd2;
        code_mem[366] = 4'd3;
        code_mem[367] = 4'd3;
        code_mem[368] = 4'd3;
        code_mem[369] = 4'd6;
        code_mem[370] = 4'd2;
        code_mem[371] = 4'd7;
        code_mem[372] = 4'd3;
        code_mem[373] = 4'd3;
        code_mem[374] = 4'd3;
        code_mem[375] = 4'd2;
        code_mem[376] = 4'd7;
        code_mem[377] = 4'd6;
        code_mem[378] = 4'd0;
        code_mem[379] = 4'd4;
        code_mem[380] = 4'd0;
        code_mem[381] = 4'd5;
        code_mem[382] = 4'd1;
        code_mem[383] = 4'd8;
        code_mem[384] = 4'd7;
        code_mem[385] = 4'd5;
        code_mem[386] = 4'd9;
        code_mem[387] = 4'd0;
        code_mem[388] = 4'd4;
        code_mem[389] = 4'd0;
        code_mem[390] = 4'd10;
        code_mem[391] = 4'd8;
        code_mem[392] = 4'd6;
        code_mem[393] = 4'd5;
        code_mem[394] = 4'd1;
        code_mem[395] = 4'd8;
        code_mem[396] = 4'd0;
        code_mem[397] = 4'd0;
        code_mem[398] = 4'd4;
        code_mem[399] = 4'd6;
        code_mem[400] = 4'd10;
        code_mem[401] = 4'd8;
        code_mem[402] = 4'd8;
        code_mem[403] = 4'd5;
        code_mem[404] = 4'd1;
        code_mem[405] = 4'd0;
        code_mem[406] = 4'd0;
        code_mem[407] = 4'd4;
        code_mem[408] = 4'd8;
        code_mem[409] = 4'd5;
        code_mem[410] = 4'd1;
        code_mem[411] = 4'd9;
        code_mem[412] = 4'd7;
        code_mem[413] = 4'd5;
        code_mem[414] = 4'd5;
        code_mem[415] = 4'd9;
        code_mem[416] = 4'd7;
        code_mem[417] = 4'd4;
        code_mem[418] = 4'd0;
        code_mem[419] = 4'd0;
        code_mem[420] = 4'd1;
        code_mem[421] = 4'd8;
        code_mem[422] = 4'd5;
        code_mem[423] = 4'd5;
        code_mem[424] = 4'd9;
        code_mem[425] = 4'd7;
        code_mem[426] = 4'd1;
        code_mem[427] = 4'd8;
        code_mem[428] = 4'd5;
        code_mem[429] = 4'd8;
        code_mem[430] = 4'd6;
        code_mem[431] = 4'd10;
        code_mem[432] = 4'd5;
        code_mem[433] = 4'd1;
        code_mem[434] = 4'd8;
        code_mem[435] = 4'd7;
        code_mem[436] = 4'd5;
        code_mem[437] = 4'd9;
        code_mem[438] = 4'd0;
        code_mem[439] = 4'd4;
        code_mem[440] = 4'd0;
        code_mem[441] = 4'd5;
        code_mem[442] = 4'd1;
        code_mem[443] = 4'd8;
        code_mem[444] = 4'd10;
        code_mem[445] = 4'd8;
        code_mem[446] = 4'd6;
        code_mem[447] = 4'd7;
        code_mem[448] = 4'd5;
        code_mem[449] = 4'd9;
        code_mem[450] = 4'd10;
        code_mem[451] = 4'd8;
        code_mem[452] = 4'd6;
        code_mem[453] = 4'd7;
        code_mem[454] = 4'd5;
        code_mem[455] = 4'd9;
        code_mem[456] = 4'd5;
        code_mem[457] = 4'd1;
        code_mem[458] = 4'd8;
        code_mem[459] = 4'd10;
        code_mem[460] = 4'd8;
        code_mem[461] = 4'd6;
        code_mem[462] = 4'd5;
        code_mem[463] = 4'd1;
        code_mem[464] = 4'd8;
        code_mem[465] = 4'd0;
        code_mem[466] = 4'd4;
        code_mem[467] = 4'd0;
        code_mem[468] = 4'd8;
        code_mem[469] = 4'd6;
        code_mem[470] = 4'd10;
        code_mem[471] = 4'd5;
        code_mem[472] = 4'd9;
        code_mem[473] = 4'd7;
        code_mem[474] = 4'd1;
        code_mem[475] = 4'd8;
        code_mem[476] = 4'd5;
        code_mem[477] = 4'd8;
        code_mem[478] = 4'd6;
        code_mem[479] = 4'd10;
        code_mem[480] = 4'd1;
        code_mem[481] = 4'd8;
        code_mem[482] = 4'd5;
        code_mem[483] = 4'd4;
        code_mem[484] = 4'd0;
        code_mem[485] = 4'd0;
        code_mem[486] = 4'd8;
        code_mem[487] = 4'd5;
        code_mem[488] = 4'd1;
        code_mem[489] = 4'd6;
        code_mem[490] = 4'd10;
        code_mem[491] = 4'd8;
        code_mem[492] = 4'd9;
        code_mem[493] = 4'd7;
        code_mem[494] = 4'd5;
        code_mem[495] = 4'd8;
        code_mem[496] = 4'd5;
        code_mem[497] = 4'd1;
        code_mem[498] = 4'd0;
        code_mem[499] = 4'd0;
        code_mem[500] = 4'd4;
        code_mem[501] = 4'd6;
        code_mem[502] = 4'd10;
        code_mem[503] = 4'd8;
        code_mem[504] = 4'd1;
        code_mem[505] = 4'd8;
        code_mem[506] = 4'd5;
        code_mem[507] = 4'd4;
        code_mem[508] = 4'd0;
        code_mem[509] = 4'd0;
        code_mem[510] = 4'd8;
        code_mem[511] = 4'd6;
        code_mem[512] = 4'd10;
        code_mem[513] = 4'd1;
        code_mem[514] = 4'd8;
        code_mem[515] = 4'd5;
        code_mem[516] = 4'd5;
        code_mem[517] = 4'd9;
        code_mem[518] = 4'd7;
        code_mem[519] = 4'd4;
        code_mem[520] = 4'd0;
        code_mem[521] = 4'd0;
        code_mem[522] = 4'd3;
        code_mem[523] = 4'd3;
        code_mem[524] = 4'd3;
        code_mem[525] = 4'd2;
        code_mem[526] = 4'd7;
        code_mem[527] = 4'd6;
        code_mem[528] = 4'd6;
        code_mem[529] = 4'd2;
        code_mem[530] = 4'd7;
        code_mem[531] = 4'd3;
        code_mem[532] = 4'd3;
        code_mem[533] = 4'd3;
        code_mem[534] = 4'd7;
        code_mem[535] = 4'd6;
        code_mem[536] = 4'd2;
        code_mem[537] = 4'd2;
        code_mem[538] = 4'd7;
        code_mem[539] = 4'd6;
    end

    reg                 conj_r;
    reg [9:0]           addr;               // idx*9 + term counter
    reg [3:0]           term;               // 0..8 = row*3 + col
    reg signed [W-1:0]  w_a [0:2];          // latched source (B,C,D) pairs
    reg signed [W-1:0]  w_b [0:2];
    reg signed [W-1:0]  acc_a [0:2];        // output accumulators
    reg signed [W-1:0]  acc_b [0:2];
    reg [1:0]           state;

    // ── registered ROM read with address prefetch ────────────────────
    // The BSRAM read is registered (1-cycle latency); the prefetch hides
    // it: on the accepted start cycle we present the base address so
    // code_raw holds code[0] during the first S_ACC cycle, and during
    // S_ACC term k we present addr+1 so code_raw holds code[k] while the
    // NEXT entry is being fetched. The engine's 13-cycle slot is
    // unchanged (testbench-pinned at exactly 12 clocks start→done).
    // The final prefetch (base+9) may read past the last entry of the
    // current rotation — that value lands during S_SHIFT and is unused.
    wire [9:0] rom_base = {1'b0, sel[5:0], 3'b000} + {4'b0, sel[5:0]};
    wire [9:0] rom_addr = (state == S_IDLE) ? rom_base : (addr + 10'd1);
    reg  [3:0] code_raw;
    always @(posedge clk) code_raw <= code_mem[rom_addr];
    wire [3:0] code = !conj_r        ? code_raw :
                      (code_raw == 4'd5)  ? 4'd8 :
                      (code_raw == 4'd8)  ? 4'd5 :
                      (code_raw == 4'd6)  ? 4'd7 :
                      (code_raw == 4'd7)  ? 4'd6 :
                      (code_raw == 4'd9)  ? 4'd10 :
                      (code_raw == 4'd10) ? 4'd9 : code_raw;

    wire [1:0] col = (term == 4'd0 || term == 4'd3 || term == 4'd6) ? 2'd0 :
                     (term == 4'd1 || term == 4'd4 || term == 4'd7) ? 2'd1 :
                                                                      2'd2;
    wire [1:0] row = (term < 4'd3) ? 2'd0 : (term < 4'd6) ? 2'd1 : 2'd2;

    wire signed [W-1:0] wa = w_a[col];
    wire signed [W-1:0] wb = w_b[col];

    // code * (wa + wb*phi) in Z[phi] — adders and negates only
    reg signed [W-1:0] term_a, term_b;
    always @* begin
        case (code)
            4'd1:    begin term_a =  wa;           term_b =  wb;           end
            4'd2:    begin term_a = -wa;           term_b = -wb;           end
            4'd3:    begin term_a =  wa + wa;      term_b =  wb + wb;      end
            4'd4:    begin term_a = -(wa + wa);    term_b = -(wb + wb);    end
            4'd5:    begin term_a =  wb;           term_b =  wa + wb;      end
            4'd6:    begin term_a = -wb;           term_b = -(wa + wb);    end
            4'd7:    begin term_a =  wb - wa;      term_b =  wa;           end
            4'd8:    begin term_a =  wa - wb;      term_b = -wa;           end
            4'd9:    begin term_a =  wb + wb - wa; term_b =  wa + wa + wb; end
            4'd10:   begin term_a =  wa - wb - wb; term_b = -(wa + wa + wb); end
            default: begin term_a = {W{1'b0}};     term_b = {W{1'b0}};     end
        endcase
    end

    // ── dispatch guards (decode order: BADIDX, UNTAGGED, CATMIX) ───
    wire       bad_idx  = (sel[5:0] > 6'd59);
    wire       untagged = (src_tag == TAG_UNTAGGED);
    wire       catmix   = (src_tag == TAG_MAIN &&  sel[6]) ||
                          (src_tag == TAG_CONJ && !sel[6]);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state <= S_IDLE; busy <= 0; done <= 0;
            fault <= 0; fault_code <= 0; out_tag <= TAG_UNTAGGED;
            conj_r <= 0; addr <= 0; term <= 0;
            w_a[0] <= 0; w_a[1] <= 0; w_a[2] <= 0;
            w_b[0] <= 0; w_b[1] <= 0; w_b[2] <= 0;
            acc_a[0] <= 0; acc_a[1] <= 0; acc_a[2] <= 0;
            acc_b[0] <= 0; acc_b[1] <= 0; acc_b[2] <= 0;
            out_a_a <= 0; out_a_b <= 0; out_b_a <= 0; out_b_b <= 0;
            out_c_a <= 0; out_c_b <= 0; out_d_a <= 0; out_d_b <= 0;
        end else begin
            done <= 0; fault <= 0;
            case (state)
                S_IDLE: if (start) begin
                    if (bad_idx) begin
                        fault <= 1; fault_code <= FAULT_BADIDX;
                    end else if (untagged) begin
                        fault <= 1; fault_code <= FAULT_UNTAGGED;
                    end else if (catmix) begin
                        fault <= 1; fault_code <= FAULT_CATMIX;
                    end else begin
                        conj_r <= sel[6];
                        // idx*9 = idx*8 + idx
                        addr   <= {1'b0, sel[5:0], 3'b000} + {4'b0, sel[5:0]};
                        term   <= 0;
                        w_a[0] <= in_b_a; w_b[0] <= in_b_b;
                        w_a[1] <= in_c_a; w_b[1] <= in_c_b;
                        w_a[2] <= in_d_a; w_b[2] <= in_d_b;
                        acc_a[0] <= 0; acc_a[1] <= 0; acc_a[2] <= 0;
                        acc_b[0] <= 0; acc_b[1] <= 0; acc_b[2] <= 0;
                        busy <= 1; state <= S_ACC;
                    end
                end

                S_ACC: begin
                    acc_a[row] <= acc_a[row] + term_a;
                    acc_b[row] <= acc_b[row] + term_b;
                    if (term == 4'd8) state <= S_SHIFT;
                    else begin term <= term + 4'd1; addr <= addr + 10'd1; end
                end

                S_SHIFT: begin
                    // Unguarded >>>1: licensed by the typestate at dispatch
                    // (doubling theorem — pre-shift sums are even for every
                    // legally tagged input; no divisibility check here).
                    acc_a[0] <= acc_a[0] >>> 1; acc_b[0] <= acc_b[0] >>> 1;
                    acc_a[1] <= acc_a[1] >>> 1; acc_b[1] <= acc_b[1] >>> 1;
                    acc_a[2] <= acc_a[2] >>> 1; acc_b[2] <= acc_b[2] >>> 1;
                    state <= S_ZSUM;
                end

                S_ZSUM: begin
                    out_b_a <= acc_a[0]; out_b_b <= acc_b[0];
                    out_c_a <= acc_a[1]; out_c_b <= acc_b[1];
                    out_d_a <= acc_a[2]; out_d_b <= acc_b[2];
                    out_a_a <= -(acc_a[0] + acc_a[1] + acc_a[2]);
                    out_a_b <= -(acc_b[0] + acc_b[1] + acc_b[2]);
                    out_tag <= conj_r ? TAG_CONJ : TAG_MAIN;
                    done <= 1; busy <= 0; state <= S_IDLE;
                end
            endcase
        end
    end
endmodule
