// spu13_irotc_engine.v — Icosahedral A5 rotation engine (IROTC opcode)
//
// Copyright 2026 John Curley
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Term-serial coefficient-select datapath (docs/IROTC_SPEC.md §6, design
// decision 2026-07-10): the doubled numerator alphabet is only
// {0, ±1, ±2, ±phi, ±phi^-1, ±sqrt5}, each a single-cycle signed map on a
// Z[phi] pair, so one shared term unit + 9 accumulate cycles executes any
// of the 60 rotations — either catalog — in a FIXED 13-cycle slot:
//
//   cycle  0    : start accepted, guards, operand/index latch
//   cycles 1-9  : acc[row] += code(idx,row,col) * w[col]   (x0 burns the
//                 cycle — latency is uniform across all indices)
//   cycle 10    : acc >>>= 1 (unguarded — licensed by the DOUBLED
//                 typestate at dispatch; doubling theorem)
//   cycle 11    : A = -(B+C+D) zero-sum recompute
//   cycle 12    : done pulse, outputs + out_tag valid
//
// This is signed exact Z[phi] integer arithmetic — NOT the mod-L_p plane
// of spu13_lucas_mac.v. No multipliers, no DSPs: adders and muxes only.
//
// The conjugate catalog (sel[6], Galois phi -> 1-phi) is the code remap
// 5<->8, 6<->7, 9<->10 — no second ROM. Code ROM is GENERATED:
//   python3 software/tests/test_icosahedral_catalog.py --emit-rtl
// (catalog sha aabef37c9c8b0317; never hand-edit the .mem).
//
// Dispatch faults (all leave outputs bit-identically untouched):
//   FAULT_BADIDX   sel[5:0] > 59
//   FAULT_UNTAGGED src_tag == TAG_UNTAGGED
//   FAULT_CATMIX   src_tag locked to the other catalog (typestate v0.2)
module spu13_irotc_engine #(
    parameter W = 32
) (
    input  wire                 clk,
    input  wire                 rst_n,
    input  wire                 start,
    input  wire [6:0]           sel,        // [5:0] index, [6] conjugate
    input  wire [1:0]           src_tag,    // source register typestate
    input  wire signed [W-1:0]  in_b_a, in_b_b,
    input  wire signed [W-1:0]  in_c_a, in_c_b,
    input  wire signed [W-1:0]  in_d_a, in_d_b,
    output reg                  busy,
    output reg                  done,
    output reg                  fault,
    output reg  [1:0]           fault_code,
    output reg  [1:0]           out_tag,    // TAG_MAIN or TAG_CONJ on done
    output reg  signed [W-1:0]  out_a_a, out_a_b,
    output reg  signed [W-1:0]  out_b_a, out_b_b,
    output reg  signed [W-1:0]  out_c_a, out_c_b,
    output reg  signed [W-1:0]  out_d_a, out_d_b
);
    // φ-plane typestate encodings (IROTC_SPEC.md §3)
    localparam [1:0] TAG_UNTAGGED = 2'd0;
    localparam [1:0] TAG_FRESH    = 2'd1;
    localparam [1:0] TAG_MAIN     = 2'd2;
    localparam [1:0] TAG_CONJ     = 2'd3;

    localparam [1:0] FAULT_BADIDX   = 2'd1;
    localparam [1:0] FAULT_UNTAGGED = 2'd2;
    localparam [1:0] FAULT_CATMIX   = 2'd3;

    localparam [1:0] S_IDLE = 2'd0, S_ACC = 2'd1, S_SHIFT = 2'd2,
                     S_ZSUM = 2'd3;

    // ── code ROM (60x9 alphabet codes, catalog sha aabef37c9c8b0317) ─
    // Generated by test_icosahedral_catalog.py --emit-rtl; hardcoded
    // for synthesis portability (yosys $readmemh path resolution is
    // fragile across tool versions).
    function [3:0] code_lookup;
        input [9:0] a;
        begin
            case (a)
                10'd0: code_lookup = 4'd3;
                10'd1: code_lookup = 4'd0;
                10'd2: code_lookup = 4'd0;
                10'd3: code_lookup = 4'd0;
                10'd4: code_lookup = 4'd3;
                10'd5: code_lookup = 4'd0;
                10'd6: code_lookup = 4'd0;
                10'd7: code_lookup = 4'd0;
                10'd8: code_lookup = 4'd3;
                10'd9: code_lookup = 4'd4;
                10'd10: code_lookup = 4'd4;
                10'd11: code_lookup = 4'd4;
                10'd12: code_lookup = 4'd0;
                10'd13: code_lookup = 4'd0;
                10'd14: code_lookup = 4'd3;
                10'd15: code_lookup = 4'd0;
                10'd16: code_lookup = 4'd3;
                10'd17: code_lookup = 4'd0;
                10'd18: code_lookup = 4'd4;
                10'd19: code_lookup = 4'd0;
                10'd20: code_lookup = 4'd0;
                10'd21: code_lookup = 4'd5;
                10'd22: code_lookup = 4'd9;
                10'd23: code_lookup = 4'd7;
                10'd24: code_lookup = 4'd8;
                10'd25: code_lookup = 4'd6;
                10'd26: code_lookup = 4'd10;
                10'd27: code_lookup = 4'd4;
                10'd28: code_lookup = 4'd0;
                10'd29: code_lookup = 4'd0;
                10'd30: code_lookup = 4'd8;
                10'd31: code_lookup = 4'd6;
                10'd32: code_lookup = 4'd10;
                10'd33: code_lookup = 4'd1;
                10'd34: code_lookup = 4'd8;
                10'd35: code_lookup = 4'd5;
                10'd36: code_lookup = 4'd4;
                10'd37: code_lookup = 4'd0;
                10'd38: code_lookup = 4'd0;
                10'd39: code_lookup = 4'd1;
                10'd40: code_lookup = 4'd8;
                10'd41: code_lookup = 4'd5;
                10'd42: code_lookup = 4'd5;
                10'd43: code_lookup = 4'd9;
                10'd44: code_lookup = 4'd7;
                10'd45: code_lookup = 4'd2;
                10'd46: code_lookup = 4'd7;
                10'd47: code_lookup = 4'd6;
                10'd48: code_lookup = 4'd7;
                10'd49: code_lookup = 4'd6;
                10'd50: code_lookup = 4'd2;
                10'd51: code_lookup = 4'd6;
                10'd52: code_lookup = 4'd2;
                10'd53: code_lookup = 4'd7;
                10'd54: code_lookup = 4'd7;
                10'd55: code_lookup = 4'd6;
                10'd56: code_lookup = 4'd2;
                10'd57: code_lookup = 4'd6;
                10'd58: code_lookup = 4'd2;
                10'd59: code_lookup = 4'd7;
                10'd60: code_lookup = 4'd2;
                10'd61: code_lookup = 4'd7;
                10'd62: code_lookup = 4'd6;
                10'd63: code_lookup = 4'd7;
                10'd64: code_lookup = 4'd5;
                10'd65: code_lookup = 4'd9;
                10'd66: code_lookup = 4'd0;
                10'd67: code_lookup = 4'd4;
                10'd68: code_lookup = 4'd0;
                10'd69: code_lookup = 4'd5;
                10'd70: code_lookup = 4'd1;
                10'd71: code_lookup = 4'd8;
                10'd72: code_lookup = 4'd9;
                10'd73: code_lookup = 4'd7;
                10'd74: code_lookup = 4'd5;
                10'd75: code_lookup = 4'd6;
                10'd76: code_lookup = 4'd10;
                10'd77: code_lookup = 4'd8;
                10'd78: code_lookup = 4'd0;
                10'd79: code_lookup = 4'd0;
                10'd80: code_lookup = 4'd4;
                10'd81: code_lookup = 4'd6;
                10'd82: code_lookup = 4'd2;
                10'd83: code_lookup = 4'd7;
                10'd84: code_lookup = 4'd2;
                10'd85: code_lookup = 4'd7;
                10'd86: code_lookup = 4'd6;
                10'd87: code_lookup = 4'd7;
                10'd88: code_lookup = 4'd6;
                10'd89: code_lookup = 4'd2;
                10'd90: code_lookup = 4'd6;
                10'd91: code_lookup = 4'd10;
                10'd92: code_lookup = 4'd8;
                10'd93: code_lookup = 4'd8;
                10'd94: code_lookup = 4'd5;
                10'd95: code_lookup = 4'd1;
                10'd96: code_lookup = 4'd0;
                10'd97: code_lookup = 4'd0;
                10'd98: code_lookup = 4'd4;
                10'd99: code_lookup = 4'd0;
                10'd100: code_lookup = 4'd0;
                10'd101: code_lookup = 4'd3;
                10'd102: code_lookup = 4'd4;
                10'd103: code_lookup = 4'd4;
                10'd104: code_lookup = 4'd4;
                10'd105: code_lookup = 4'd3;
                10'd106: code_lookup = 4'd0;
                10'd107: code_lookup = 4'd0;
                10'd108: code_lookup = 4'd0;
                10'd109: code_lookup = 4'd3;
                10'd110: code_lookup = 4'd0;
                10'd111: code_lookup = 4'd3;
                10'd112: code_lookup = 4'd0;
                10'd113: code_lookup = 4'd0;
                10'd114: code_lookup = 4'd4;
                10'd115: code_lookup = 4'd4;
                10'd116: code_lookup = 4'd4;
                10'd117: code_lookup = 4'd5;
                10'd118: code_lookup = 4'd1;
                10'd119: code_lookup = 4'd8;
                10'd120: code_lookup = 4'd0;
                10'd121: code_lookup = 4'd4;
                10'd122: code_lookup = 4'd0;
                10'd123: code_lookup = 4'd10;
                10'd124: code_lookup = 4'd8;
                10'd125: code_lookup = 4'd6;
                10'd126: code_lookup = 4'd10;
                10'd127: code_lookup = 4'd8;
                10'd128: code_lookup = 4'd6;
                10'd129: code_lookup = 4'd0;
                10'd130: code_lookup = 4'd4;
                10'd131: code_lookup = 4'd0;
                10'd132: code_lookup = 4'd7;
                10'd133: code_lookup = 4'd5;
                10'd134: code_lookup = 4'd9;
                10'd135: code_lookup = 4'd8;
                10'd136: code_lookup = 4'd5;
                10'd137: code_lookup = 4'd1;
                10'd138: code_lookup = 4'd9;
                10'd139: code_lookup = 4'd7;
                10'd140: code_lookup = 4'd5;
                10'd141: code_lookup = 4'd0;
                10'd142: code_lookup = 4'd0;
                10'd143: code_lookup = 4'd4;
                10'd144: code_lookup = 4'd4;
                10'd145: code_lookup = 4'd4;
                10'd146: code_lookup = 4'd4;
                10'd147: code_lookup = 4'd0;
                10'd148: code_lookup = 4'd3;
                10'd149: code_lookup = 4'd0;
                10'd150: code_lookup = 4'd3;
                10'd151: code_lookup = 4'd0;
                10'd152: code_lookup = 4'd0;
                10'd153: code_lookup = 4'd4;
                10'd154: code_lookup = 4'd4;
                10'd155: code_lookup = 4'd4;
                10'd156: code_lookup = 4'd3;
                10'd157: code_lookup = 4'd0;
                10'd158: code_lookup = 4'd0;
                10'd159: code_lookup = 4'd0;
                10'd160: code_lookup = 4'd0;
                10'd161: code_lookup = 4'd3;
                10'd162: code_lookup = 4'd2;
                10'd163: code_lookup = 4'd7;
                10'd164: code_lookup = 4'd6;
                10'd165: code_lookup = 4'd6;
                10'd166: code_lookup = 4'd2;
                10'd167: code_lookup = 4'd7;
                10'd168: code_lookup = 4'd3;
                10'd169: code_lookup = 4'd3;
                10'd170: code_lookup = 4'd3;
                10'd171: code_lookup = 4'd2;
                10'd172: code_lookup = 4'd7;
                10'd173: code_lookup = 4'd6;
                10'd174: code_lookup = 4'd3;
                10'd175: code_lookup = 4'd3;
                10'd176: code_lookup = 4'd3;
                10'd177: code_lookup = 4'd7;
                10'd178: code_lookup = 4'd6;
                10'd179: code_lookup = 4'd2;
                10'd180: code_lookup = 4'd7;
                10'd181: code_lookup = 4'd5;
                10'd182: code_lookup = 4'd9;
                10'd183: code_lookup = 4'd5;
                10'd184: code_lookup = 4'd1;
                10'd185: code_lookup = 4'd8;
                10'd186: code_lookup = 4'd10;
                10'd187: code_lookup = 4'd8;
                10'd188: code_lookup = 4'd6;
                10'd189: code_lookup = 4'd7;
                10'd190: code_lookup = 4'd5;
                10'd191: code_lookup = 4'd9;
                10'd192: code_lookup = 4'd10;
                10'd193: code_lookup = 4'd8;
                10'd194: code_lookup = 4'd6;
                10'd195: code_lookup = 4'd0;
                10'd196: code_lookup = 4'd4;
                10'd197: code_lookup = 4'd0;
                10'd198: code_lookup = 4'd6;
                10'd199: code_lookup = 4'd10;
                10'd200: code_lookup = 4'd8;
                10'd201: code_lookup = 4'd9;
                10'd202: code_lookup = 4'd7;
                10'd203: code_lookup = 4'd5;
                10'd204: code_lookup = 4'd8;
                10'd205: code_lookup = 4'd5;
                10'd206: code_lookup = 4'd1;
                10'd207: code_lookup = 4'd6;
                10'd208: code_lookup = 4'd10;
                10'd209: code_lookup = 4'd8;
                10'd210: code_lookup = 4'd0;
                10'd211: code_lookup = 4'd0;
                10'd212: code_lookup = 4'd4;
                10'd213: code_lookup = 4'd9;
                10'd214: code_lookup = 4'd7;
                10'd215: code_lookup = 4'd5;
                10'd216: code_lookup = 4'd0;
                10'd217: code_lookup = 4'd4;
                10'd218: code_lookup = 4'd0;
                10'd219: code_lookup = 4'd7;
                10'd220: code_lookup = 4'd5;
                10'd221: code_lookup = 4'd9;
                10'd222: code_lookup = 4'd10;
                10'd223: code_lookup = 4'd8;
                10'd224: code_lookup = 4'd6;
                10'd225: code_lookup = 4'd0;
                10'd226: code_lookup = 4'd0;
                10'd227: code_lookup = 4'd4;
                10'd228: code_lookup = 4'd9;
                10'd229: code_lookup = 4'd7;
                10'd230: code_lookup = 4'd5;
                10'd231: code_lookup = 4'd6;
                10'd232: code_lookup = 4'd10;
                10'd233: code_lookup = 4'd8;
                10'd234: code_lookup = 4'd0;
                10'd235: code_lookup = 4'd0;
                10'd236: code_lookup = 4'd3;
                10'd237: code_lookup = 4'd0;
                10'd238: code_lookup = 4'd3;
                10'd239: code_lookup = 4'd0;
                10'd240: code_lookup = 4'd4;
                10'd241: code_lookup = 4'd4;
                10'd242: code_lookup = 4'd4;
                10'd243: code_lookup = 4'd0;
                10'd244: code_lookup = 4'd0;
                10'd245: code_lookup = 4'd3;
                10'd246: code_lookup = 4'd3;
                10'd247: code_lookup = 4'd0;
                10'd248: code_lookup = 4'd0;
                10'd249: code_lookup = 4'd0;
                10'd250: code_lookup = 4'd3;
                10'd251: code_lookup = 4'd0;
                10'd252: code_lookup = 4'd0;
                10'd253: code_lookup = 4'd3;
                10'd254: code_lookup = 4'd0;
                10'd255: code_lookup = 4'd4;
                10'd256: code_lookup = 4'd4;
                10'd257: code_lookup = 4'd4;
                10'd258: code_lookup = 4'd0;
                10'd259: code_lookup = 4'd0;
                10'd260: code_lookup = 4'd3;
                10'd261: code_lookup = 4'd0;
                10'd262: code_lookup = 4'd3;
                10'd263: code_lookup = 4'd0;
                10'd264: code_lookup = 4'd0;
                10'd265: code_lookup = 4'd0;
                10'd266: code_lookup = 4'd3;
                10'd267: code_lookup = 4'd3;
                10'd268: code_lookup = 4'd0;
                10'd269: code_lookup = 4'd0;
                10'd270: code_lookup = 4'd5;
                10'd271: code_lookup = 4'd9;
                10'd272: code_lookup = 4'd7;
                10'd273: code_lookup = 4'd8;
                10'd274: code_lookup = 4'd6;
                10'd275: code_lookup = 4'd10;
                10'd276: code_lookup = 4'd4;
                10'd277: code_lookup = 4'd0;
                10'd278: code_lookup = 4'd0;
                10'd279: code_lookup = 4'd8;
                10'd280: code_lookup = 4'd6;
                10'd281: code_lookup = 4'd10;
                10'd282: code_lookup = 4'd4;
                10'd283: code_lookup = 4'd0;
                10'd284: code_lookup = 4'd0;
                10'd285: code_lookup = 4'd5;
                10'd286: code_lookup = 4'd9;
                10'd287: code_lookup = 4'd7;
                10'd288: code_lookup = 4'd1;
                10'd289: code_lookup = 4'd8;
                10'd290: code_lookup = 4'd5;
                10'd291: code_lookup = 4'd8;
                10'd292: code_lookup = 4'd6;
                10'd293: code_lookup = 4'd10;
                10'd294: code_lookup = 4'd5;
                10'd295: code_lookup = 4'd9;
                10'd296: code_lookup = 4'd7;
                10'd297: code_lookup = 4'd3;
                10'd298: code_lookup = 4'd0;
                10'd299: code_lookup = 4'd0;
                10'd300: code_lookup = 4'd4;
                10'd301: code_lookup = 4'd4;
                10'd302: code_lookup = 4'd4;
                10'd303: code_lookup = 4'd0;
                10'd304: code_lookup = 4'd3;
                10'd305: code_lookup = 4'd0;
                10'd306: code_lookup = 4'd3;
                10'd307: code_lookup = 4'd0;
                10'd308: code_lookup = 4'd0;
                10'd309: code_lookup = 4'd0;
                10'd310: code_lookup = 4'd0;
                10'd311: code_lookup = 4'd3;
                10'd312: code_lookup = 4'd4;
                10'd313: code_lookup = 4'd4;
                10'd314: code_lookup = 4'd4;
                10'd315: code_lookup = 4'd3;
                10'd316: code_lookup = 4'd3;
                10'd317: code_lookup = 4'd3;
                10'd318: code_lookup = 4'd6;
                10'd319: code_lookup = 4'd2;
                10'd320: code_lookup = 4'd7;
                10'd321: code_lookup = 4'd7;
                10'd322: code_lookup = 4'd6;
                10'd323: code_lookup = 4'd2;
                10'd324: code_lookup = 4'd7;
                10'd325: code_lookup = 4'd6;
                10'd326: code_lookup = 4'd2;
                10'd327: code_lookup = 4'd2;
                10'd328: code_lookup = 4'd7;
                10'd329: code_lookup = 4'd6;
                10'd330: code_lookup = 4'd3;
                10'd331: code_lookup = 4'd3;
                10'd332: code_lookup = 4'd3;
                10'd333: code_lookup = 4'd7;
                10'd334: code_lookup = 4'd6;
                10'd335: code_lookup = 4'd2;
                10'd336: code_lookup = 4'd3;
                10'd337: code_lookup = 4'd3;
                10'd338: code_lookup = 4'd3;
                10'd339: code_lookup = 4'd6;
                10'd340: code_lookup = 4'd2;
                10'd341: code_lookup = 4'd7;
                10'd342: code_lookup = 4'd9;
                10'd343: code_lookup = 4'd7;
                10'd344: code_lookup = 4'd5;
                10'd345: code_lookup = 4'd0;
                10'd346: code_lookup = 4'd0;
                10'd347: code_lookup = 4'd4;
                10'd348: code_lookup = 4'd8;
                10'd349: code_lookup = 4'd5;
                10'd350: code_lookup = 4'd1;
                10'd351: code_lookup = 4'd9;
                10'd352: code_lookup = 4'd7;
                10'd353: code_lookup = 4'd5;
                10'd354: code_lookup = 4'd8;
                10'd355: code_lookup = 4'd5;
                10'd356: code_lookup = 4'd1;
                10'd357: code_lookup = 4'd6;
                10'd358: code_lookup = 4'd10;
                10'd359: code_lookup = 4'd8;
                10'd360: code_lookup = 4'd6;
                10'd361: code_lookup = 4'd2;
                10'd362: code_lookup = 4'd7;
                10'd363: code_lookup = 4'd7;
                10'd364: code_lookup = 4'd6;
                10'd365: code_lookup = 4'd2;
                10'd366: code_lookup = 4'd3;
                10'd367: code_lookup = 4'd3;
                10'd368: code_lookup = 4'd3;
                10'd369: code_lookup = 4'd6;
                10'd370: code_lookup = 4'd2;
                10'd371: code_lookup = 4'd7;
                10'd372: code_lookup = 4'd3;
                10'd373: code_lookup = 4'd3;
                10'd374: code_lookup = 4'd3;
                10'd375: code_lookup = 4'd2;
                10'd376: code_lookup = 4'd7;
                10'd377: code_lookup = 4'd6;
                10'd378: code_lookup = 4'd0;
                10'd379: code_lookup = 4'd4;
                10'd380: code_lookup = 4'd0;
                10'd381: code_lookup = 4'd5;
                10'd382: code_lookup = 4'd1;
                10'd383: code_lookup = 4'd8;
                10'd384: code_lookup = 4'd7;
                10'd385: code_lookup = 4'd5;
                10'd386: code_lookup = 4'd9;
                10'd387: code_lookup = 4'd0;
                10'd388: code_lookup = 4'd4;
                10'd389: code_lookup = 4'd0;
                10'd390: code_lookup = 4'd10;
                10'd391: code_lookup = 4'd8;
                10'd392: code_lookup = 4'd6;
                10'd393: code_lookup = 4'd5;
                10'd394: code_lookup = 4'd1;
                10'd395: code_lookup = 4'd8;
                10'd396: code_lookup = 4'd0;
                10'd397: code_lookup = 4'd0;
                10'd398: code_lookup = 4'd4;
                10'd399: code_lookup = 4'd6;
                10'd400: code_lookup = 4'd10;
                10'd401: code_lookup = 4'd8;
                10'd402: code_lookup = 4'd8;
                10'd403: code_lookup = 4'd5;
                10'd404: code_lookup = 4'd1;
                10'd405: code_lookup = 4'd0;
                10'd406: code_lookup = 4'd0;
                10'd407: code_lookup = 4'd4;
                10'd408: code_lookup = 4'd8;
                10'd409: code_lookup = 4'd5;
                10'd410: code_lookup = 4'd1;
                10'd411: code_lookup = 4'd9;
                10'd412: code_lookup = 4'd7;
                10'd413: code_lookup = 4'd5;
                10'd414: code_lookup = 4'd5;
                10'd415: code_lookup = 4'd9;
                10'd416: code_lookup = 4'd7;
                10'd417: code_lookup = 4'd4;
                10'd418: code_lookup = 4'd0;
                10'd419: code_lookup = 4'd0;
                10'd420: code_lookup = 4'd1;
                10'd421: code_lookup = 4'd8;
                10'd422: code_lookup = 4'd5;
                10'd423: code_lookup = 4'd5;
                10'd424: code_lookup = 4'd9;
                10'd425: code_lookup = 4'd7;
                10'd426: code_lookup = 4'd1;
                10'd427: code_lookup = 4'd8;
                10'd428: code_lookup = 4'd5;
                10'd429: code_lookup = 4'd8;
                10'd430: code_lookup = 4'd6;
                10'd431: code_lookup = 4'd10;
                10'd432: code_lookup = 4'd5;
                10'd433: code_lookup = 4'd1;
                10'd434: code_lookup = 4'd8;
                10'd435: code_lookup = 4'd7;
                10'd436: code_lookup = 4'd5;
                10'd437: code_lookup = 4'd9;
                10'd438: code_lookup = 4'd0;
                10'd439: code_lookup = 4'd4;
                10'd440: code_lookup = 4'd0;
                10'd441: code_lookup = 4'd5;
                10'd442: code_lookup = 4'd1;
                10'd443: code_lookup = 4'd8;
                10'd444: code_lookup = 4'd10;
                10'd445: code_lookup = 4'd8;
                10'd446: code_lookup = 4'd6;
                10'd447: code_lookup = 4'd7;
                10'd448: code_lookup = 4'd5;
                10'd449: code_lookup = 4'd9;
                10'd450: code_lookup = 4'd10;
                10'd451: code_lookup = 4'd8;
                10'd452: code_lookup = 4'd6;
                10'd453: code_lookup = 4'd7;
                10'd454: code_lookup = 4'd5;
                10'd455: code_lookup = 4'd9;
                10'd456: code_lookup = 4'd5;
                10'd457: code_lookup = 4'd1;
                10'd458: code_lookup = 4'd8;
                10'd459: code_lookup = 4'd10;
                10'd460: code_lookup = 4'd8;
                10'd461: code_lookup = 4'd6;
                10'd462: code_lookup = 4'd5;
                10'd463: code_lookup = 4'd1;
                10'd464: code_lookup = 4'd8;
                10'd465: code_lookup = 4'd0;
                10'd466: code_lookup = 4'd4;
                10'd467: code_lookup = 4'd0;
                10'd468: code_lookup = 4'd8;
                10'd469: code_lookup = 4'd6;
                10'd470: code_lookup = 4'd10;
                10'd471: code_lookup = 4'd5;
                10'd472: code_lookup = 4'd9;
                10'd473: code_lookup = 4'd7;
                10'd474: code_lookup = 4'd1;
                10'd475: code_lookup = 4'd8;
                10'd476: code_lookup = 4'd5;
                10'd477: code_lookup = 4'd8;
                10'd478: code_lookup = 4'd6;
                10'd479: code_lookup = 4'd10;
                10'd480: code_lookup = 4'd1;
                10'd481: code_lookup = 4'd8;
                10'd482: code_lookup = 4'd5;
                10'd483: code_lookup = 4'd4;
                10'd484: code_lookup = 4'd0;
                10'd485: code_lookup = 4'd0;
                10'd486: code_lookup = 4'd8;
                10'd487: code_lookup = 4'd5;
                10'd488: code_lookup = 4'd1;
                10'd489: code_lookup = 4'd6;
                10'd490: code_lookup = 4'd10;
                10'd491: code_lookup = 4'd8;
                10'd492: code_lookup = 4'd9;
                10'd493: code_lookup = 4'd7;
                10'd494: code_lookup = 4'd5;
                10'd495: code_lookup = 4'd8;
                10'd496: code_lookup = 4'd5;
                10'd497: code_lookup = 4'd1;
                10'd498: code_lookup = 4'd0;
                10'd499: code_lookup = 4'd0;
                10'd500: code_lookup = 4'd4;
                10'd501: code_lookup = 4'd6;
                10'd502: code_lookup = 4'd10;
                10'd503: code_lookup = 4'd8;
                10'd504: code_lookup = 4'd1;
                10'd505: code_lookup = 4'd8;
                10'd506: code_lookup = 4'd5;
                10'd507: code_lookup = 4'd4;
                10'd508: code_lookup = 4'd0;
                10'd509: code_lookup = 4'd0;
                10'd510: code_lookup = 4'd8;
                10'd511: code_lookup = 4'd6;
                10'd512: code_lookup = 4'd10;
                10'd513: code_lookup = 4'd1;
                10'd514: code_lookup = 4'd8;
                10'd515: code_lookup = 4'd5;
                10'd516: code_lookup = 4'd5;
                10'd517: code_lookup = 4'd9;
                10'd518: code_lookup = 4'd7;
                10'd519: code_lookup = 4'd4;
                10'd520: code_lookup = 4'd0;
                10'd521: code_lookup = 4'd0;
                10'd522: code_lookup = 4'd3;
                10'd523: code_lookup = 4'd3;
                10'd524: code_lookup = 4'd3;
                10'd525: code_lookup = 4'd2;
                10'd526: code_lookup = 4'd7;
                10'd527: code_lookup = 4'd6;
                10'd528: code_lookup = 4'd6;
                10'd529: code_lookup = 4'd2;
                10'd530: code_lookup = 4'd7;
                10'd531: code_lookup = 4'd3;
                10'd532: code_lookup = 4'd3;
                10'd533: code_lookup = 4'd3;
                10'd534: code_lookup = 4'd7;
                10'd535: code_lookup = 4'd6;
                10'd536: code_lookup = 4'd2;
                10'd537: code_lookup = 4'd2;
                10'd538: code_lookup = 4'd7;
                10'd539: code_lookup = 4'd6;
                default: code_lookup = 4'd0;
            endcase
        end
    endfunction

    reg                 conj_r;
    reg [9:0]           addr;               // idx*9 + term counter
    reg [3:0]           term;               // 0..8 = row*3 + col
    reg signed [W-1:0]  w_a [0:2];          // latched source (B,C,D) pairs
    reg signed [W-1:0]  w_b [0:2];
    reg signed [W-1:0]  acc_a [0:2];        // output accumulators
    reg signed [W-1:0]  acc_b [0:2];
    reg [1:0]           state;

    // ── term unit ──────────────────────────────────────────────────
    // Conjugate remap first (Galois phi -> 1-phi on the coefficient):
    //   +phi <-> -phi^-1, -phi <-> +phi^-1, +sqrt5 <-> -sqrt5
    wire [3:0] code_raw = code_lookup(addr);
    wire [3:0] code = !conj_r        ? code_raw :
                      (code_raw == 4'd5)  ? 4'd8 :
                      (code_raw == 4'd8)  ? 4'd5 :
                      (code_raw == 4'd6)  ? 4'd7 :
                      (code_raw == 4'd7)  ? 4'd6 :
                      (code_raw == 4'd9)  ? 4'd10 :
                      (code_raw == 4'd10) ? 4'd9 : code_raw;

    wire [1:0] col = (term == 4'd0 || term == 4'd3 || term == 4'd6) ? 2'd0 :
                     (term == 4'd1 || term == 4'd4 || term == 4'd7) ? 2'd1 :
                                                                      2'd2;
    wire [1:0] row = (term < 4'd3) ? 2'd0 : (term < 4'd6) ? 2'd1 : 2'd2;

    wire signed [W-1:0] wa = w_a[col];
    wire signed [W-1:0] wb = w_b[col];

    // code * (wa + wb*phi) in Z[phi] — adders and negates only
    reg signed [W-1:0] term_a, term_b;
    always @* begin
        case (code)
            4'd1:    begin term_a =  wa;           term_b =  wb;           end
            4'd2:    begin term_a = -wa;           term_b = -wb;           end
            4'd3:    begin term_a =  wa + wa;      term_b =  wb + wb;      end
            4'd4:    begin term_a = -(wa + wa);    term_b = -(wb + wb);    end
            4'd5:    begin term_a =  wb;           term_b =  wa + wb;      end
            4'd6:    begin term_a = -wb;           term_b = -(wa + wb);    end
            4'd7:    begin term_a =  wb - wa;      term_b =  wa;           end
            4'd8:    begin term_a =  wa - wb;      term_b = -wa;           end
            4'd9:    begin term_a =  wb + wb - wa; term_b =  wa + wa + wb; end
            4'd10:   begin term_a =  wa - wb - wb; term_b = -(wa + wa + wb); end
            default: begin term_a = {W{1'b0}};     term_b = {W{1'b0}};     end
        endcase
    end

    // ── dispatch guards (decode order: BADIDX, UNTAGGED, CATMIX) ───
    wire       bad_idx  = (sel[5:0] > 6'd59);
    wire       untagged = (src_tag == TAG_UNTAGGED);
    wire       catmix   = (src_tag == TAG_MAIN &&  sel[6]) ||
                          (src_tag == TAG_CONJ && !sel[6]);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state <= S_IDLE; busy <= 0; done <= 0;
            fault <= 0; fault_code <= 0; out_tag <= TAG_UNTAGGED;
            conj_r <= 0; addr <= 0; term <= 0;
            w_a[0] <= 0; w_a[1] <= 0; w_a[2] <= 0;
            w_b[0] <= 0; w_b[1] <= 0; w_b[2] <= 0;
            acc_a[0] <= 0; acc_a[1] <= 0; acc_a[2] <= 0;
            acc_b[0] <= 0; acc_b[1] <= 0; acc_b[2] <= 0;
            out_a_a <= 0; out_a_b <= 0; out_b_a <= 0; out_b_b <= 0;
            out_c_a <= 0; out_c_b <= 0; out_d_a <= 0; out_d_b <= 0;
        end else begin
            done <= 0; fault <= 0;
            case (state)
                S_IDLE: if (start) begin
                    if (bad_idx) begin
                        fault <= 1; fault_code <= FAULT_BADIDX;
                    end else if (untagged) begin
                        fault <= 1; fault_code <= FAULT_UNTAGGED;
                    end else if (catmix) begin
                        fault <= 1; fault_code <= FAULT_CATMIX;
                    end else begin
                        conj_r <= sel[6];
                        // idx*9 = idx*8 + idx
                        addr   <= {1'b0, sel[5:0], 3'b000} + {4'b0, sel[5:0]};
                        term   <= 0;
                        w_a[0] <= in_b_a; w_b[0] <= in_b_b;
                        w_a[1] <= in_c_a; w_b[1] <= in_c_b;
                        w_a[2] <= in_d_a; w_b[2] <= in_d_b;
                        acc_a[0] <= 0; acc_a[1] <= 0; acc_a[2] <= 0;
                        acc_b[0] <= 0; acc_b[1] <= 0; acc_b[2] <= 0;
                        busy <= 1; state <= S_ACC;
                    end
                end

                S_ACC: begin
                    acc_a[row] <= acc_a[row] + term_a;
                    acc_b[row] <= acc_b[row] + term_b;
                    if (term == 4'd8) state <= S_SHIFT;
                    else begin term <= term + 4'd1; addr <= addr + 10'd1; end
                end

                S_SHIFT: begin
                    // Unguarded >>>1: licensed by the typestate at dispatch
                    // (doubling theorem — pre-shift sums are even for every
                    // legally tagged input; no divisibility check here).
                    acc_a[0] <= acc_a[0] >>> 1; acc_b[0] <= acc_b[0] >>> 1;
                    acc_a[1] <= acc_a[1] >>> 1; acc_b[1] <= acc_b[1] >>> 1;
                    acc_a[2] <= acc_a[2] >>> 1; acc_b[2] <= acc_b[2] >>> 1;
                    state <= S_ZSUM;
                end

                S_ZSUM: begin
                    out_b_a <= acc_a[0]; out_b_b <= acc_b[0];
                    out_c_a <= acc_a[1]; out_c_b <= acc_b[1];
                    out_d_a <= acc_a[2]; out_d_b <= acc_b[2];
                    out_a_a <= -(acc_a[0] + acc_a[1] + acc_a[2]);
                    out_a_b <= -(acc_b[0] + acc_b[1] + acc_b[2]);
                    out_tag <= conj_r ? TAG_CONJ : TAG_MAIN;
                    done <= 1; busy <= 0; state <= S_IDLE;
                end
            endcase
        end
    end
endmodule
