// spu13_composition_policy_tb.v
//
// Checks spu13_composition_policy.v against the cases in the software oracle
// (software/lib/composition_policy.py) and its trace
// (software/tests/test_composition_trace.py). The two must agree case for
// case; the oracle is normative.
//
// The trace's own rule applies here too: a run in which some outcome never
// appears is untested, however green it looks. This bench fails if accept,
// hold and escalate are not all exercised.

`timescale 1ns / 1ps
`default_nettype none

module spu13_composition_policy_tb;

    reg  [7:0] som1_flags;
    reg  [7:0] som1_error;
    reg  [1:0] verdict;
    wire [1:0] outcome;
    wire [2:0] reason;

    integer checks   = 0;
    integer failures = 0;
    integer saw_accept   = 0;
    integer saw_hold     = 0;
    integer saw_escalate = 0;
    integer gi;
    reg [22:0] golden [0:383];

    localparam [1:0] V_CONCUR      = 2'b00;
    localparam [1:0] V_DISSENT     = 2'b01;
    localparam [1:0] V_UNAVAILABLE = 2'b10;

    localparam [1:0] O_ACCEPT   = 2'b00;
    localparam [1:0] O_HOLD     = 2'b01;
    localparam [1:0] O_ESCALATE = 2'b10;

    // A clean, valid, unambiguous classification: valid | has_second | map_valid
    localparam [7:0] F_CLEAN = 8'b0001_0101;

    spu13_composition_policy dut (
        .som1_flags (som1_flags),
        .som1_error (som1_error),
        .verdict    (verdict),
        .outcome    (outcome),
        .reason     (reason)
    );

    task check;
        input [7:0]  f;
        input [7:0]  e;
        input [1:0]  v;
        input [1:0]  expect_outcome;
        input [2:0]  expect_reason;
        input [255:0] label;
        begin
            som1_flags = f;
            som1_error = e;
            verdict    = v;
            #1;
            checks = checks + 1;
            if (outcome !== expect_outcome || reason !== expect_reason) begin
                failures = failures + 1;
                $display("  FAIL %0s: outcome=%b (want %b) reason=%0d (want %0d)",
                         label, outcome, expect_outcome, reason, expect_reason);
            end
            if (outcome === O_ACCEPT)   saw_accept   = saw_accept   + 1;
            if (outcome === O_HOLD)     saw_hold     = saw_hold     + 1;
            if (outcome === O_ESCALATE) saw_escalate = saw_escalate + 1;
        end
    endtask

    initial begin
        // --- the eight trace steps, in the oracle's order -----------------
        check(F_CLEAN, 8'd0, V_CONCUR,      O_ACCEPT,   3'd0, "concur -> accept");
        check(F_CLEAN, 8'd0, V_DISSENT,     O_HOLD,     3'd1, "dissent -> hold");
        check(F_CLEAN | 8'b0000_1000, 8'd0, V_CONCUR,
              O_ESCALATE, 3'd7, "ambiguous -> escalate even when algebra concurs");
        check(8'b0001_0000, 8'd0, V_CONCUR, O_ESCALATE, 3'd3, "not valid -> escalate");
        check(F_CLEAN, 8'd5, V_CONCUR,      O_ESCALATE, 3'd4, "error code -> escalate");
        check(8'b0000_0101, 8'd0, V_CONCUR, O_ESCALATE, 3'd5, "no map -> escalate");
        check(F_CLEAN, 8'd0, V_UNAVAILABLE, O_HOLD,     3'd2, "unavailable -> hold");
        check(F_CLEAN | 8'b0000_0010, 8'd0, V_CONCUR,
              O_ESCALATE, 3'd6, "busy -> escalate");

        // --- the property that matters: dissent never escalates ----------
        // A dissenting algebra verdict must not be able to promote itself
        // into an escalation; only the decision service's own state can.
        check(F_CLEAN, 8'd0, V_DISSENT, O_HOLD, 3'd1, "dissent cannot escalate");

        // --- priority: several failures at once report the first reason ---
        // Matches the oracle's evaluation order, so traces are comparable.
        check(8'b0000_1000, 8'd9, V_DISSENT, O_ESCALATE, 3'd3,
              "invalid+error+ambiguous -> reports not-valid first");

        // --- every algebra verdict on an unusable frame still escalates ---
        check(8'b0000_0000, 8'd0, V_DISSENT,     O_ESCALATE, 3'd3, "invalid+dissent");
        check(8'b0000_0000, 8'd0, V_UNAVAILABLE, O_ESCALATE, 3'd3, "invalid+unavailable");

        // --- exhaustive parity against the oracle -------------------------
        // 384 vectors generated by software/tests/test_composition_trace.py
        // covering every flag pattern (bits 0-4; 5-7 are reserved), four
        // error codes and every verdict. Case agreement is not equivalence;
        // this is.
        $readmemh("hardware/tests/spu13/composition_policy_golden.mem", golden);
        for (gi = 0; gi < 384; gi = gi + 1) begin
            som1_flags = golden[gi][22:15];
            som1_error = golden[gi][14:7];
            verdict    = golden[gi][6:5];
            #1;
            checks = checks + 1;
            if (outcome !== golden[gi][4:3] || reason !== golden[gi][2:0]) begin
                failures = failures + 1;
                if (failures < 10)
                    $display("  FAIL golden[%0d] flags=%02h err=%02h v=%b: outcome=%b (want %b) reason=%0d (want %0d)",
                             gi, som1_flags, som1_error, verdict,
                             outcome, golden[gi][4:3], reason, golden[gi][2:0]);
            end
            if (outcome === O_ACCEPT)   saw_accept   = saw_accept   + 1;
            if (outcome === O_HOLD)     saw_hold     = saw_hold     + 1;
            if (outcome === O_ESCALATE) saw_escalate = saw_escalate + 1;
        end

        if (saw_accept == 0 || saw_hold == 0 || saw_escalate == 0) begin
            failures = failures + 1;
            $display("  FAIL: not all outcomes exercised (accept=%0d hold=%0d escalate=%0d)",
                     saw_accept, saw_hold, saw_escalate);
        end

        $display("spu13_composition_policy: %0d checks, %0d failed", checks, failures);
        $display("  outcomes exercised: accept=%0d hold=%0d escalate=%0d",
                 saw_accept, saw_hold, saw_escalate);
        if (failures == 0) $display("PASS");
        else               $display("FAIL");
        $finish;
    end

endmodule

`default_nettype wire
