`timescale 1ns / 1ps

// spu13_series_stream_tb.v — Golden-vector testbench for the eps^3 series
// stream evaluator.
//
// Vectors come from a COMMITTED .mem file generated by the Python oracle:
//   PYTHONPATH=software python3 software/lib/digon_recursive.py \
//       --emit-series-mem hardware/tests/spu13/spu13_series_stream_golden.mem
// Format documented in digon_recursive.emit_series_mem.  Singular vectors
// sit mid-run AND last (ordering-adversarial, per the batch-inverter
// precedent).  The tb fails loudly on a missing/empty golden file — no
// vacuous passes.
//
// Assertions per normal vector: bit-exact root, no err_singular, and the
// exact resource count (26 shared-mult launches + 1 tower — the point of
// the static-schedule design).  Per singular vector: err_singular, 0 mults,
// 1 tower.  Busy must be done-coupled throughout.

module spu13_series_stream_tb;

    localparam N_WORDS_MAX = 1 + 16 * 49;   // headroom for up to 16 vectors

    reg clk, rst_n, start;

    reg [31:0] c0_o0_z0, c0_o0_z1, c0_o0_z2, c0_o0_z3;
    reg [31:0] c0_o1_z0, c0_o1_z1, c0_o1_z2, c0_o1_z3;
    reg [31:0] c0_o2_z0, c0_o2_z1, c0_o2_z2, c0_o2_z3;

    reg [31:0] c1_o0_z0, c1_o0_z1, c1_o0_z2, c1_o0_z3;
    reg [31:0] c1_o1_z0, c1_o1_z1, c1_o1_z2, c1_o1_z3;
    reg [31:0] c1_o2_z0, c1_o2_z1, c1_o2_z2, c1_o2_z3;

    reg [31:0] c2_o0_z0, c2_o0_z1, c2_o0_z2, c2_o0_z3;
    reg [31:0] c2_o1_z0, c2_o1_z1, c2_o1_z2, c2_o1_z3;
    reg [31:0] c2_o2_z0, c2_o2_z1, c2_o2_z2, c2_o2_z3;

    wire [31:0] x_o0_z0, x_o0_z1, x_o0_z2, x_o0_z3;
    wire [31:0] x_o1_z0, x_o1_z1, x_o1_z2, x_o1_z3;
    wire [31:0] x_o2_z0, x_o2_z1, x_o2_z2, x_o2_z3;
    wire done, err_singular, busy;

    // ── Inverter interface ───────────────────────────────────────────
    wire        inv_start;
    wire [31:0] inv_z0, inv_z1, inv_z2, inv_z3;
    wire [31:0] inv_r0, inv_r1, inv_r2, inv_r3;
    wire        inv_done, inv_flags_v;

    wire        tmult_start;
    wire [31:0] tmult_a0, tmult_a1, tmult_a2, tmult_a3;
    wire [31:0] tmult_b0, tmult_b1, tmult_b2, tmult_b3;
    wire [31:0] tmult_r0, tmult_r1, tmult_r2, tmult_r3;
    wire        tmult_done, tmult_busy;

    wire        jmult_start;
    wire [31:0] jmult_a0, jmult_a1, jmult_a2, jmult_a3;
    wire [31:0] jmult_b0, jmult_b1, jmult_b2, jmult_b3;
    wire [31:0] jmult_r0, jmult_r1, jmult_r2, jmult_r3;
    wire        jmult_done;

    spu13_series_stream u_dut (
        .clk(clk), .rst_n(rst_n), .start(start),

        .c0_o0_z0(c0_o0_z0), .c0_o0_z1(c0_o0_z1),
        .c0_o0_z2(c0_o0_z2), .c0_o0_z3(c0_o0_z3),
        .c0_o1_z0(c0_o1_z0), .c0_o1_z1(c0_o1_z1),
        .c0_o1_z2(c0_o1_z2), .c0_o1_z3(c0_o1_z3),
        .c0_o2_z0(c0_o2_z0), .c0_o2_z1(c0_o2_z1),
        .c0_o2_z2(c0_o2_z2), .c0_o2_z3(c0_o2_z3),

        .c1_o0_z0(c1_o0_z0), .c1_o0_z1(c1_o0_z1),
        .c1_o0_z2(c1_o0_z2), .c1_o0_z3(c1_o0_z3),
        .c1_o1_z0(c1_o1_z0), .c1_o1_z1(c1_o1_z1),
        .c1_o1_z2(c1_o1_z2), .c1_o1_z3(c1_o1_z3),
        .c1_o2_z0(c1_o2_z0), .c1_o2_z1(c1_o2_z1),
        .c1_o2_z2(c1_o2_z2), .c1_o2_z3(c1_o2_z3),

        .c2_o0_z0(c2_o0_z0), .c2_o0_z1(c2_o0_z1),
        .c2_o0_z2(c2_o0_z2), .c2_o0_z3(c2_o0_z3),
        .c2_o1_z0(c2_o1_z0), .c2_o1_z1(c2_o1_z1),
        .c2_o1_z2(c2_o1_z2), .c2_o1_z3(c2_o1_z3),
        .c2_o2_z0(c2_o2_z0), .c2_o2_z1(c2_o2_z1),
        .c2_o2_z2(c2_o2_z2), .c2_o2_z3(c2_o2_z3),

        .x_o0_z0(x_o0_z0), .x_o0_z1(x_o0_z1),
        .x_o0_z2(x_o0_z2), .x_o0_z3(x_o0_z3),
        .x_o1_z0(x_o1_z0), .x_o1_z1(x_o1_z1),
        .x_o1_z2(x_o1_z2), .x_o1_z3(x_o1_z3),
        .x_o2_z0(x_o2_z0), .x_o2_z1(x_o2_z1),
        .x_o2_z2(x_o2_z2), .x_o2_z3(x_o2_z3),
        .done(done), .err_singular(err_singular), .busy(busy),

        .inv_start(inv_start),
        .inv_z0(inv_z0), .inv_z1(inv_z1),
        .inv_z2(inv_z2), .inv_z3(inv_z3),
        .inv_r0(inv_r0), .inv_r1(inv_r1),
        .inv_r2(inv_r2), .inv_r3(inv_r3),
        .inv_done(inv_done), .inv_flags_v(inv_flags_v),

        .mult_start(jmult_start),
        .mult_a0(jmult_a0), .mult_a1(jmult_a1),
        .mult_a2(jmult_a2), .mult_a3(jmult_a3),
        .mult_b0(jmult_b0), .mult_b1(jmult_b1),
        .mult_b2(jmult_b2), .mult_b3(jmult_b3),
        .mult_r0(jmult_r0), .mult_r1(jmult_r1),
        .mult_r2(jmult_r2), .mult_r3(jmult_r3),
        .mult_done(jmult_done)
    );

    spu13_fp4_inverter u_inverter (
        .clk(clk), .rst_n(rst_n), .start(inv_start),
        .z0(inv_z0), .z1(inv_z1), .z2(inv_z2), .z3(inv_z3),
        .inv0(inv_r0), .inv1(inv_r1), .inv2(inv_r2), .inv3(inv_r3),
        .done(inv_done), .busy(), .flags_v(inv_flags_v),
        .mult_start(tmult_start),
        .mult_a0(tmult_a0), .mult_a1(tmult_a1),
        .mult_a2(tmult_a2), .mult_a3(tmult_a3),
        .mult_b0(tmult_b0), .mult_b1(tmult_b1),
        .mult_b2(tmult_b2), .mult_b3(tmult_b3),
        .mult_r0(tmult_r0), .mult_r1(tmult_r1),
        .mult_r2(tmult_r2), .mult_r3(tmult_r3),
        .mult_done(tmult_done), .mult_busy(tmult_busy)
    );

    spu13_m31_multiplier u_tmult (
        .clk(clk), .rst_n(rst_n), .start(tmult_start),
        .a0(tmult_a0), .a1(tmult_a1), .a2(tmult_a2), .a3(tmult_a3),
        .b0(tmult_b0), .b1(tmult_b1), .b2(tmult_b2), .b3(tmult_b3),
        .r0(tmult_r0), .r1(tmult_r1), .r2(tmult_r2), .r3(tmult_r3),
        .done(tmult_done), .busy(tmult_busy), .rns_error()
    );

    spu13_m31_multiplier u_jmult (
        .clk(clk), .rst_n(rst_n), .start(jmult_start),
        .a0(jmult_a0), .a1(jmult_a1), .a2(jmult_a2), .a3(jmult_a3),
        .b0(jmult_b0), .b1(jmult_b1), .b2(jmult_b2), .b3(jmult_b3),
        .r0(jmult_r0), .r1(jmult_r1), .r2(jmult_r2), .r3(jmult_r3),
        .done(jmult_done), .busy(), .rns_error()
    );

    always #5 clk = ~clk;

    // ── Resource pulse counters ──────────────────────────────────────
    integer mult_pulses = 0, inv_pulses = 0;
    integer mult_mark = 0, inv_mark = 0;
    always @(posedge clk) begin
        if (jmult_start) mult_pulses = mult_pulses + 1;
        if (inv_start)   inv_pulses  = inv_pulses + 1;
    end

    integer test_pass, test_total, busy_errors;

    task run_stream;
        begin
            mult_mark = mult_pulses;
            inv_mark  = inv_pulses;
            start = 1; #10; start = 0;
            #11;
            if (busy !== 1'b1) begin
                busy_errors = busy_errors + 1;
                $display("  busy not asserted after start");
            end
            wait(done); #2;
            if (busy !== 1'b0) begin
                busy_errors = busy_errors + 1;
                $display("  busy still asserted after done");
            end
        end
    endtask

    // ── Golden vector memory ─────────────────────────────────────────
    reg [31:0] gv [0:N_WORDS_MAX-1];
    integer n_vec, v, base, k, errors;
    reg singular;

    task load_vector;
        input integer b;
        begin
            c0_o0_z0=gv[b+1];  c0_o0_z1=gv[b+2];  c0_o0_z2=gv[b+3];  c0_o0_z3=gv[b+4];
            c0_o1_z0=gv[b+5];  c0_o1_z1=gv[b+6];  c0_o1_z2=gv[b+7];  c0_o1_z3=gv[b+8];
            c0_o2_z0=gv[b+9];  c0_o2_z1=gv[b+10]; c0_o2_z2=gv[b+11]; c0_o2_z3=gv[b+12];
            c1_o0_z0=gv[b+13]; c1_o0_z1=gv[b+14]; c1_o0_z2=gv[b+15]; c1_o0_z3=gv[b+16];
            c1_o1_z0=gv[b+17]; c1_o1_z1=gv[b+18]; c1_o1_z2=gv[b+19]; c1_o1_z3=gv[b+20];
            c1_o2_z0=gv[b+21]; c1_o2_z1=gv[b+22]; c1_o2_z2=gv[b+23]; c1_o2_z3=gv[b+24];
            c2_o0_z0=gv[b+25]; c2_o0_z1=gv[b+26]; c2_o0_z2=gv[b+27]; c2_o0_z3=gv[b+28];
            c2_o1_z0=gv[b+29]; c2_o1_z1=gv[b+30]; c2_o1_z2=gv[b+31]; c2_o1_z3=gv[b+32];
            c2_o2_z0=gv[b+33]; c2_o2_z1=gv[b+34]; c2_o2_z2=gv[b+35]; c2_o2_z3=gv[b+36];
        end
    endtask

    function check_x;
        input integer b;
        begin
            check_x =
                (x_o0_z0===gv[b+37] && x_o0_z1===gv[b+38] &&
                 x_o0_z2===gv[b+39] && x_o0_z3===gv[b+40] &&
                 x_o1_z0===gv[b+41] && x_o1_z1===gv[b+42] &&
                 x_o1_z2===gv[b+43] && x_o1_z3===gv[b+44] &&
                 x_o2_z0===gv[b+45] && x_o2_z1===gv[b+46] &&
                 x_o2_z2===gv[b+47] && x_o2_z3===gv[b+48]);
        end
    endfunction

    initial begin
        clk = 0; rst_n = 0; start = 0;
        test_pass = 0; test_total = 0; busy_errors = 0;
        for (k = 0; k < N_WORDS_MAX; k = k + 1) gv[k] = 32'hXXXXXXXX;
        $readmemh("hardware/tests/spu13/spu13_series_stream_golden.mem", gv);
        #20 rst_n = 1; #10;

        // Vacuous-pass guard: golden file must exist and be plausible.
        n_vec = gv[0];
        test_total = test_total + 1;
        if (gv[0] === 32'hXXXXXXXX || n_vec < 4) begin
            $display("FAIL: golden .mem missing/short (n_vec=%0d)", n_vec);
        end else begin
            test_pass = test_pass + 1;

            for (v = 0; v < n_vec; v = v + 1) begin
                base = 1 + v * 49;
                singular = (gv[base] !== 32'd0);
                load_vector(base);
                run_stream();

                if (singular) begin
                    test_total = test_total + 1;
                    if (err_singular === 1'b1) test_pass = test_pass + 1;
                    else $display("FAIL: vec %0d err_singular not asserted", v);

                    test_total = test_total + 1;
                    if ((mult_pulses - mult_mark) === 0 &&
                        (inv_pulses - inv_mark) === 1)
                        test_pass = test_pass + 1;
                    else
                        $display("FAIL: vec %0d singular counts %0d/%0d, expected 0/1",
                                 v, mult_pulses - mult_mark, inv_pulses - inv_mark);
                end else begin
                    test_total = test_total + 1;
                    if (err_singular === 1'b0) test_pass = test_pass + 1;
                    else $display("FAIL: vec %0d spurious err_singular", v);

                    test_total = test_total + 1;
                    if (check_x(base)) test_pass = test_pass + 1;
                    else begin
                        $display("FAIL: vec %0d root mismatch", v);
                        $display("  x0=(%h,%h,%h,%h) exp=(%h,%h,%h,%h)",
                            x_o0_z0,x_o0_z1,x_o0_z2,x_o0_z3,
                            gv[base+37],gv[base+38],gv[base+39],gv[base+40]);
                        $display("  x1=(%h,%h,%h,%h) exp=(%h,%h,%h,%h)",
                            x_o1_z0,x_o1_z1,x_o1_z2,x_o1_z3,
                            gv[base+41],gv[base+42],gv[base+43],gv[base+44]);
                        $display("  x2=(%h,%h,%h,%h) exp=(%h,%h,%h,%h)",
                            x_o2_z0,x_o2_z1,x_o2_z2,x_o2_z3,
                            gv[base+45],gv[base+46],gv[base+47],gv[base+48]);
                    end

                    test_total = test_total + 1;
                    if ((mult_pulses - mult_mark) === 26 &&
                        (inv_pulses - inv_mark) === 1)
                        test_pass = test_pass + 1;
                    else
                        $display("FAIL: vec %0d counts %0d mults / %0d towers, expected 26/1",
                                 v, mult_pulses - mult_mark, inv_pulses - inv_mark);
                end
            end
        end

        test_total = test_total + 1;
        if (busy_errors == 0) test_pass = test_pass + 1;
        else $display("FAIL: %0d busy-discipline violations", busy_errors);

        if (test_pass == test_total)
            $display("PASS: spu13_series_stream_tb (%0d/%0d, %0d vectors)",
                     test_pass, test_total, n_vec);
        else
            $display("FAIL: spu13_series_stream_tb (%0d/%0d)", test_pass, test_total);
        $finish;
    end

    initial begin
        #4000000;
        $display("FAIL: spu13_series_stream_tb (watchdog)");
        $finish;
    end

endmodule
