# Diagnostic: HSYNC on G8 (proven working), RGB on the other three top-row
# pins, and VSYNC broadcast to ALL FOUR bottom-row pins so it is present
# whichever hole the VSYNC wire occupies.
set_property PACKAGE_PIN M21 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
set_property PACKAGE_PIN H7 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PULLTYPE PULLUP [get_ports rst_n]
set_property PACKAGE_PIN G8 [get_ports vga_hsync]
set_property PACKAGE_PIN G7 [get_ports vga_b]
set_property PACKAGE_PIN G5 [get_ports vga_g]
set_property PACKAGE_PIN D5 [get_ports vga_r]
set_property PACKAGE_PIN G6 [get_ports {vga_vsync[0]}]
set_property PACKAGE_PIN D6 [get_ports {vga_vsync[1]}]
set_property PACKAGE_PIN E6 [get_ports {vga_vsync[2]}]
set_property PACKAGE_PIN E5 [get_ports {vga_vsync[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_r]
set_property IOSTANDARD LVCMOS33 [get_ports vga_g]
set_property IOSTANDARD LVCMOS33 [get_ports vga_b]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_vsync[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_vsync[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_vsync[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_vsync[3]}]
