set_property PACKAGE_PIN M21 [get_ports clk_100mhz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100mhz]
create_clock -period 20.000 -name sys_clk [get_ports clk_100mhz]

set_property PACKAGE_PIN H7 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN V17 [get_ports {led_out[0]}]
set_property PACKAGE_PIN W21 [get_ports {led_out[1]}]
set_property PACKAGE_PIN Y21 [get_ports {led_out[2]}]
set_property PACKAGE_PIN V26 [get_ports {led_out[3]}]
set_property PACKAGE_PIN V16 [get_ports fault_led]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports fault_led]
