#!/usr/bin/env python3
# iris_som_edge_verify.py — RTL-vs-oracle verification harness
#
# Trains a 4-node SOM on the Iris dataset (3 features: sepal length,
# petal length, petal width — dropping sepal width to match SPU-4's
# NUM_FEATURES=3), exports weights, and generates a Verilog testbench
# that replays all 150 samples through spu4_som_edge.v against the
# Python oracle.
#
# Usage: python3 software/tests/iris_som_edge_verify.py
# Output: build/iris_som_edge_tb.v (self-checking Verilog testbench)

import csv
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from lib.rational_som import SomNode, weighted_quadrance, find_bmu
from lib.rational_som import RationalSurd

CSV_PATH = os.path.join(os.path.dirname(__file__), "data", "iris.csv")
OUT_TB   = "build/iris_som_edge_tb.v"

NUM_NODES    = 4
NUM_FEATURES = 3      # sepal length, petal length, petal width
EPOCHS       = 20
LEARNING_RATE = 0.3
Q12_SCALE    = 4096   # 12 fractional bits

def load_iris():
    """Load Iris dataset, return list of (features, label)."""
    samples = []
    with open(CSV_PATH) as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) < 5:
                continue
            # Features: sepal_len, sepal_wid, petal_len, petal_wid
            features = [float(row[0]), float(row[2]), float(row[3])]
            label = row[4]
            samples.append((features, label))
    return samples

def to_q12(val):
    """Convert float to Q12 fixed-point integer."""
    return int(round(val * Q12_SCALE))

def from_q12(val):
    """Convert Q12 fixed-point integer back to float."""
    return val / Q12_SCALE

def train_som(samples):
    """Train 4-node SOM with 3 features, Q12 fixed-point."""
    # Initialise nodes with random samples
    import random
    random.seed(42)
    nodes = []
    for i in range(NUM_NODES):
        feat = random.choice(samples)[0]
        nodes.append(SomNode(
            node_id=i,
            axial_q=0,
            axial_r=i,
            cluster_label=i,
            weights=tuple(RationalSurd(to_q12(feat[j]), 0) for j in range(NUM_FEATURES)),
        ))

    for epoch in range(EPOCHS):
        lr = LEARNING_RATE * (1.0 - epoch / EPOCHS)
        random.shuffle(samples)
        for features, _ in samples:
            q12_feat = [to_q12(f) for f in features]
            result = find_bmu([RationalSurd(f, 0) for f in q12_feat], nodes, [RationalSurd(4096, 0)]*NUM_FEATURES)
            if result is None:
                continue
            # Update winner (RationalSurd is immutable — rebuild tuple)
            n = nodes[result.best_node_id]
            new_weights = list(n.weights)
            for j in range(NUM_FEATURES):
                delta = q12_feat[j] - n.weights[j].p
                shift = max(1, 8 - epoch // 3)
                new_p = n.weights[j].p + (delta >> shift)
                new_weights[j] = RationalSurd(new_p, 0)
            nodes[result.best_node_id] = SomNode(
                node_id=n.node_id, axial_q=n.axial_q, axial_r=n.axial_r,
                cluster_label=n.cluster_label, weights=tuple(new_weights)
            )

    return nodes

def export_weights(nodes, path):
    """Export trained weights as a Verilog header include file."""
    with open(path, "w") as f:
        f.write("// Auto-generated Iris SOM weights for spu4_som_edge.v\n")
        f.write(f"// {NUM_NODES} nodes × {NUM_FEATURES} features, Q12 fixed-point\n")
        f.write(f"// Epochs: {EPOCHS}, LR: {LEARNING_RATE}\n\n")
        for n in nodes:
            f.write(f"// Node {n.node_id}: ")
            for j in range(NUM_FEATURES):
                f.write(f"F{j}={from_q12(n.weights[j].p):.1f} ")
            f.write("\n")

def pack_features(vals_pq):
    """Pack a list of (p, q) pairs into spu4_som_edge.v's feature-vector
    format: {F_last_P, F_last_Q, ..., F0_P, F0_Q} — P in the upper 16 bits
    of each 32-bit feature slot, Q in the lower 16 bits (module header
    comment; matches the P-upper/Q-lower convention used everywhere else
    in this repo for a packed RationalSurd)."""
    packed = 0
    for j in range(len(vals_pq) - 1, -1, -1):
        p, q = vals_pq[j]
        packed = (packed << 32) | ((p & 0xFFFF) << 16) | (q & 0xFFFF)
    return packed


def gen_tb(nodes, samples):
    """Generate a self-checking Verilog testbench replaying every sample
    through spu4_som_edge.v and checking best_node against the oracle."""
    NS = len(samples)
    bits = NUM_FEATURES * 2 * 16

    lines = []
    lines.append(f"""// iris_som_edge_tb.v — Auto-generated RTL-vs-oracle verification
// {NUM_NODES} nodes x {NUM_FEATURES} features, {NS} samples, Q12 fixed-point.
// Generated by software/tests/iris_som_edge_verify.py — do not hand-edit.

`timescale 1ns/1ps

module iris_som_edge_tb;

    localparam NUM_FEATURES = {NUM_FEATURES};
    localparam WIDTH        = 16;
    localparam NUM_SAMPLES  = {NS};

    reg clk = 0;
    reg rst_n = 0;
    reg start = 0;
    wire done;
    reg [NUM_FEATURES * 2 * WIDTH - 1 : 0] features;
    reg weight_we = 0;
    reg [1:0] weight_node = 0;
    reg [NUM_FEATURES * 2 * WIDTH - 1 : 0] weight_data;
    wire bmu_valid;
    wire [1:0] best_node;
    wire [31:0] best_quadrance;

    spu4_som_edge #(.NUM_FEATURES(NUM_FEATURES), .WIDTH(WIDTH)) u_dut (
        .clk(clk), .rst_n(rst_n), .start(start), .done(done),
        .features(features),
        .weight_we(weight_we), .weight_node(weight_node), .weight_data(weight_data),
        .bmu_valid(bmu_valid), .best_node(best_node), .best_quadrance(best_quadrance)
    );

    always #5 clk = ~clk;

    // Sample ROM: pre-computed by the Python oracle (train_som/find_bmu)
    reg [NUM_FEATURES * 2 * WIDTH - 1 : 0] sample_rom [0:NUM_SAMPLES-1];
    reg [1:0] expected_bmu [0:NUM_SAMPLES-1];

    integer fail = 0;
    integer i;

    initial begin
        rst_n = 0; start = 0; weight_we = 0;
        #20; rst_n = 1; #20;

        // Sync to a clean clock edge before the first weight write — the
        // #20 reset delays land exactly on clock-edge instants (5ns half
        // period), which races weight_we against the DUT's posedge sample
        // and silently drops every weight load without this.
        @(posedge clk);

        // ── Load weights ──────────────────────────────────────────""")

    # Weight loading sequence
    for n in nodes:
        vals_pq = [(n.weights[j].p, n.weights[j].q) for j in range(NUM_FEATURES)]
        packed = pack_features(vals_pq)
        lines.append(f"        weight_node = 2'd{n.node_id};")
        lines.append(f"        weight_data = {bits}'h{packed & ((1 << bits) - 1):0{bits // 4}x};")
        lines.append("        weight_we = 1; @(posedge clk); weight_we = 0; @(posedge clk);")

    # Sample ROM + expected BMU (Q is always 0 for this dataset — see train_som)
    lines.append("")
    lines.append("        // ── Sample ROM (pre-computed by Python oracle) ────────────")
    for idx, (features_val, _label) in enumerate(samples):
        q12_feat = [to_q12(f) for f in features_val]
        result = find_bmu(
            [RationalSurd(f, 0) for f in q12_feat], nodes,
            [RationalSurd(4096, 0)] * NUM_FEATURES,
        )
        exp_node = result.best_node_id if result and result.valid else 0

        packed = pack_features([(f, 0) for f in q12_feat])
        lines.append(f"        sample_rom[{idx}] = {bits}'h{packed & ((1 << bits) - 1):0{bits // 4}x};")
        lines.append(f"        expected_bmu[{idx}] = 2'd{exp_node};")

    # Test loop
    lines.append("""
        // ── Run classification on all samples ─────────────────────
        for (i = 0; i < NUM_SAMPLES; i = i + 1) begin
            @(posedge clk);
            features = sample_rom[i];
            start = 1;
            @(posedge clk);
            start = 0;
            wait (done);
            @(posedge clk);

            if (!bmu_valid) begin
                $display("FAIL sample %0d: bmu_valid not set", i);
                fail = fail + 1;
            end else if (best_node !== expected_bmu[i]) begin
                $display("FAIL sample %0d: got=%0d exp=%0d Q=%0d",
                    i, best_node, expected_bmu[i], best_quadrance);
                fail = fail + 1;
            end
        end

        if (fail == 0)
            $display("\\nPASS (%0d samples, 0 failures)", NUM_SAMPLES);
        else
            $display("\\nFAIL (%0d failures in %0d samples)", fail, NUM_SAMPLES);
        $finish;
    end

endmodule
""")

    return "\n".join(lines)

def main():
    print("[*] Loading Iris dataset...")
    samples = load_iris()
    print(f"    {len(samples)} samples, {NUM_FEATURES} features (dropped sepal width)")

    print(f"[*] Training {NUM_NODES}-node SOM ({EPOCHS} epochs)...")
    nodes = train_som(samples)

    # Print node summary
    for n in nodes:
        vals = [f"{from_q12(n.weights[j].p):.1f}" for j in range(NUM_FEATURES)]
        print(f"    Node {n.node_id}: ({', '.join(vals)})")

    # Run oracle and count per-node assignments
    counts = [0] * NUM_NODES
    mismatches = 0
    for features, label in samples:
        q12_feat = [to_q12(f) for f in features]
        result = find_bmu([RationalSurd(f, 0) for f in q12_feat], nodes, [RationalSurd(4096, 0)]*NUM_FEATURES)
        if result:
            counts[result.best_node_id] += 1
    print(f"    Oracle BMU distribution: {counts}")

    # Export weights
    os.makedirs("build", exist_ok=True)
    export_weights(nodes, "build/iris_som_edge_weights.txt")

    # Generate testbench
    tb = gen_tb(nodes, samples)
    with open(OUT_TB, "w") as f:
        f.write(tb)
    print(f"[*] Wrote testbench: {OUT_TB} ({len(tb.splitlines())} lines)")
    print(f"[*] Run: iverilog -o build/iris_som_edge_tb.vvp "
          f"hardware/rtl/core/spu4/spu4_som_edge.v {OUT_TB} && vvp build/iris_som_edge_tb.vvp")

if __name__ == "__main__":
    main()
