#!/usr/bin/env python3
"""
VM-vs-RTL trace equivalence test for all six corrected ROTC angles.

Computes expected RationalSurd outputs using the VM's exact Q12-scaled
circulant path, writes them as a Verilog header, compiles and runs the
RTL testbench, and asserts bit-exact match on every component (A,B,C,D)
for angles 0–5.

Implementation:
  python3 software/tests/test_rotc_vm_rtl_trace.py

Requirements: iverilog + vvp in PATH, RationalSurd+QuadrayVector from spu_vm.
"""

import os
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path


# ── Imports from the SPU codebase ──────────────────────────────────────────

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO / "software"))

from spu_vm import RationalSurd, QuadrayVector


# ── VM ROTC computation (mirrors spu_vm.py:1250-1346) ─────────────────────

_ROTC_TABLE = {
    # Tetrahedral C₃ subgroup (angles 0–5)
    0:  (1,  0,  0,  0,  0,  0,  1),   # identity
    1:  (2,  0,  2,  0, -1,  0,  3),   # thirds period-6
    2:  (0,  0,  1,  0,  0,  0,  1),   # P5 forward
    3:  (-1, 0,  2,  0,  2,  0,  3),   # thirds period-2
    4:  (2,  0, -1,  0,  2,  0,  3),   # thirds period-6 inverse
    5:  (0,  0,  0,  0,  1,  0,  1),   # P5 inverse
}

Q12 = 4096


def vm_rotc(source: QuadrayVector, angle: int) -> QuadrayVector:
    """Apply ROTC angle to source using exact VM Q12 path."""
    Fa, Fb, Ga, Gb, Ha, Hb, denom = _ROTC_TABLE[angle]
    F = RationalSurd(Fa, Fb)
    G = RationalSurd(Ga, Gb)
    H = RationalSurd(Ha, Hb)

    # Q12 fixed-point scaling (matches spu_vm.py:1319-1323)
    B = RationalSurd(source.b.a * Q12, source.b.b * Q12)
    C = RationalSurd(source.c.a * Q12, source.c.b * Q12)
    D = RationalSurd(source.d.a * Q12, source.d.b * Q12)

    # Circulant application (matches spu_vm.py:1326-1328)
    b2 = F * B + H * C + G * D
    c2 = G * B + F * C + H * D
    d2 = H * B + G * C + F * D

    # Scale back with symmetric rounding (matches spu_vm.py:1330-1342)
    scale = Q12 * denom
    half = scale // 2

    def rdiv(num: int) -> int:
        if num >= 0:
            return (num + half) // scale
        else:
            return -((-num + half) // scale)

    b2 = RationalSurd(rdiv(b2.a), rdiv(b2.b))
    c2 = RationalSurd(rdiv(c2.a), rdiv(c2.b))
    d2 = RationalSurd(rdiv(d2.a), rdiv(d2.b))

    return QuadrayVector(source.a, b2, c2, d2)


# ── RTL hex encoding ──────────────────────────────────────────────────────

def rs_to_hex(rs: RationalSurd) -> str:
    """Encode RationalSurd as 64-bit hex matching RTL wire format {b[31:0], a[31:0]}."""
    a32 = rs.a & 0xFFFFFFFF
    b32 = rs.b & 0xFFFFFFFF
    return f"64'h{b32:08X}{a32:08X}"


# ── Generate Verilog header with expected values ──────────────────────────

def generate_expected_header(test_vector: QuadrayVector) -> str:
    """Return Verilog header content with expected A,B,C,D for each angle."""
    lines = [
        "// Auto-generated by test_rotc_vm_rtl_trace.py",
        "// Expected ROTC outputs from VM Q12 path for canonical test vector.",
        f"// Input: A={rs_to_hex(test_vector.a)} B={rs_to_hex(test_vector.b)} C={rs_to_hex(test_vector.c)} D={rs_to_hex(test_vector.d)}",
        "",
    ]

    for angle in range(6):
        result = vm_rotc(test_vector, angle)
        lines.append(f"// --- Angle {angle} ---")
        lines.append(f"`define EXPECT_A{angle} {rs_to_hex(result.a)}")
        lines.append(f"`define EXPECT_B{angle} {rs_to_hex(result.b)}")
        lines.append(f"`define EXPECT_C{angle} {rs_to_hex(result.c)}")
        lines.append(f"`define EXPECT_D{angle} {rs_to_hex(result.d)}")
        lines.append("")

    # P5 bypass and inverse bypass flag table
    lines.append("// bypass_p5: angles that use pure permutation path")
    lines.append("`define BYPASS_P5_TABLE 6'b000100  // angle 2 only")
    lines.append("// bypass_p5_inv: angles that use inverse permutation path")
    lines.append("`define BYPASS_P5_INV_TABLE 6'b100000  // angle 5 only")
    lines.append("// apply_div3: angles that need division by 3")
    lines.append("`define APPLY_DIV3_TABLE 6'b011010  // angles 1, 3, 4")

    return "\n".join(lines) + "\n"


# ── Verilog trace testbench ───────────────────────────────────────────────

VERILOG_TB = r"""
`timescale 1ns/1ps

module spu13_rotc_trace_tb;

    reg clk = 0;
    reg rst_n = 0;
    always #5 clk = ~clk;

    reg start = 0;
    wire done;
    reg [63:0] A_in, B_in, C_in, D_in;
    reg [63:0] F, G, H;
    reg bypass_p5;
    reg bypass_p5_inv;
    reg apply_div3;
    wire [63:0] A_out, B_out, C_out, D_out;

    spu13_rotor_core_tdm u_dut (
        .clk(clk), .rst_n(rst_n),
        .start(start), .done(done),
        .A_in(A_in), .B_in(B_in), .C_in(C_in), .D_in(D_in),
        .F(F), .G(G), .H(H),
        .field_sel(2'b00),
        .bypass_p5(bypass_p5), .bypass_p5_inv(bypass_p5_inv),
        .apply_div3(apply_div3),
        .A_out(A_out), .B_out(B_out), .C_out(C_out), .D_out(D_out)
    );

    // Angle F/G/H coefficient ROM (integer representation, denom applied by div3)
    // Identity (angle 0)
    `define ANG0_F  {32'd0, 32'd1}
    `define ANG0_G  64'd0
    `define ANG0_H  64'd0
    // Thirds period-6 (angle 1): F=2, G=2, H=-1, denom=3
    `define ANG1_F  {32'd0, 32'd2}
    `define ANG1_G  {32'd0, 32'd2}
    `define ANG1_H  {32'd0, 32'hFFFFFFFF}
    // P5 forward (angle 2): F=0, G=1, H=0 — pure permutation
    `define ANG2_F  64'd0
    `define ANG2_G  {32'd0, 32'd1}
    `define ANG2_H  64'd0
    // Thirds period-2 (angle 3): F=-1, G=2, H=2, denom=3
    `define ANG3_F  {32'd0, 32'hFFFFFFFF}
    `define ANG3_G  {32'd0, 32'd2}
    `define ANG3_H  {32'd0, 32'd2}
    // Thirds period-6 inverse (angle 4): F=2, G=-1, H=2, denom=3
    `define ANG4_F  {32'd0, 32'd2}
    `define ANG4_G  {32'd0, 32'hFFFFFFFF}
    `define ANG4_H  {32'd0, 32'd2}
    // P5 inverse (angle 5): F=0, G=0, H=1 — reverse permutation
    `define ANG5_F  64'd0
    `define ANG5_G  64'd0
    `define ANG5_H  {32'd0, 32'd1}

    integer angle;
    integer fail_count;
    reg [63:0] coeff_F, coeff_G, coeff_H;
    reg bypass, bypass_inv, div3_en;
    reg [63:0] exp_a, exp_b, exp_c, exp_d;

    initial begin
        $dumpfile("build/spu13_rotc_trace_tb.vcd");
        $dumpvars(0, spu13_rotc_trace_tb);

        fail_count = 0;

        // Canonical test vector — matches VM test vector
        // A = 1 + 0*sqrt(3), B = 2 + 2*sqrt(3), C = 3 + 3*sqrt(3), D = 4 + 4*sqrt(3)
        A_in = `EXPECT_A0;   // identity: A is invariant
        B_in = {32'd2, 32'd2};
        C_in = {32'd3, 32'd3};
        D_in = {32'd4, 32'd4};

        #20 rst_n = 1;
        #20;

        for (angle = 0; angle < 6; angle = angle + 1) begin
            $display("--- Angle %0d ---", angle);

            // Select coefficients and control flags
            case (angle)
                0: begin coeff_F = `ANG0_F; coeff_G = `ANG0_G; coeff_H = `ANG0_H;
                         bypass = 0; bypass_inv = 0; div3_en = 0; end
                1: begin coeff_F = `ANG1_F; coeff_G = `ANG1_G; coeff_H = `ANG1_H;
                         bypass = 0; bypass_inv = 0; div3_en = 1; end
                2: begin coeff_F = `ANG2_F; coeff_G = `ANG2_G; coeff_H = `ANG2_H;
                         bypass = 1; bypass_inv = 0; div3_en = 0; end
                3: begin coeff_F = `ANG3_F; coeff_G = `ANG3_G; coeff_H = `ANG3_H;
                         bypass = 0; bypass_inv = 0; div3_en = 1; end
                4: begin coeff_F = `ANG4_F; coeff_G = `ANG4_G; coeff_H = `ANG4_H;
                         bypass = 0; bypass_inv = 0; div3_en = 1; end
                5: begin coeff_F = `ANG5_F; coeff_G = `ANG5_G; coeff_H = `ANG5_H;
                         bypass = 0; bypass_inv = 1; div3_en = 0; end
            endcase

            F <= coeff_F;
            G <= coeff_G;
            H <= coeff_H;
            bypass_p5 <= bypass;
            bypass_p5_inv <= bypass_inv;
            apply_div3 <= div3_en;

            @(posedge clk);
            start <= 1;
            @(posedge clk);
            start <= 0;
            wait(done);
            @(posedge clk);
            #1;

            // Compare against VM expected values
            case (angle)
                0: begin exp_a = `EXPECT_A0; exp_b = `EXPECT_B0; exp_c = `EXPECT_C0; exp_d = `EXPECT_D0; end
                1: begin exp_a = `EXPECT_A1; exp_b = `EXPECT_B1; exp_c = `EXPECT_C1; exp_d = `EXPECT_D1; end
                2: begin exp_a = `EXPECT_A2; exp_b = `EXPECT_B2; exp_c = `EXPECT_C2; exp_d = `EXPECT_D2; end
                3: begin exp_a = `EXPECT_A3; exp_b = `EXPECT_B3; exp_c = `EXPECT_C3; exp_d = `EXPECT_D3; end
                4: begin exp_a = `EXPECT_A4; exp_b = `EXPECT_B4; exp_c = `EXPECT_C4; exp_d = `EXPECT_D4; end
                5: begin exp_a = `EXPECT_A5; exp_b = `EXPECT_B5; exp_c = `EXPECT_C5; exp_d = `EXPECT_D5; end
            endcase

            if (A_out !== exp_a) begin
                $display("  FAIL: A%0d: got %h, expected %h", angle, A_out, exp_a);
                fail_count = fail_count + 1;
            end else $display("  PASS: A%0d = %h", angle, A_out);

            if (B_out !== exp_b) begin
                $display("  FAIL: B%0d: got %h, expected %h", angle, B_out, exp_b);
                fail_count = fail_count + 1;
            end else $display("  PASS: B%0d = %h", angle, B_out);

            if (C_out !== exp_c) begin
                $display("  FAIL: C%0d: got %h, expected %h", angle, C_out, exp_c);
                fail_count = fail_count + 1;
            end else $display("  PASS: C%0d = %h", angle, C_out);

            if (D_out !== exp_d) begin
                $display("  FAIL: D%0d: got %h, expected %h", angle, D_out, exp_d);
                fail_count = fail_count + 1;
            end else $display("  PASS: D%0d = %h", angle, D_out);

            #40;
        end

        if (fail_count == 0)
            $display("ALL 24 CHECKS PASSED (6 angles x 4 components)");
        else
            $display("FAILED: %0d mismatches", fail_count);

        #200;
        $finish;
    end

endmodule
"""


# ── Main test driver ──────────────────────────────────────────────────────

def main() -> int:
    repo = Path(__file__).resolve().parent.parent.parent
    build_dir = repo / "build"
    build_dir.mkdir(exist_ok=True)

    # 1. Define canonical test vector
    test_vector = QuadrayVector(
        RationalSurd(1, 0),   # A = 1 + 0√3
        RationalSurd(2, 2),   # B = 2 + 2√3
        RationalSurd(3, 3),   # C = 3 + 3√3
        RationalSurd(4, 4),   # D = 4 + 4√3
    )

    # 2. Print VM expected outputs for transparency
    print("VM expected outputs (Q12 path):")
    for angle in range(6):
        result = vm_rotc(test_vector, angle)
        names = {0: "identity", 1: "thirds period-6", 2: "P5 forward",
                 3: "thirds period-2", 4: "thirds period-6 inv", 5: "P5 inverse"}
        print(f"  Angle {angle} ({names[angle]}):")
        print(f"    A = {result.a!r}")
        print(f"    B = {result.b!r}")
        print(f"    C = {result.c!r}")
        print(f"    D = {result.d!r}")
        print(f"    A_hex = {rs_to_hex(result.a)}")
        print(f"    B_hex = {rs_to_hex(result.b)}")
        print(f"    C_hex = {rs_to_hex(result.c)}")
        print(f"    D_hex = {rs_to_hex(result.d)}")

    # 3. Generate expected header
    header_content = generate_expected_header(test_vector)
    header_path = build_dir / "rotc_trace_expected.vh"
    header_path.write_text(header_content)
    print(f"\nWrote expected header: {header_path}")

    # 4. Write Verilog testbench
    tb_path = build_dir / "spu13_rotc_trace_tb.v"
    tb_content = f"`include \"{header_path}\"\n" + VERILOG_TB
    tb_path.write_text(tb_content)

    # 5. Find source files
    rotor_core = repo / "hardware/rtl/core/spu13/spu13_rotor_core_tdm.v"
    surd_mult = repo / "hardware/rtl/common/prim/surd_multiplier.v"

    if not rotor_core.exists():
        print(f"ERROR: rotor core not found: {rotor_core}")
        return 1
    if not surd_mult.exists():
        print(f"ERROR: surd_multiplier not found: {surd_mult}")
        return 1

    # 6. Compile
    vvp_path = build_dir / "spu13_rotc_trace_tb.vvp"
    compile_cmd = [
        "iverilog", "-g2012",
        "-o", str(vvp_path),
        "-I", str(repo / "hardware/rtl/common/prim"),
        "-y", str(repo / "hardware/rtl/common/prim"),
        "-y", str(repo / "hardware/rtl/core/spu13"),
        str(tb_path),
    ]
    print(f"\nCompile: {' '.join(compile_cmd)}")
    cr = subprocess.run(compile_cmd, capture_output=True, text=True, cwd=str(repo))
    if cr.returncode != 0:
        print(f"COMPILE ERROR:\n{cr.stderr}")
        return 1

    # 7. Run simulation
    print(f"Run: vvp {vvp_path}")
    rr = subprocess.run(["vvp", str(vvp_path)], capture_output=True, text=True,
                        cwd=str(repo), timeout=30)
    print(rr.stdout)
    if rr.stderr:
        print(rr.stderr, file=sys.stderr)

    if "ALL 24 CHECKS PASSED" in rr.stdout:
        print("\nVM-vs-RTL TRACE EQUIVALENCE: PASS")
        return 0
    else:
        print("\nVM-vs-RTL TRACE EQUIVALENCE: FAIL")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
