#!/usr/bin/env python3
"""
Six-step rational robotics trace against the ROTC TDM RTL core.

The host oracle emits the exact integer six-step trajectory for corrected
ROTC angle 1. The generated RTL testbench then applies:

    forward angle 1
    inverse angle 4

for each phase. Every inverse must recover the phase input, phases 0-4 must
not close the orbit, and phase 5 must close exactly.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO / "software"))

from lib.rational_robotics import (  # noqa: E402
    QuadrayQ,
    q3,
    six_step_kinematics_trace,
)


def q3_to_hex(value) -> str:
    """Encode Q3 p + q*sqrt(3) as RTL {q[31:0], p[31:0]} hex."""

    if value.p.denominator != 1 or value.q.denominator != 1:
        raise ValueError(f"RTL six-step fixture requires integer Q3, got {value}")
    p32 = int(value.p) & 0xFFFFFFFF
    q32 = int(value.q) & 0xFFFFFFFF
    return f"64'h{q32:08X}{p32:08X}"


def quadray_macros(prefix: str, value: QuadrayQ) -> list[str]:
    return [
        f"`define {prefix}_A {q3_to_hex(value.a)}",
        f"`define {prefix}_B {q3_to_hex(value.b)}",
        f"`define {prefix}_C {q3_to_hex(value.c)}",
        f"`define {prefix}_D {q3_to_hex(value.d)}",
    ]


def generate_expected_header() -> str:
    root = QuadrayQ(q3(1), q3(2, 2), q3(3, 3), q3(4, 4))
    trace = six_step_kinematics_trace(start=root, angle=1)

    lines = [
        "// Auto-generated by test_rotc_six_step_rtl_trace.py",
        "// Root vector is chosen so corrected angle 1 remains integer at each phase.",
        "",
        *quadray_macros("ROOT", root),
        "",
    ]

    for frame in trace:
        lines.append(f"// --- Six-step phase {frame.phase} commanded vector ---")
        lines.extend(quadray_macros(f"EXPECT_CMD{frame.phase}", frame.commanded_vector))
        lines.append("")

    return "\n".join(lines) + "\n"


VERILOG_TB = r"""
`timescale 1ns/1ps

module spu13_rotc_six_step_trace_tb;

    reg clk = 0;
    reg rst_n = 0;
    always #5 clk = ~clk;

    reg start = 0;
    wire done;
    reg [63:0] A_in, B_in, C_in, D_in;
    reg [63:0] F, G, H;
    reg bypass_p5 = 0;
    reg bypass_p5_inv = 0;
    reg apply_div3 = 0;
    wire [63:0] A_out, B_out, C_out, D_out;

    spu13_rotor_core_tdm u_dut (
        .clk(clk), .rst_n(rst_n),
        .start(start), .done(done),
        .A_in(A_in), .B_in(B_in), .C_in(C_in), .D_in(D_in),
        .F(F), .G(G), .H(H),
        .field_sel(2'b00),
        .bypass_p5(bypass_p5),
        .bypass_p5_inv(bypass_p5_inv),
        .apply_div3(apply_div3),
        .A_out(A_out), .B_out(B_out), .C_out(C_out), .D_out(D_out)
    );

    reg [63:0] root_a, root_b, root_c, root_d;
    reg [63:0] cur_a, cur_b, cur_c, cur_d;
    reg [63:0] cmd_a, cmd_b, cmd_c, cmd_d;
    reg [63:0] rec_a, rec_b, rec_c, rec_d;
    reg [63:0] exp_a [0:5];
    reg [63:0] exp_b [0:5];
    reg [63:0] exp_c [0:5];
    reg [63:0] exp_d [0:5];
    integer phase;
    integer fail_count;

    task automatic select_angle;
        input [2:0] angle;
        begin
            case (angle)
                3'd1: begin
                    F = {32'd0, 32'd2};
                    G = {32'd0, 32'd2};
                    H = {32'd0, 32'hFFFFFFFF};
                    bypass_p5 = 0;
                    bypass_p5_inv = 0;
                    apply_div3 = 1;
                end
                3'd4: begin
                    F = {32'd0, 32'd2};
                    G = {32'd0, 32'hFFFFFFFF};
                    H = {32'd0, 32'd2};
                    bypass_p5 = 0;
                    bypass_p5_inv = 0;
                    apply_div3 = 1;
                end
                default: begin
                    F = {32'd0, 32'd1};
                    G = 64'd0;
                    H = 64'd0;
                    bypass_p5 = 0;
                    bypass_p5_inv = 0;
                    apply_div3 = 0;
                end
            endcase
        end
    endtask

    task automatic run_angle;
        input [2:0] angle;
        input [63:0] src_a;
        input [63:0] src_b;
        input [63:0] src_c;
        input [63:0] src_d;
        output [63:0] dst_a;
        output [63:0] dst_b;
        output [63:0] dst_c;
        output [63:0] dst_d;
        begin
            select_angle(angle);
            A_in = src_a;
            B_in = src_b;
            C_in = src_c;
            D_in = src_d;
            @(posedge clk);
            start = 1;
            @(posedge clk);
            start = 0;
            wait(done);
            @(posedge clk);
            #1;
            dst_a = A_out;
            dst_b = B_out;
            dst_c = C_out;
            dst_d = D_out;
        end
    endtask

    initial begin
        $dumpfile("build/spu13_rotc_six_step_trace_tb.vcd");
        $dumpvars(0, spu13_rotc_six_step_trace_tb);

        fail_count = 0;

        root_a = `ROOT_A;
        root_b = `ROOT_B;
        root_c = `ROOT_C;
        root_d = `ROOT_D;

        exp_a[0] = `EXPECT_CMD0_A; exp_b[0] = `EXPECT_CMD0_B;
        exp_c[0] = `EXPECT_CMD0_C; exp_d[0] = `EXPECT_CMD0_D;
        exp_a[1] = `EXPECT_CMD1_A; exp_b[1] = `EXPECT_CMD1_B;
        exp_c[1] = `EXPECT_CMD1_C; exp_d[1] = `EXPECT_CMD1_D;
        exp_a[2] = `EXPECT_CMD2_A; exp_b[2] = `EXPECT_CMD2_B;
        exp_c[2] = `EXPECT_CMD2_C; exp_d[2] = `EXPECT_CMD2_D;
        exp_a[3] = `EXPECT_CMD3_A; exp_b[3] = `EXPECT_CMD3_B;
        exp_c[3] = `EXPECT_CMD3_C; exp_d[3] = `EXPECT_CMD3_D;
        exp_a[4] = `EXPECT_CMD4_A; exp_b[4] = `EXPECT_CMD4_B;
        exp_c[4] = `EXPECT_CMD4_C; exp_d[4] = `EXPECT_CMD4_D;
        exp_a[5] = `EXPECT_CMD5_A; exp_b[5] = `EXPECT_CMD5_B;
        exp_c[5] = `EXPECT_CMD5_C; exp_d[5] = `EXPECT_CMD5_D;

        cur_a = root_a;
        cur_b = root_b;
        cur_c = root_c;
        cur_d = root_d;

        #20 rst_n = 1;
        #20;

        for (phase = 0; phase < 6; phase = phase + 1) begin
            $display("--- Six-step RTL phase %0d ---", phase);

            run_angle(3'd1, cur_a, cur_b, cur_c, cur_d, cmd_a, cmd_b, cmd_c, cmd_d);
            run_angle(3'd4, cmd_a, cmd_b, cmd_c, cmd_d, rec_a, rec_b, rec_c, rec_d);

            if (cmd_a !== exp_a[phase]) begin
                $display("  FAIL: phase %0d cmd A got %h expected %h", phase, cmd_a, exp_a[phase]);
                fail_count = fail_count + 1;
            end
            if (cmd_b !== exp_b[phase]) begin
                $display("  FAIL: phase %0d cmd B got %h expected %h", phase, cmd_b, exp_b[phase]);
                fail_count = fail_count + 1;
            end
            if (cmd_c !== exp_c[phase]) begin
                $display("  FAIL: phase %0d cmd C got %h expected %h", phase, cmd_c, exp_c[phase]);
                fail_count = fail_count + 1;
            end
            if (cmd_d !== exp_d[phase]) begin
                $display("  FAIL: phase %0d cmd D got %h expected %h", phase, cmd_d, exp_d[phase]);
                fail_count = fail_count + 1;
            end

            if (rec_a !== cur_a || rec_b !== cur_b || rec_c !== cur_c || rec_d !== cur_d) begin
                $display("  FAIL: phase %0d inverse-balance mismatch", phase);
                $display("        recovered %h %h %h %h", rec_a, rec_b, rec_c, rec_d);
                $display("        expected  %h %h %h %h", cur_a, cur_b, cur_c, cur_d);
                fail_count = fail_count + 1;
            end else begin
                $display("  PASS: phase %0d inverse-balanced", phase);
            end

            if (phase < 5) begin
                if (cmd_a === root_a && cmd_b === root_b && cmd_c === root_c && cmd_d === root_d) begin
                    $display("  FAIL: phase %0d closed early", phase);
                    fail_count = fail_count + 1;
                end else begin
                    $display("  PASS: phase %0d remains open", phase);
                end
            end else begin
                if (cmd_a === root_a && cmd_b === root_b && cmd_c === root_c && cmd_d === root_d) begin
                    $display("  PASS: phase 5 closes the six-step orbit");
                end else begin
                    $display("  FAIL: phase 5 did not close");
                    fail_count = fail_count + 1;
                end
            end

            cur_a = cmd_a;
            cur_b = cmd_b;
            cur_c = cmd_c;
            cur_d = cmd_d;
        end

        if (fail_count == 0)
            $display("ALL 6 SIX-STEP RTL PHASES PASSED");
        else
            $display("FAILED: %0d six-step RTL mismatches", fail_count);

        #100;
        $finish;
    end

endmodule
"""


def main() -> int:
    build_dir = REPO / "build"
    build_dir.mkdir(exist_ok=True)

    header_path = build_dir / "rotc_six_step_expected.vh"
    header_path.write_text(generate_expected_header())

    tb_path = build_dir / "spu13_rotc_six_step_trace_tb.v"
    tb_path.write_text(f"`include \"{header_path}\"\n" + VERILOG_TB)

    vvp_path = build_dir / "spu13_rotc_six_step_trace_tb.vvp"
    compile_cmd = [
        "iverilog",
        "-g2012",
        "-o",
        str(vvp_path),
        "-I",
        str(REPO / "hardware/rtl/common/prim"),
        "-y",
        str(REPO / "hardware/rtl/common/prim"),
        "-y",
        str(REPO / "hardware/rtl/core/spu13"),
        str(tb_path),
    ]

    print(f"Compile: {' '.join(compile_cmd)}")
    cr = subprocess.run(compile_cmd, capture_output=True, text=True, cwd=str(REPO))
    if cr.returncode != 0:
        print(f"COMPILE ERROR:\n{cr.stderr}")
        return 1

    print(f"Run: vvp {vvp_path}")
    rr = subprocess.run(
        ["vvp", str(vvp_path)],
        capture_output=True,
        text=True,
        cwd=str(REPO),
        timeout=30,
    )
    print(rr.stdout)
    if rr.stderr:
        print(rr.stderr, file=sys.stderr)

    if "ALL 6 SIX-STEP RTL PHASES PASSED" in rr.stdout:
        print("ROTC SIX-STEP RTL TRACE: PASS")
        return 0

    print("ROTC SIX-STEP RTL TRACE: FAIL")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
