#!/usr/bin/env python3
"""Generate and verify the frozen full-width A31 inverter corpus.

The expected values come from the existing bit-exact tower oracle in
``software/lib/a31_field.py``.  The committed memory is deliberately frozen
before the structured-inverter RTL is written, so candidate results cannot
be used to manufacture their own expected answers.

Usage:
    python3 software/tests/test_fp4_inverter_golden.py
    python3 software/tests/test_fp4_inverter_golden.py --emit-mem
"""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "software"))

from lib.a31_field import (  # noqa: E402
    A31_ONE,
    P,
    a31_mul,
    a31_norm,
    a31_tower_inv,
)

GOLDEN_MEM = ROOT / "hardware/tests/spu13/spu13_fp4_inverter_golden.mem"
SQRT15 = pow(15, (P + 1) // 4, P)


def build_inputs() -> list[tuple[str, tuple[int, int, int, int]]]:
    """Return named canonical inputs, including extrema and non-units."""
    inputs = [
        ("identity", (1, 0, 0, 0)),
        ("scalar_two", (2, 0, 0, 0)),
        ("scalar_three", (3, 0, 0, 0)),
        ("scalar_five", (5, 0, 0, 0)),
        ("scalar_six", (6, 0, 0, 0)),
        ("scalar_seven", (7, 0, 0, 0)),
        ("scalar_nine", (9, 0, 0, 0)),
        ("scalar_eleven", (11, 0, 0, 0)),
        ("scalar_p_minus_one", (P - 1, 0, 0, 0)),
        ("pure_sqrt3", (0, 1, 0, 0)),
        ("pure_sqrt5", (0, 0, 1, 0)),
        ("pure_sqrt15", (0, 0, 0, 1)),
        # These large canonical residues force the weighted A31 accumulator
        # through its high bits while the conjugations create cancellation.
        ("all_p_minus_one", (P - 1, P - 1, P - 1, P - 1)),
        ("alternating_extrema", (P - 1, 1, P - 1, 1)),
        ("descending_extrema", (P - 1, P - 2, P - 3, P - 4)),
        ("half_and_extrema", (0x40000000, 0x3FFFFFFF, P - 2, 2)),
        ("mixed_regression", (12345, 67890, 11111, 22222)),
        ("mixed_large", (0x71234567, 0x6ABCDE01, 0x456789AB, 0x23456789)),
        ("zero", (0, 0, 0, 0)),
        ("zero_divisor_positive", (SQRT15, 0, 0, 1)),
        ("zero_divisor_negative", (P - SQRT15, 0, 0, 1)),
    ]

    # Multiplication by a unit preserves zero-divisor status and produces
    # nontrivial nonzero tuples that do not resemble the defining factor.
    zd = (SQRT15, 0, 0, 1)
    inputs.extend([
        ("zero_divisor_mixed_a", a31_mul(zd, (2, 3, 5, 7))),
        ("zero_divisor_mixed_b", a31_mul(zd, (P - 2, 17, P - 19, 23))),
    ])

    rng = random.Random(0xA31_2026)
    for index in range(8):
        while True:
            value = tuple(rng.randrange(P) for _ in range(4))
            if a31_norm(value) != 0:
                inputs.append((f"deterministic_unit_{index}", value))
                break
    return inputs


def render_mem() -> str:
    inputs = build_inputs()
    lines = [
        "// spu13_fp4_inverter_golden.mem — auto-generated frozen vectors",
        "// Format: <n_cases>, then 9 words per case:",
        "//   z0 z1 z2 z3 inv0 inv1 inv2 inv3 flags_v",
        "// Generated by test_fp4_inverter_golden.py --emit-mem",
        "",
        f"{len(inputs):08X}",
    ]
    for name, value in inputs:
        inverse, singular = a31_tower_inv(value)
        expected = (0, 0, 0, 0) if singular else inverse
        lines.append(f"// {name}")
        for word in (*value, *expected, int(singular)):
            lines.append(f"{word:08X}")
    return "\n".join(lines) + "\n"


def verify_vectors() -> None:
    inputs = build_inputs()
    singular_count = 0
    for name, value in inputs:
        inverse, singular = a31_tower_inv(value)
        if singular:
            singular_count += 1
            assert a31_norm(value) == 0, f"{name}: false singular classification"
            assert inverse is None, f"{name}: singular input returned an inverse"
        else:
            assert inverse is not None, f"{name}: unit returned no inverse"
            assert a31_mul(value, inverse) == A31_ONE, f"{name}: z * inv(z) != 1"

    expected = render_mem()
    assert GOLDEN_MEM.exists(), f"missing committed golden file: {GOLDEN_MEM}"
    actual = GOLDEN_MEM.read_text()
    assert actual == expected, (
        "committed inverter vectors drifted; regenerate explicitly with --emit-mem"
    )
    print(
        f"PASS: fp4 inverter golden corpus ({len(inputs)} vectors, "
        f"{len(inputs) - singular_count} units, {singular_count} singulars)"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--emit-mem",
        action="store_true",
        help="replace the committed memory with oracle-derived vectors",
    )
    args = parser.parse_args()
    if args.emit_mem:
        GOLDEN_MEM.write_text(render_mem())
        print(f"Wrote {GOLDEN_MEM}")
    verify_vectors()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
