#!/usr/bin/env python3
"""Generate the 256-entry reciprocal-estimate ROM for spu_reciprocal_core.v.

Reuses build_lut() from software/lib/gpu_reciprocal_oracle.py -- the same
function the exhaustive characterization in
spu_strategy/contract_gpu_reciprocal_scoping_2026-08-25.md validated -- so
the RTL's ROM and the oracle's ROM are generated by the identical code
path, not two hand-kept copies that could drift.

Writes hardware/rtl/arch/gpu_reciprocal_lut_q15.mem: 256 lines of 4-hex-digit
(16-bit) values, $readmemh format, matching the existing pade_num/den .mem
convention. Per AGENTS.md's "no manual edits to generated files" rule --
regenerate via this script, never hand-edit the .mem file.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "software", "lib"))
from gpu_reciprocal_oracle import build_lut, LUT_INDEX_BITS, OUT_FRAC_BITS

OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "hardware", "rtl", "arch",
                         "gpu_reciprocal_lut_q15.mem")


def main():
    lut = build_lut()
    assert len(lut) == (1 << LUT_INDEX_BITS)
    with open(OUT_PATH, "w") as f:
        for entry in lut:
            assert 0 <= entry < (1 << 16), f"entry {entry} doesn't fit 16 bits"
            f.write(f"{entry:04x}\n")
    print(f"Wrote {len(lut)} entries to {OUT_PATH} (OUT_FRAC_BITS={OUT_FRAC_BITS})")


if __name__ == "__main__":
    main()
