#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate and verify the evidence tables for LUCAS_MAC_PAPER.tex.

The arithmetic rows are computed from the same independent Python oracle used
to make the RTL golden vectors.  Physical rows are deliberately artifact-level
measurements copied from the hardware evidence ledger; verification checks the
ledger markers before accepting them.

Usage:
    python3 tools/lucas_paper_data.py --output docs/lucas_paper_tables.tex
    python3 tools/lucas_paper_data.py --verify
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "software" / "tests"))

from test_lucas_mac_oracle import (  # noqa: E402
    DEFAULT_MODULUS,
    LUCAS_PRIMES,
    phi_conj,
    phi_inv,
    phi_mul,
    phi_mul_full,
    phi_order,
    phi_phslk,
    pinv_latency_profile,
)


EXPECTED_PERIODS = {11: 10, 29: 14, 199: 22, 521: 26, 3571: 34, 9349: 38}

RESOURCE_ROWS = (
    ("Tang fast probe", "696 LUT4; 216 DFF", "0 / 0", "126.50 MHz; silicon"),
    ("Tang PHSLK probe", "293 LUT4; 146 DFF", "0 / 0", "200.40 MHz; silicon"),
    ("Artix Lucas MAC leaf", "955 estimated LCs", "92 / --", "mapped in LUCAS spin"),
    ("Whole Artix LUCAS spin", "5,073 estimated LCs", "120 / --", "4.41 MHz; silicon"),
)

EVIDENCE_MARKERS = (
    ("docs/hardware_evidence.md", "696 LUT4, 216 DFF, 416 ALU, 0 BRAM, 0 DSP"),
    ("docs/hardware_evidence.md", "126.50 MHz"),
    ("docs/hardware_evidence.md", "293 LUT4, 146 DFF, 182 ALU, 0 BRAM, 0 DSP"),
    ("docs/hardware_evidence.md", "200.40 MHz"),
    ("docs/CURRENT_STATUS.md", "955 estimated LCs"),
    ("docs/CURRENT_STATUS.md", "estimated 5,073 LCs"),
    ("docs/CURRENT_STATUS.md", "120 DSP48E1"),
    ("docs/CURRENT_STATUS.md", "4.41 MHz"),
)


def generated_tables() -> str:
    periods = "\n".join(
        f"{p} & {mod} & {EXPECTED_PERIODS[mod]} \\\\"
        for p, mod in LUCAS_PRIMES.items()
    )
    inv = phi_inv(3, 5)
    ops = (
        (r"$\phi(3+5\phi)$", phi_mul(3, 5), (5, 8)),
        (r"$\overline{3+5\phi}$", phi_conj(3, 5), (8, 516)),
        (r"$(3+5\phi)(2+7\phi)$", phi_mul_full(3, 5, 2, 7), (41, 66)),
        (r"$(3+5\phi)^{-1}$", inv, (513, 5)),
        (r"$(3+5\phi)(3+5\phi)^{-1}$",
         phi_mul_full(3, 5, inv[0], inv[1]), (1, 0)),
    )
    op_rows = "\n".join(
        f"{label} & $({got[0]},{got[1]})$ & "
        f"{'$\\checkmark$' if got == expected else '$\\times$'} \\\\"
        for label, got, expected in ops
    )
    resources = "\n".join(
        f"{name} & {logic} & {dsp_bram} & {evidence} \\\\"
        for name, logic, dsp_bram, evidence in RESOURCE_ROWS
    )
    profile = pinv_latency_profile(DEFAULT_MODULUS)
    return rf"""% LUCAS publication data -- auto-generated by tools/lucas_paper_data.py
\newcommand{{\LucasPrimeTable}}{{%
\begin{{table}}[ht]
\centering
\caption{{Lucas-prime $\phi$ periods computed by the publication oracle.}}
\label{{tab:lucas}}
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\begin{{tabular}}{{rrr}}
\toprule
$p$ & $L_p$ & Period \\
\midrule
{periods}
\bottomrule
\end{{tabular}}
\end{{table}}
}}

\newcommand{{\LucasTimingTable}}{{%
\begin{{table}}[ht]
\centering
\caption{{Accepted-operation latency of the reusable MAC core. PMUL's three
cycles are busy cycles after acceptance; PINV is data-dependent but bounded by
a 64-iteration watchdog. Transport and sidecar scheduling are excluded.}}
\label{{tab:timing}}
\footnotesize
\setlength{{\tabcolsep}}{{3pt}}
\begin{{tabular}}{{lll}}
\toprule
Opcode & Core latency & Arithmetic path \\
\midrule
PSCALE & 1 cycle & shift/add, zero multiply \\
PCHIRAL & 1 cycle & add/subtract, zero multiply \\
PMUL & 3 busy cycles & four scalar products \\
PINV & bounded iterative & norm, BEEA, scalar products \\
PHSLK & 1 cycle & two cross-products \\
\bottomrule
\end{{tabular}}
\end{{table}}
}}

\newcommand{{\LucasOperationTable}}{{%
\begin{{table}}[ht]
\centering
\caption{{Selected arithmetic vectors recomputed by the publication oracle.}}
\label{{tab:ops}}
\footnotesize
\setlength{{\tabcolsep}}{{3pt}}
\begin{{tabular}}{{lll}}
\toprule
Operation & Oracle pair $(a,b)$ & Match \\
\midrule
{op_rows}
\bottomrule
\end{{tabular}}
\end{{table}}
}}

\newcommand{{\LucasResourceTable}}{{%
\begin{{table*}}[t]
\centering
\caption{{Mapped implementation artifacts. Backend-native logic counts are not
cross-vendor equivalents. ``Silicon'' denotes the bounded vectors recorded in
the hardware evidence ledger, not exhaustive input coverage.}}
\label{{tab:resources}}
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\begin{{tabular}}{{llll}}
\toprule
Artifact & Logic/registers & DSP / BRAM & Timing/evidence \\
\midrule
{resources}
\bottomrule
\end{{tabular}}
\end{{table*}}
}}

\newcommand{{\LucasPinvProfileTable}}{{%
\begin{{table}}[ht]
\centering
\caption{{Exhaustive software-oracle profile of the RTL-style scalar PINV
inverse over $\mathbb{{Z}}[\phi]/L_{{521}}$. Counts exclude acceptance.}}
\label{{tab:pinv-profile}}
\footnotesize
\setlength{{\tabcolsep}}{{3pt}}
\begin{{tabular}}{{lr}}
\toprule
Measure & Oracle result \\
\midrule
Nonzero-norm elements & {profile['nonzero_elements']:,} \\
Zero-divisor elements & {profile['zero_divisors']:,} \\
Unique nonzero norms & {profile['unique_norms']} \\
Busy cycles, min/max/mean & {profile['min_cycles']}/{profile['max_cycles']}/{profile['avg_cycles']:.2f} \\
\bottomrule
\end{{tabular}}
\end{{table}}
}}
% End auto-generated LUCAS publication data
"""


def verify() -> tuple[int, list[str]]:
    checks: list[tuple[bool, str]] = []
    for mod, expected in EXPECTED_PERIODS.items():
        checks.append((phi_order(mod) == expected, f"phi period modulo {mod}"))

    inv = phi_inv(3, 5)
    checks.extend((
        (phi_mul(3, 5) == (5, 8), "PSCALE vector"),
        (phi_conj(3, 5) == (8, 516), "PCHIRAL vector"),
        (phi_mul_full(3, 5, 2, 7) == (41, 66), "PMUL vector"),
        (inv == (513, 5), "PINV vector"),
        (phi_mul_full(3, 5, inv[0], inv[1]) == (1, 0), "inverse identity"),
    ))
    coherent = phi_phslk((3, 5), (2, 7), (6, 10), (4, 14))
    mismatch = phi_phslk((3, 5), (2, 7), (6, 11), (4, 14))
    singular = phi_phslk((3, 5), (1, 100), (6, 10), (4, 14))
    checks.extend((
        (coherent[:2] == (True, False), "PHSLK coherent vector"),
        (mismatch[:2] == (False, False), "PHSLK mismatch vector"),
        (singular[:2] == (False, True), "PHSLK singular vector"),
    ))

    profile = pinv_latency_profile(DEFAULT_MODULUS)
    expected_profile = {
        "nonzero_elements": 270400,
        "zero_divisors": 1041,
        "unique_norms": 520,
        "min_cycles": 3,
        "max_cycles": 23,
    }
    for key, expected in expected_profile.items():
        checks.append((profile[key] == expected, f"PINV profile {key}"))
    checks.append((round(profile["avg_cycles"], 2) == 16.66,
                   "PINV profile average"))

    for relative, marker in EVIDENCE_MARKERS:
        checks.append((marker in (ROOT / relative).read_text(),
                       f"evidence marker {marker}"))

    committed = ROOT / "docs" / "lucas_paper_tables.tex"
    if committed.exists():
        checks.append((committed.read_text() == generated_tables(),
                       "committed generated table is current"))

    failures = [label for passed, label in checks if not passed]
    return len(checks), failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, help="write generated LaTeX")
    parser.add_argument("--verify", action="store_true", help="verify oracle and ledger claims")
    args = parser.parse_args()

    if args.output:
        args.output.write_text(generated_tables())
        print(f"Wrote generated LaTeX to {args.output}")
    elif not args.verify:
        print(generated_tables(), end="")

    if args.verify:
        total, failures = verify()
        passed = total - len(failures)
        print(f"LUCAS publication oracle: {passed}/{total} passed")
        for failure in failures:
            print(f"  FAIL: {failure}")
        return 1 if failures else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
