#!/usr/bin/env python3
"""Package selected ROM/hex assets into build/spi_assets.tar.gz for SPI flashing.
Includes: vnorm_*, rplu_*, rational_sine_*, pade_*, params_*.hex, any other .mem/.hex small tables.
"""
import os
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / 'build'
OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT = OUT_DIR / 'spi_assets.tar.gz'

INCLUDE_DIR = ROOT / 'hardware' / 'common' / 'rtl' / 'gpu'
patterns = ['vnorm_*', 'v_real_*', 'rplu_*', 'rational_sine_*', 'pade_*', 'params_*.hex', 'exp_lut_*.mem']
files = []
for p in INCLUDE_DIR.iterdir():
    name = p.name
    for pat in patterns:
        from fnmatch import fnmatch
        if fnmatch(name, pat):
            files.append(p)
            break

# also include README manifest
manifest = OUT_DIR / 'spi_assets_manifest.txt'
with manifest.open('w') as mf:
    mf.write('SPI Assets manifest\n')
    mf.write('Generated by tools/package_spi_assets.py\n')
    mf.write('\nIncluded files:\n')
    for f in files:
        mf.write(f.relative_to(ROOT).as_posix() + '\n')

with tarfile.open(OUT, 'w:gz') as tar:
    tar.add(manifest, arcname='spi_assets_manifest.txt')
    for f in files:
        tar.add(f, arcname=f.relative_to(ROOT).as_posix())

print(f'Wrote {OUT} with {len(files)} files')
print('Files:')
for f in files:
    print(' -', f.relative_to(ROOT))
